### ISSUE TITLE
Funding: Change 'Award' to 'Funder'?

### ISSUE THREAD

**Issue by JGilbert-eLife** [substance/texture#1001]
I think ‘Awards’ is a little confusing as a heading. It might be better to refer to this as ‘Funders’ and individual entries as 'Funder' (e.g. 'add Funder') since I think this is fairly common terminology.

(In JATS, funding-group contains award-groups containing the individual funder details, so I see the logic of naming it following that, but 'award' has somewhat broader meaning than I think fits here)

**Comment by Integral** [comment]
Done via #1160.
