### ISSUE TITLE
Keywords: Adding Research organism variant

### ISSUE THREAD

**Issue by JGilbert-eLife** [substance/texture#1007]
eLife includes the following keyword group in addition to author keywords:

```
<kwd-group kwd-group-type="research-organism">
                <title>Research organism</title>
                <kwd>Human</kwd>
                <kwd>Machine</kwd>
            </kwd-group>
```

Research organisms are populated from a preset list, though I think additional free-text entries are also required. Italics are aloowed here, as with normal keywords.

**Comment by michael** [comment]
See Keywords feature in requirements document. Closing.
