### ISSUE TITLE
Support for figure supplements

### ISSUE THREAD

**Issue by michael** [substance/texture#1012]
We want to support "Stacks of Figures". At eLife there's one main figure and any number of figure supplements. The desired tagging for this in JATS is as follows:

```xml
<fig-group content-type="stack">
<fig id="fig3">...</fig><!--main figure-->
<fig id="fig3s1" specific-use="child-fig">...</fig><!--supplement 1 -->
<fig id="fig3s2" specific-use="child-fig">...</fig>
<fig id="fig3s3" specific-use="child-fig">...</fig>
</fig-group>
```

We added `content-type="stack"` to be able to distinguish this from another type of grouping ?`content-type="panels"`, which represents a single figure, consisting of multiple individual panels. (to be described in a separate issue).

We will have to adjust automatic labelling and detect such groups. Instead of Figure 3, Figure 4, Figure 5 we would need to generate "Figure 3, Figure 3 - supplement 1, Figure 3 supplement 2, ...". Is this general enough for a Stack feature?

**Comment by michael** [comment]
@dalapeyre there is just one use-case, we may also have which is a "stack of multi-panel figures". Therefore we would need nesting of fig-group like:

```xml
<fig-group content-type="stack">
  <fig-group content-type="panels" id="fig1">...</fig-group>
  <fig-group content-type="panels" id="fig2s1">...</fig-group>
</fig-group>
```

This is not a pressing issue, but maybe it would make sense to allow nesting fig-group elements in JATS. Up for discussion...

**Comment by michael** [comment]
eLife Example XML (of current corpus, not Dar):

```xml
<fig-group>
                        <fig id="fig2" position="float">
                            <object-id pub-id-type="doi">10.7554/eLife.00666.008</object-id>
                        <label>Figure 2.</label>
                        <caption>
                            <title>Figure with figure supplements. In the PDF this asset box will take full column width.</title> 
                            <p>This is the basic information provided about an article. <xref ref-type="fig" rid="fig1">Figure 1
                            </xref> shows an expanded view (<xref ref-type="bibr" rid="bib26">Kok et al., 2015</xref>; <xref ref-type="bibr" rid="bib28">National Institute of Mental 
                                Health, 1990</xref>).</p>
                        </caption>
                            <graphic mimetype="image" mime-subtype="tiff" xlink:href="elife-00666-fig2.tif"/>
                    </fig>
                        <fig id="fig2s1" position="float" specific-use="child-fig">
                            <!-- UPDATE: DOI prefix removed from XML but must be added for display--> 
                            <object-id pub-id-type="doi">10.7554/eLife.00666.009</object-id>
                            <label>Figure 2—figure supplement 1.</label>
                            <caption>
                                <title>The representation of the Major Subject Areas, Research Organisms and author keywords on the eLife HTML page</title>
                            </caption>
                            <graphic mimetype="image" mime-subtype="tiff" xlink:href="elife-00666-fig2-figsupp1.tif"/>
                        </fig>
                        <fig id="fig2s2" position="float" specific-use="child-fig">
                            <!-- UPDATE: DOI prefix removed from XML but must be added for display--> 
                            <object-id pub-id-type="doi">10.7554/eLife.00666.010</object-id>
                            <label>Figure 2—figure supplement 2.</label>
                            <caption>
                                <title>Representation of figure with figure supplements on the HTML view.</title>
                            </caption>
                            <graphic mimetype="image" mime-subtype="tiff" xlink:href="elife-00666-fig2-figsupp2.tif"/>
                        </fig>
</fig-group>
```

**Comment by dalapeyre** [comment]
looks fine to me.

—debbie

> On Nov 5, 2018, at 11:33 AM, Michael Aufreiter <notifications@github.com> wrote:
> 
> eLife Example XML (of current corpus, not Dar):
> 
> <fig-group
> >
>                         <
> fig id="fig2" position="float"
> >
>                             <
> object-id pub-id-type="doi">10.7554/eLife.00666.008</object-id
> >
>                         <
> label>Figure 2.</label
> >
>                         <
> caption
> >
>                             <
> title>Figure with figure supplements. In the PDF this asset box will take full column width.</title
> > 
>                             <
> p>This is the basic information provided about an article. <xref ref-type="fig" rid="fig1"
> >Figure 1
>                             </
> xref> shows an expanded view (<xref ref-type="bibr" rid="bib26">Kok et al., 2015</xref>; <xref ref-type="bibr" rid="bib28"
> >National Institute of Mental 
>                                 Health, 1990</
> xref>).</p
> >
>                         </
> caption
> >
>                             <
> graphic mimetype="image" mime-subtype="tiff" xlink:href="elife-00666-fig2.tif"
> />
>                     </
> fig
> >
>                         <
> fig id="fig2s1" position="float" specific-use="child-fig"
> >
>                             
> 
>  
>                             <
> object-id pub-id-type="doi">10.7554/eLife.00666.009</object-id
> >
>                             <
> label>Figure 2—figure supplement 1.</label
> >
>                             <
> caption
> >
>                                 <
> title>The representation of the Major Subject Areas, Research Organisms and author keywords on the eLife HTML page</title
> >
>                             </
> caption
> >
>                             <
> graphic mimetype="image" mime-subtype="tiff" xlink:href="elife-00666-fig2-figsupp1.tif"
> />
>                         </
> fig
> >
>                         <
> fig id="fig2s2" position="float" specific-use="child-fig"
> >
>                             
> 
>  
>                             <
> object-id pub-id-type="doi">10.7554/eLife.00666.010</object-id
> >
>                             <
> label>Figure 2—figure supplement 2.</label
> >
>                             <
> caption
> >
>                                 <
> title>Representation of figure with figure supplements on the HTML view.</title
> >
>                             </
> caption
> >
>                             <
> graphic mimetype="image" mime-subtype="tiff" xlink:href="elife-00666-fig2-figsupp2.tif"
> />
>                         </
> fig
> >
> </
> fig-group>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 


================================================================
Deborah A Lapeyre              mailto:dalapeyre@mulberrytech.com
Mulberry Technologies, Inc.      http://www.mulberrytech.com
17 West Jefferson Street         Phone: 301-315-9631 (USA)
Suite 207                        Fax:   301-315-8385
Rockville, MD 20850
----------------------------------------------------------------
Mulberry Technologies: Consultancy for XML, XSLT, and Schematron
================================================================

**Comment by Melissa37** [comment]
@michael Thanks for this.
I personally prefer the option that eLife figure supplements are contained within the same fig group as their parent (like eLife does it). I think semantically this is more correct and negates the need to have nested fig groups. I think attributes on the ```<fig>``` and ```<fig-group>``` can manage the distinctions between your two use-cases.

**Comment by michael** [comment]
@Melissa37 @dalapeyre nested fig-groups we only need when the actual figures are of this new multipanel figure type. So we would need this only if SourceData wanted figure supplements (of which each is another group of panels = multi-panel fig). But let's neglect this use-case for now.

**Comment by dalapeyre** [comment]
Thank you.  —Debbie

**Comment by oliver----** [comment]
We have added support for sub-figures. What is missing to achieve 'figure supplements' is a means to tag a sub-figure as being 'supplementary' and a label generator, that takes this into account and produce something like 'Figure 1-figure supplement 2'.

**Comment by dalapeyre** [comment]
> On Jan 16, 2019, at 2:49 AM, Oliver Buchtala <notifications@github.com> wrote:
> 
> We have added support for sub-figures. What is missing to achieve 'figure supplements' is a means to tag a sub-figure as being 'supplementary' and a label generator, that takes this into account and produce something like 'Figure 1-figure supplement 2'.
> 
> 

I thought we had agreed that these were just sub-figures
in a <fig-group> with either a @content-type or a 
@specific-use of “supplement" on  each individual figure.

Figures can take labels, either
  'Figure 1-figure supplement 2’
or just 
>  '-figure supplement 2’
if you expect figure numbers to be autogenerated.
The rules are different it type =“supplement”

Doesn't this work?

—Debbie







================================================================
Deborah A Lapeyre              mailto:dalapeyre@mulberrytech.com
Mulberry Technologies, Inc.      http://www.mulberrytech.com
17 West Jefferson Street         Phone: 301-315-9631 (USA)
Suite 207                        Fax:   301-315-8385
Rockville, MD 20850
----------------------------------------------------------------
Mulberry Technologies: Consultancy for XML, XSLT, and Schematron
================================================================
