### ISSUE TITLE
Add support for supplementary-material in caption

### ISSUE THREAD

**Issue by JGilbert-eLife** [substance/texture#1016]
eLife allows two types of `<supplementary-material>` within `<caption>` for figures, tables and videos - source data and source code.

(This is a separate but related use of supplementary-material at the article level, see #1015 )

Examples:

Source data for a table:

```
                    <table-wrap id="table3" position="float">
                        <object-id pub-id-type="doi">10.7554/eLife.00666.005</object-id>
                        <label>Table 3.</label>
                        <caption><p></p>
                            <p><supplementary-material id="table3sdata1">
                                <object-id pub-id-type="doi">10.7554/eLife.00666.006</object-id>
                                <label>Table 3—source data 1.</label>
                                <caption><title>Representative curves of steady-state kinetic analyses for each IGF1R protein characterized.</title>
                                    <p>Each data point was performed in duplicate and is shown separately.</p>
                                </caption>
                                <media mimetype="application" mime-subtype="xlsx" xlink:href="elife-00666-table3-data1.xlsx"/>
                            </supplementary-material>
                            </p>
                        </caption>
                    . . . . . . .

```

Source data for a figure supplement (see: #1012) 

```
<fig id="fig3s1" position="float" specific-use="child-fig">
                            <object-id pub-id-type="doi">10.7554/eLife.00666.012</object-id>
                            <label>Figure 3—figure supplement 1.</label>
                            <caption>
                                <title>Title of the figure supplement</title>
                                    <p>
                                        <supplementary-material id="fig3sdata1">
                                            <object-id pub-id-type="doi">10.7554/eLife.00666.013</object-id>
                                            <label>Figure 3—figure supplement 1—source data 1.</label>
                                            <caption>
                                            <title>Title of the figure supplement source data.</title>
                                            <p>Legend of the figure supplement source data.</p>
                                            </caption>
                                            <media mimetype="application" mime-subtype="xlsx" xlink:href="elife-00666-fig3-figsupp1-data1.xlsx"/>
                                        </supplementary-material>
                                    </p>
                            </caption>
                            <graphic mimetype="image" mime-subtype="tiff" xlink:href="elife-00666-fig3-figsupp1.tif"/>
                        </fig>
```

Source code for a video:

```
<media mimetype="video" mime-subtype="mp4" id="video1" xlink:href="elife-00666-video1.mp4">
                        <object-id pub-id-type="doi">10.7554/eLife.00666.016</object-id>
                        <label>Video 1.</label>
                        <caption>
                            <title>
                                A description of the eLife editorial process.
                            </title>
                            <p><supplementary-material id="video1scode1">
                                <object-id pub-id-type="doi">10.7554/eLife.00666.037</object-id>
                                <label>Video 1—source code 1.</label>
                                <caption>
                                    <title>Title of the source code.</title>
                                    <p>Legend of the source code.</p>
                                </caption>
                                <media mimetype="application" mime-subtype="xlsx" xlink:href="elife-00666-video1-code1.xlsx"/>
                            </supplementary-material>
                            </p>
                        </caption>
                    </media>
```

**Comment by michael** [comment]
We had discussed exactly this topic today with SourceData as we also supported supplementary files inside figure captions. However we came to the conclusion that it's much more elegant to have all supp materials in the main text, but reference them from the figure caption, to tie them together. Another reason is that JATS does not allow supplementary-material inside captions, only through the backdoor of wrapping it in a paragraph.

@Melissa37 @JGilbert-eLife could you meditate about that proposal instead of the inline supps inside captions? ;-) Let us know what would be negative implications of that switch.

@dalapeyre what is your opinion about the use (abuse?) of `caption > p > supplementary-material`?

**Comment by Melissa37** [comment]
@thewilkybarkid @gnott @lsh-0  do you have any thoughts on this? We are concerned about an explicit link between the figures and their suppl materials, which we want to display together, but whether they are actually physically together in the XML could impact on this? Not sure how PMC would deal with this, but I thought I'd start with you guys first.

**Comment by thewilkybarkid** [comment]
In my mind these shouldn't be in a caption, but moving them (eg directly inside `<fig>`) doesn't resolve the `<p>` issue, which is also odd.

What would moving them look like? Assume to a `<sec>` inside `<back>`? Can't see a sensible mechanism for linking to it from a `<fig>` etc...

**Comment by dalapeyre** [comment]
Pardon me for being dense.

I thought we has agreed that this was just a figure group,
one of which was a regular figure and some of which
were supplementary figures. (Apparently that was my idea,
not agreement. Sorry)

Is your idea that a figure group could contain either:
 - figures (<fig>), or 
 - inner figure groups (<fig-group), or
 - supplementary material (<supplementary-material>)?

If so, we could ask the JATS SC for that.

But they might ask why you could not tag that as:
   <fig-group>
     <fig>…</fig>
     <fig-group specific-use="supplementary-material">
       <fig>…</fig> 
       <fig>…</fig> 
       <fig>…</fig>
     </fig-group> 
   </fig-groiup>

If your rationale is that these are not figures, but
actually <supplementary-material>, we can ask the SC.

The link(s) would be the containment.

 —Debbie

> On Feb 5, 2019, at 5:53 AM, Melissa Harrison <notifications@github.com> wrote:
> 
> @thewilkybarkid @gnott @lsh-0 do you have any thoughts on this? We are concerned about an explicit link between the figures and their suppl materials, which we want to display together, but whether they are actually physically together in the XML could impact on this? Not sure how PMC would deal with this, but I thought I'd start with you guys first.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 


================================================================
Deborah A Lapeyre              mailto:dalapeyre@mulberrytech.com
Mulberry Technologies, Inc.      http://www.mulberrytech.com
17 West Jefferson Street         Phone: 301-315-9631 (USA)
Suite 207                        Fax:   301-315-8385
Rockville, MD 20850
----------------------------------------------------------------
Mulberry Technologies: Consultancy for XML, XSLT, and Schematron
================================================================

**Comment by JGilbert-eLife** [comment]
The idea is to associate source data with the specific figure (or supplementary figure) to which it relates. This can lead to cases where we have a Figure that has source data AND figure supplements that can themselves have source data:

Figure 1
> Figure 1—source data 1
> Figure 1—source data 2

> Figure 1—figure supplement 1
>>Figure 1—figure supplement 1—source data 1
>>Figure 1—figure supplement 1—source data 2

> Figure 1—figure supplement 2
>>Figure 1—figure supplement 2—source data 1

This connects source data files directly to the figure to which they relate, making the relationships very clear, rather than just placing the source data all together in a separate section.

Our current placement of  `<supplementary-material>` in `<p>` within `<caption>` is an attempt to approximate this relationship, so cutting out the middle-man with a change to JATS would help us greatly. E.g. if we could do

```
<fig> . . .
     <supplementary-material> . . . </supplementary-material>
</fig>
```

then our use of `<fig-group>` to contain a set of `<fig>`s would allow for the full figure supplement and source data structure outlined above.

```
<fig-group>
     <fig id="fig2" position="float">
          <label>Figure 2.</label>
          <caption>
          . . .
          </caption>
          <graphic mimetype="image" mime-subtype="tiff" xlink:href="elife-00666-fig2.tif"/>
          <supplementary-material id="fig3sdata1">
               <label>Figure 2—figure supplement 1—source data 1.</label>
               <caption>
                . . . 
               </caption>
               <media mimetype="application" mime-subtype="xlsx" xlink:href="elife-00666-fig2-figsupp1-data1.xlsx"/>
          </supplementary-material>
     </fig>
     <fig id="fig2s1" position="float" specific-use="child-fig">
          <label>Figure 2—figure supplement 1.</label>
          <caption>
          . . . 
          </caption>
          <graphic mimetype="image" mime-subtype="tiff" xlink:href="elife-00666-fig2-figsupp1.tif"/>
          <supplementary-material id="fig3sdata1">
               <label>Figure 2—figure supplement 1—source data 1.</label>
               <caption>
                . . . 
               </caption>
               <media mimetype="application" mime-subtype="xlsx" xlink:href="elife-00666-fig2-figsupp1-data1.xlsx"/>
          </supplementary-material>
     </fig>
</fig-group>
```

An argument I can see for doing it this way is that it maintains the distinction between a figure and another kind of file (the general use of supplementary-material).

**Comment by michael** [comment]
We had that discussion recently with SourceData. We came to the conclusion that stand-alone supp files (in a separate section) and linking them with figures by creating references in the caption is the most flexible:

- source data file could be reused (e.g. if it's used by two figures)
- nested editing becomes cumbersome
- supp-files are not supported in caption (only works through `p > supplementary-material` hack)

Here's how it looks when supp file is in the caption (ugly nesting)

http://cdn.substance.io/figure-package-preview-1/?archive=figure-package

And here's the xref-linked version:

http://cdn.substance.io/figure-package-preview-2/?archive=figure-package

**Comment by dalapeyre** [comment]
I thought the requirement was for them all to be inside the same
grouping. What eLife had looked like a figure group with 4
figures, 3 of which were supplemental figures.

But I admit that I like cross-references much better (they are
closer to the real semantics), and using cross-refernces  
requires no JATS changes. Datasets are not typically published
with the paper, but pointed to. I like the argument that one dataset
could supply several figures, as one affiliation could
be shared by multiple authors.

—Debbie



> On Feb 7, 2019, at 4:46 AM, Michael Aufreiter <notifications@github.com> wrote:
> 
> We had that discussion recently with SourceData. We came to the conclusion that stand-alone supp files (in a separate section) and linking them with figures by creating references in the caption is the most flexible:
> 
> 	• source data file could be reused (e.g. if it's used by two figures)
> 	• nested editing becomes cumbersome
> 	• supp-files are not supported in caption (only works through p > supplementary-material hack)
> Here's how it looks when supp file is in the caption (ugly nesting)
> 
> http://cdn.substance.io/figure-package-preview-1/?archive=figure-package
> 
> And here's the xref-linked version:
> 
> http://cdn.substance.io/figure-package-preview-2/?archive=figure-package
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 


================================================================
Deborah A Lapeyre              mailto:dalapeyre@mulberrytech.com
Mulberry Technologies, Inc.      http://www.mulberrytech.com
17 West Jefferson Street         Phone: 301-315-9631 (USA)
Suite 207                        Fax:   301-315-8385
Rockville, MD 20850
----------------------------------------------------------------
Mulberry Technologies: Consultancy for XML, XSLT, and Schematron
================================================================

**Comment by Melissa37** [comment]
Hi @michael I think there is some confusion but the EMBO use case is different to the eLife use-case. @JGilbert-eLife @FAtherden-eLife and I would be happy to have a call with you about this.

**Comment by michael** [comment]
I've captured the requirements in this feature spec here. https://github.com/substance/texture/issues/1245

Let's continue the discussion there.
