### ISSUE TITLE
Add support for inline graphics

### ISSUE THREAD

**Issue by JGilbert-eLife** [substance/texture#1018]
eLife does allow inline graphics as distinct from main figures. We are reconsidering their use in general but we have examples in the archive of this being used to place images within tables.

```
<sec id="s2-6-4">
                    <title>Inline graphics</title>
                    <p> Here is an example of pulling in an inline graphic <inline-graphic mimetype="image" mime-subtype="jpeg" xlink:href="elife-00666-inf001.jpeg"/>.</p>
                </sec>
```

**Comment by Integral** [comment]
<img width="636" alt="screen shot 2018-11-18 at 19 03 03" src="https://user-images.githubusercontent.com/182010/48675091-71e72c80-eb65-11e8-9103-62965935d0d0.png">
