### ISSUE TITLE
Undo not working in metadata editor

### ISSUE THREAD

**Issue by fabiobatalha** [substance/texture#1040]
After remove an affiliation and try to undo this action the affiliation was not recovered.

**Comment by fabiobatalha** [comment]
I noticed also that all the metadata toolbar stops to work after clicking the undo button.

**Comment by oliver----** [comment]
Confirmed.

**Comment by oliver----** [comment]
I will add 'Undo' to all tests for adding entities. This way we should be able to cover this.
