### ISSUE TITLE
Graphic load error: Infinite cycle of rerendering 

### ISSUE THREAD

**Issue by Integral** [substance/texture#1048]
![](http://g.recordit.co/GYp2oiBrOT.gif)
<img width="549" alt="screen shot 2018-11-26 at 19 11 10" src="https://user-images.githubusercontent.com/182010/49026502-12b19980-f1af-11e8-89c4-aaed736eb69b.png">

**Comment by michael** [comment]
How to reproduce?

**Comment by Integral** [comment]
@michael just remove image from dist folder and open the document

**Comment by Integral** [comment]
this is a general way to reproduce `load error` which we are handling, but now in a bad way...

**Comment by Integral** [comment]
I am sorry, it is not on master. Forget about this.
