### ISSUE TITLE
Feature proposal: Ordering document sections through the TOC panel

### ISSUE THREAD

**Issue by unixba** [substance/texture#105]
Hi everyone,

I think it would be great if Texture offered the possibility to arrange the order of sections and subsections in the document by simply dragging-and-dropping them inside the Table of Contents panel.

This would relieve the authors from the error-prone task of cutting and pasting parts of the document to rearrange them, and would instead provide them with a rather pleasing experience of visually arranging the sections of their document.

Furthermore, each section heading in the Table of Contents panel could have additional two icons attached to it: an "eye" and a "padlock" (similar to what layers have in a photo editing application).

The "eye" icon would be used to hide certain parts of the text and leave visible only those sections which the author wants to work on.

The "padlock" icon would enable the author to lock certain sections and subsections to prevent their accidental change or reordering.

Hope you find these suggestions useful.

Cheers,
Kenan

**Comment by michael** [comment]
Hi!

Restructuring a doc via drag+drop is a bit tricky (there are a number of edge cases e.g. what to do when somebody wants to drag a level 3 section into another level 3 section. However will allow adjusting the level from the TOC as described here: #130
