### ISSUE TITLE
Isolated node didn't got selected via keyboard

### ISSUE THREAD

**Issue by Integral** [substance/texture#1053]
E.g. if use keyboard I have no chance to insert paragraph between figures or remove one of them.
I'm jumping between internal fields of figures, look:
![](http://g.recordit.co/SCicXXJmDm.gif)
While I would expect this state as well:
![screen shot 2018-11-29 at 16 11 43](https://user-images.githubusercontent.com/182010/49224194-d326bf80-f3f1-11e8-9a75-19e065c9827c.png)

**Comment by oliver----** [comment]
During the 1.0 development we decided that 'open' isolated nodes results in a nicer UX than 'closed' ones. You can select a whole node by clicking something which is not editable, e.g. the border, or by using ESC when inside one of the fields.
