### ISSUE TITLE
Footnotes seems not to work properly

### ISSUE THREAD

**Issue by fabiobatalha** [substance/texture#1058]
When a footnote is included in the metadata scope it is not possible to write a text on it.

**Comment by oliver----** [comment]
This is how it looks like in the current version.

![texture-insert-footnote](https://user-images.githubusercontent.com/284099/49513955-deb33400-f892-11e8-93c7-bc0a55d53e2a.gif)

**Comment by oliver----** [comment]
Closing this, assuming that the issue has been resolved.
