### ISSUE TITLE
CONTRIBUTING.md dead links

### ISSUE THREAD

**Issue by Bachstelze** [substance/texture#106]
all links in https://github.com/substance/texture/blob/develop/CONTRIBUTING.md are dead... is there a new documentation?

**Comment by michael** [comment]
Hi thanks for reporting. 

Only the locations of the source files changed. Will fix.

**Comment by michael** [comment]
Fixed.

**Comment by Bachstelze** [comment]
ohh nice, the evening lecture is saved
