### ISSUE TITLE
Ability to create definition lists

### ISSUE THREAD

**Issue by fabiobatalha** [substance/texture#1061]
Definition lists should be used to 

### Author
- 

### Production staff
- As Production staff, I want to be able to edit a definition list to fix any errors that were not identified in previous production steps
- As a Production staff, I want to be able to copy and paste a definition list from one place to another in the document, to fix any positioning error
- As a Production staff, I want to include items in a definition list to fix any error that were not identified in previous production steps  

### But what if . . . ?
- 

### Considerations
- 

## XML requirements

JATS Spec: https://jats.nlm.nih.gov/publishing/tag-library/1.1/element/def-list.html

### Érudit Examples

**Example 1:** https://www.erudit.org/fr/revues/ltp/2012-v68-n1-ltp0139/1010219ar/

``` xml
<def-list>
	<def-item>
		<term>Florian Philippot (Front national, FN), Extrême droite</term>
		<def>36,06</def>
	</def-item>
	<def-item>
		<term>Philippe Richert (Union de la droite, UD), Droite</term>
		<def>25,83</def>
	</def-item>
	<def-item>
		<term>Jean-Pierre Masseret (Union de la gauche, UG), Gauche</term>
		<def>16,11</def>
	</def-item>
	<def-item>
		<term>Sandrine Bélier (Europe Ecologie Les Verts, EELV), Ecologistes</term>
		<def>6,70</def>
	</def-item>
        ...
</def-list>
```
**Example 2:**

``` xml
<def-list>
  <def-item>
    <term>§ 1 Consequenter, queritur de interiectione utrum sit pars orationis.</term>
    <def><bold>§ 1 </bold>[Question 1.1] Conséquemment, on se demande si l’interjection est une partie du discours.</def>
  </def-item>
  <def-item>
    <term>§ 2 Et uidetur quod non, quia omnis pars orationis inponitur1 a ratione ad significandumA ; set interiectio non
        inponitur a ratione ad significandum, ergo non est pars orationis. Maior patet de se. .IIII.2 enim3 manifestatur sic, nam si interiectio inponeretur a ratione
        ad significandum, non proferetur uoce incondita nec uoce irrationali ; set profertur uoce incondita, sicut dicit PriscianusB, ergo non est inposita a ratione &lt;ad significandum&gt;4.</term>
    <def><bold>§ 2</bold> [Argument 1 de la question 1.1] Et il semble que ce n’est pas le cas, parce que toute partie du discours est imposée par une propriété de signification ; or l’interjection n’est
        pas imposée par une propriété de signification, donc elle n’est pas une partie du discours. La majeure va de soi. En effet, le fait que l’interjection ne soit pas imposée par une propriété de signification est montré ainsi :
        si l’interjection était imposée par une propriété de signification, elle ne serait pas proférée par un son vocal inconnu ni par un son vocal irrationnel ; or elle est proférée par un son vocal inconnu, comme le dit Priscien,
        donc elle n’est pas imposée par une propriété de signification.</def>
  </def-item>
  ...
</def-list>
```

**Comment by Melissa37** [comment]
@fabiobatalha can you provide some XML samples and perhaps screenshots of display?

@JGilbert-eLife @FAtherden-eLife will help write some user stories for this, Fred has experience of this tagging from a previous role.
We see it as a feature Texture should support and so should spec out this ticket

**Comment by JGilbert-eLife** [comment]
Hi @fabiobatalha - what do you think of the following user stories? Do these cover everything you require from this item? Is this another case where translations will be relevant and if so, how do you handle that at the moment?

- As production staff, I want to be able to create a definition list so that I can define the terms used in an article.
- As production staff, I want to be able to add a term and its definition to a definition list so that I can expand the terms it covers.
- As production staff, I want to be able to edit a term and its definition from a definition list so that I can correct any errors.
- As production staff, I want to be able to remove a term and its definition from a definition list so that I can correct any errors.
- As production staff, I want to be able to move a definition list from one place to another so that I can correct errors in its positioning.
- As production staff, I want to be able to delete a definition list so that I can correct an error.

**Comment by FAtherden-eLife** [comment]
@fabiobatalha do you have any need to link to definitions in your content. One way in which I've seen `def-list` used is like the following:
```xml
<glossary>
    <def-list>
        ...
        <def-item id="def-1">
            <term>Q</term>
            <def>[William Shakespeare], <italic>The Tragedy of King Richard the third</italic>, 1597 (first quarto)</def>
        </def-item>
        <def-item id="def-2">
            <term>Q2</term>
            <def>[William Shakespeare], <italic>The Tragedy of King Richard the third</italic>, 1598 (second quarto)</def>
        </def-item>
        ...
    <def-list>
</glossary>
...

<fn><p>The two lines that appear in <xref ref-type="other" rid="def-2">Q2</xref> and subsequent quartos are missing from all known copies of <xref ref-type="other" rid="def-1">Q</xref>. They probably ... </p></fn>
...
```

**Comment by fabiobatalha** [comment]
We don't have this use case in our corpus. (Links to def-list)

**Comment by fabiobatalha** [comment]
Continue at: https://github.com/substance/texture/issues/1339
