### ISSUE TITLE
inline-graphic resizing images

### ISSUE THREAD

**Issue by fabiobatalha** [substance/texture#1065]
What is the ideal approach to produce images to be used in inline-graphics?

It seems Texture is resizing the images while rendering it in the editor. It makes difficult to see the images inserted in the text.

**Comment by oliver----** [comment]
@fabiobatalha Image size is a good general question which we should think about. What would be your requirements here in general?

In the case of inline-graphics I remember @Integral mentioned something about a max-height currently, to avoid an inline image stretching to wide in height. However I guess we should disable this 'hack' and instead come-up with an idea for controlling the size.

**Comment by Integral** [comment]
Yes, currently height restricted to font size to avoid changing of line
height.

**Comment by fabiobatalha** [comment]
@oliver---- Yes it is a trick issue.

The following image should illustrate what I'm talking about, and it seems to be related to the max-height (hack).

    In the paragraph L'agglomération autor.....

There is an inline-graph with the image ![x](https://user-images.githubusercontent.com/504142/49457756-63ca1a80-f7b9-11e8-9c27-7c35a6958752.png)

I put two versions of the same image:

* The original one with a ruge white space in the top and bottom of the image
* And a second image removing the maximum of white spaces I can remove

In the second example, the preview in better but still not good as expected.

The PDF is also available as a parameter of what we expect to see.

![capture du 2018-12-04 11-36-16](https://user-images.githubusercontent.com/504142/49457642-2bc2d780-f7b9-11e8-9057-409db9b88ca0.png)

**Comment by oliver----** [comment]
Just looked at the JATS spec. There seems to be no way to store desired height and width.

Thus, the only way I see so far is controlling the size via the image file itself. @fabiobatalha do you have a different idea?

@Integral we should remove the height restriction, and leave the problem to the image owner :)

**Comment by oliver----** [comment]
I noticed that there is a baseline-shift attribute on inline-grahic. @fabiobatalha could this help somehow?

**Comment by fabiobatalha** [comment]
@oliver---- I'm not sure how it can help.

I would say:
* The images should be displayed in their original size.
* This size should be controlled by the person who is editing the text.
* Texture should allow a minimum top and bottom overlap between one line and another while dealing with inline-graphics (I don't know how to do this)
  * maybe inline-graph should be (vertical-align: middle;)

**Comment by oliver----** [comment]
Fine with your suggestion.
The baseline-shift can be used to add certain vertical displacement. But not the size.
