### ISSUE TITLE
Can you give me some suggestion? How to convert the documents to PDF

### ISSUE THREAD

**Issue by YSZYCF** [substance/texture#1071]

**Comment by michael** [comment]
PDF export will be covered by external tools, and is out of scope for the Texture editor.

**Comment by jcolomb** [comment]
- as a researcher, I want to share my dar figure with my boss (on slack) for peer review.

No one will be able to get to use the tool if everybody needs to install texture.

**Comment by Melissa37** [comment]
Hi @jcolomb eLife and other members of the consortium are looking into this separately - there is no GitHub repo or anything for this work yet and no planned delivery, but it will be open sourced if/when we achieve it.

**Comment by jkanche** [comment]
would a solution for this be 

- dar -> jats (dont know what to use here)  
- jats -> pdf (using pandoc)

any suggestions for the first step ?

**Comment by Melissa37** [comment]
@jkanche Thanks!

DAR is JATS :-)

It's a strict JATS format

**Comment by fabiobatalha** [comment]
@jkanche

Rename your dar file extension to zip, unzip the file and you will have access to the JATS file and assets.

To convert JATS you can use XSLT conventions to HTML and after that use any libraries to convert HTML to PDF, ex:

Paged.JS
Weasyprint
Pandoc
