### ISSUE TITLE
Improve styles for tables in meta-data view

### ISSUE THREAD

**Issue by oliver----** [substance/texture#1072]
See this comment: https://github.com/substance/texture/pull/1057#issuecomment-444439889

**Comment by Integral** [comment]
Somehow tables are looking quite ok now:
![screen shot 2019-01-19 at 22 08 00](https://user-images.githubusercontent.com/182010/51431223-e3f7f280-1c36-11e9-904c-df2c6333a4cd.png)

So I will close this issue.
