### ISSUE TITLE
Deployment of .dar files

### ISSUE THREAD

**Issue by hyglac** [substance/texture#1101]
Texture would be great as a tool for production editors like myself. I could quickly and cleanly transition a paper from Word to JATS XML. However, after reading the documentation and checking out OTS, it is still unclear for me how I would deploy a .dar file online within OJS platform, for instance.

Can anybody please help me with this?

**Comment by michael** [comment]
Hi! A Dar archive is essentially a folder that includes the JATS XML files + all assets, as well as a manifest file. So OJS would need to allow access to those files in their Texture integration.
