### ISSUE TITLE
Internal: add test for ReferenceUpload and DOIImport

### ISSUE THREAD

**Issue by oliver----** [substance/texture#1113]
- [x] test general functionality
- [x] `DOIInputComponent.js` should be test covered
- [x] `ReferenceUploadComponent.js` should be test covered
- [x] `BibConversion.js` should be test covered
- [x] `QueryComponent.js` should be test covered

**Comment by Integral** [comment]
We've added some test and increase coverage in #1169, so for now I will close it. However this should be improved in the future.
