### ISSUE TITLE
Implement more minimal navigation for sub-figures

### ISSUE THREAD

**Issue by michael** [substance/texture#1121]
The thumbnails are eating space and cause edge cases (e.g. we need a carousel with size measuring etc.), so we need a more scalable solution. Here it is:

![image](https://user-images.githubusercontent.com/2931/51907660-c3166680-23c7-11e9-84d4-4c74b94e00db.png)

@Integral can you implement this?

**Comment by michael** [comment]
@Melissa37 this is for finishing the current iteration with SourceData. It shows the UI for the authoring view, not for the QC view / author proofing where we have all sub-figures expanded.

**Comment by oliver----** [comment]
Done via #1125
