### ISSUE TITLE
Allow 'insert authors' from insert menu

### ISSUE THREAD

**Issue by evabenitoembo** [substance/texture#1135]
![image](https://user-images.githubusercontent.com/31538460/52274477-1d29a580-294d-11e9-81fe-c7fa45f5ecb0.png)

the insert menu does not allow to insert authors. Authors first name, last name, email as input fields in manuscript view would make things easier for this important information. Prepopulated by default?

**Comment by michael** [comment]
We will take care of this.

**Comment by evabenitoembo** [comment]
Great, thanks!

**Comment by Integral** [comment]
Now you can add authors and other entities from manuscript (#1169). This will bring you to the new item in metadata view. We will improve this later, closing this issue for now.
