### ISSUE TITLE
Figure-linked "Supplementary files" should be relabeled "source data file".

### ISSUE THREAD

**Issue by evabenitoembo** [substance/texture#1141]
Only when inside a figure/panel, not at paper level! See related issue #1145  

![image](https://user-images.githubusercontent.com/31538460/52274966-7e05ad80-294e-11e9-96cc-7884272eaa08.png)

**Comment by michael** [comment]
I'd suggest to use a pre configured section title "Source Data Files" and another one "Additional files". The label "Supplementary File ?" is the most generic, so it would be best to keep that. However you can label these things differently in your presentation of the data.

**Comment by michael** [comment]
We could let you configure the label generator to use "Source Data File" but then if you upload e.g. a zip or docx, pdf etc. that would not be correct anymore. OK to leave this as is and you optimise on your front-end based on the file type?

**Comment by evabenitoembo** [comment]
We understand the power of having references to data files and think this would be very useful for pure 'supplementary files'. However, the identity of SourceData packages is in fact that they contain data associated with each panel or figure, so we should really rename those to be differential from 'general' supplementary files at the paper level that might be cited several times in the manuscript. We feel very strongly about this, in particular about the fact that it should be possible to attach files/urls to a panel almost physically and not 'only' as a reference... we might need to discuss this in a separate thread/call to really expand on this concept. I will organize a separate meeting.

**Comment by michael** [comment]
I've captured the requirements here in a Feature ticket. https://github.com/substance/texture/issues/1245

Closing this issue.
