### ISSUE TITLE
Texture integration with non node.js web app

### ISSUE THREAD

**Issue by kaschioudi** [substance/texture#115]
Hi guys,

I am trying to integrate the latest version of the editor with OTS but so far no luck.. Correct me if I am wrong but it seems to me that the sample integration code from the README file is written in ES6 and assumes node.js environment. 

That being said, I have followed the install steps and was able to generate bundle files running `npm run bundle`. From here I need to create a custom XML store and load texture in a PHP web app.  Could you please provide some guidance?  Thanks.

**Comment by michael** [comment]
Hey!

You should be good with integrating the latest release (pre-built bundle). Visit the releases page on Github or download with the link below.

https://github.com/substance/texture/releases/download/v1.0.0-alpha.2/texture-1.0.0-alpha.2.zip

**Comment by michael** [comment]
In the examples you (e.g. author.html) you see code like this:

```js
    var configurator = new t.TextureConfigurator()
      .import(t.AuthorPackage)
      .setXMLStore(t.ExampleXMLStore, XMLFILES)
```

in setXMLStore you can provide your own store, which can be implemented in ES5 (for compatibility)

E.g. like this:

```js
    function OJSXMLStore() {
      this.readXML = function(documentId, cb) {
        // Some AJAX
        // cb(null, xmlString)
      };

      this.writeXML = function(docuemntId, xml, cb) {
        // SOME AJAX for saving the xml
        // cb(null) when done and no error
      }
    }

    /* Author Configuration */
    var configurator = new t.TextureConfigurator()
      .import(t.AuthorPackage)
      .setXMLStore(OJSXMLStore)
```

**Comment by kaschioudi** [comment]
Great! I will give it another try. thanks for the quick reply.
