### ISSUE TITLE
Small caps rendering

### ISSUE THREAD

**Issue by FAtherden-eLife** [substance/texture#1166]
JATS element [sc](https://jats.nlm.nih.gov/archiving/tag-library/1.1d1/n-ary0.html) is used in eLife content to flag small caps rendering. Currently this displays as follows in Texture:

![screen shot 2019-02-11 at 14 15 02](https://user-images.githubusercontent.com/43879983/52568713-71c69800-2e07-11e9-92b1-61bb5104b10c.png)

Markup for reference:
``<abstract>
        <p>This is the abstract. An abstract can contain any formatting, such as <italic>italics</italic>,<bold>bold</bold>,<sup>superscript</sup>,<sub>subscript</sub>or<sc>small caps</sc>. MathML is
                    also allowed:<inline-formula>
            <tex-math>\overset{}{p}_{m} = 0</tex-math>
          </inline-formula>.</p>
      </abstract>``

**Comment by oliver----** [comment]
Fixed via #1169
