### ISSUE TITLE
Improve contextual menu UI + mode switcher

### ISSUE THREAD

**Issue by michael** [substance/texture#1189]
![image](https://user-images.githubusercontent.com/2931/53011398-8c6cc280-3440-11e9-88bd-593c3a80f016.png)

It would improve usability to merge all contextual actions into one menu (displayed on the right edge of the menu bar). We'd also show the category of actions (e.g. Authors, vs Chapters actions).

Additionally I propose to move the mode switcher to the left side, and implement tabs instead of a dropdown (faster switches, and moving all navigation UI closer together).

This would mean the mode switcher is not available in mobile mode, which is acceptable for the moment. However we could have a redundant mode switcher in the regular toolbar, but only show in mobile mode.

**Comment by oliver----** [comment]
Done via #1191
