### ISSUE TITLE
Footnote support in Texture

### ISSUE THREAD

**Issue by michael** [substance/texture#119]
We should try to normalize usage of footnotes in Texture. In todays publications they are used frequently to encode metadata (e.g. to reference affiliations of an author). However according to best practice we should have one fn-group at the bottom.

> Best Practice: When footnotes are grouped at the end of an article, wrap them in a `fn-group` and use an `xref` element in the text, as usual, to tie each footnote in the list to a particular location in the text.

I'd propose that we use the first fn-group in the backmatter to store all footnotes (when created through the editor). We can then automatically generate labels for the xrefs referencing the footnotes.

When `<fn>` elements are present in the article body (e.g. when using an existing JATS file) users can edit them using the XML editor widget.

Any concerns with this approach? We can always tweak that, but it could be a reasonable start.

**Comment by michael** [comment]
@jalperin @axfelix can you comment that?

**Comment by jalperin** [comment]
I am not sure of how they need to be handled in the JATS, I think @axfelix should be able to comment, but I do know that front-matter footnotes have different rules than those in the body. 

- the same footnote can appear multiple times ( i.e., multiple authors from the same affiliation) 
- they sometimes use symbols instead of numbers 
- numbering of the first footnote in the body should always start at 1, regardless of front matter footnotes

**Comment by michael** [comment]
Yeah I'm aware of some of those uses from the XML files I've seen. As said, I think they tend to be used often in the context of metadata (e.g. associating an affiliation to an author or referencing a funding institution). But there are better (more semantic) ways to encode such metadata, so I'd like to tailor the editor so that footnotes are referenced from the article body using automatic numbering. And for metadata, we'd then use the semantic tags (e.g. funding-source).

**Comment by axfelix** [comment]
Yeah, I think there are always more semantic ways of encoding front matter footnotes... none of the parsers we use currently for producing JATS from Word/PDF input will produce front matter footnotes. I'm OK with just using the XML editor fallback for existing ones if there isn't a good way to force them into affiliations.

However, I'm a little concerned about using the XML editor fallback for `<fn>` that are present in the body -- even if we enforce a single `<fn-group>` on export, I don't think the distinction is going to be clear to many users, and I'd like to give everyone the same body-text-footnote experience.

**Comment by michael** [comment]
We thought about normalizing steps in such cases:

Like when opening a doc, a prompt is displayed that fn's present in the body will be moved into an fn-group in the back and that instead an xref is placed. 

We could so the same if we detect a fig element inside a paragraph and pull it out to the section level. Would that be ok?

**Comment by axfelix** [comment]
Yeah, I think that would be perfect. We can probably even toggle off such prompts by default.

**Comment by michael** [comment]
Btw: It's easier to implement this without the prompt. For a start... ;-)

**Comment by michael** [comment]
Done.
