### ISSUE TITLE
Desktop app don't save after insert figure

### ISSUE THREAD

**Issue by yoruyenturk** [substance/texture#1214]
Hi,

I tested 2.0 desktop app. We can't save document after insert figure.

**Comment by michael** [comment]
@yoruyenturk can confirm this. Sorry for this. We're working on a fix.

**Comment by yoruyenturk** [comment]
Thanks your response.

**Comment by Integral** [comment]
@yoruyenturk thanks! you can check https://github.com/substance/texture/releases/tag/v2.0.1 now
