### ISSUE TITLE
we need better error messages when texture chokes on a document

### ISSUE THREAD

**Issue by axfelix** [substance/texture#122]
Right now, Texture's behaviour when encountering a document that's missing required JATS elements is usually to whitescreen -- errors are reported in browser console and easy to understand but nothing renders in the page itself. We should probably print some error message to the page...

**Comment by michael** [comment]
Hey! Will think about this. Throwing errors is helpful during development (debugger stops right where the error happens, giving some context). However, we should be able to turn printing the errors on screen instead in the production version.

**Comment by oliver----** [comment]
While this has changed, this is still very important.

**Comment by michael** [comment]
We have proper messaging now.
