### ISSUE TITLE
Allow deletion of references

### ISSUE THREAD

**Issue by sbirAECA** [substance/texture#1220]
In the new version 2.0.1 it is not enabled the remove item button when I select a reference

**Version: 1.0**

![referenceslist_10](https://user-images.githubusercontent.com/37865559/54016377-f7c5cc80-4182-11e9-95a8-011c255a924a.jpg)

**Version 2.0.1**

![referenceslist_201](https://user-images.githubusercontent.com/37865559/54016305-b6352180-4182-11e9-8a1f-882fe5df1531.jpg)

Thank you

**Comment by Integral** [comment]
@sbirAECA thanks for spotting this regression, this is important one!

**Comment by Integral** [comment]
Looks like remove collection command is always disabled.

**Comment by sbirAECA** [comment]
Not always it works for example when author collections

**Comment by Integral** [comment]
I will investigate. Once again thank you!

**Comment by Integral** [comment]
You are right. Looks like it's just a missing thing. I will add it.

**Comment by Integral** [comment]
This is now fixed in master. We will fix some of other bugs and then do a patch release.
Thanks!
