### ISSUE TITLE
Table commands not enabled in Metadata view

### ISSUE THREAD

**Issue by oliver----** [substance/texture#1243]
**Describe the bug**

In contrast to the Manuscript view, in the Metadata view the context menu for manipulating tables is empty.

**Steps To Reproduce**
- Open Metadata view / Tables
- Select a cell
- Click right mouse button to open context menu

**Expected behavior**

should show a context menu allowing to add/remove rows and columns, for instance

**Screenshots**
![image](https://user-images.githubusercontent.com/284099/55589736-57d37280-5731-11e9-8cb0-67b5c5a0532b.png)

**Comment by Integral** [comment]
@oliver---- would you agree with me that footnotes and bibliographic references inside table must be editable in metadata view as well?

**Comment by Integral** [comment]
...as well as other types of content available for tables in manuscript mode!

**Comment by oliver----** [comment]
Absolutely!

Daniel Beilinson <notifications@github.com> schrieb am Fr., 5. Apr. 2019,
11:34:

**Comment by oliver----** [comment]
Fixed via #1246
