### ISSUE TITLE
Bug: Formatting with ext-link

### ISSUE THREAD

**Issue by FAtherden-eLife** [substance/texture#1251]
# Describe the bug
As reported by @gnott, `ext-link` is not allowed as a child of formatting elements. Formatting inside `ext-link` elements are not displayed in texture.

# Steps To Reproduce
The following markup is considered invalid by Texture and will result in content being un-openable:
```
... invasion and egress. In <italic><ext-link ext-link-type="uri" xlink:href="https://www.sciencedirect.com/topics/immunology-and-microbiology/plasmodium-falciparum">P. falciparum</ext-link></italic>, FRM1 is present at the ...
```

The following markup is considered valid by Texture and will result in content being openable:
```
... invasion and egress. In <ext-link ext-link-type="uri" xlink:href="https://www.sciencedirect.com/topics/immunology-and-microbiology/plasmodium-falciparum"><italic>P. falciparum</italic></ext-link>, FRM1 is present at the ...
```

However the formatting is not rendered in the interface:
![Screen Shot 2019-04-17 at 09 41 16](https://user-images.githubusercontent.com/43879983/56273616-f8903d80-60f4-11e9-9b67-07714500701c.png)

# Expected behavior
`ext-link` should be allowed as a child of formatting elements and formatting should render for links in Texture interface.

**Comment by oliver----** [comment]
@Integral I'll investigate first and then hand it over to you.

**Comment by oliver----** [comment]
@Integral This was indeed incorrectly overridden in TextureJATS. I have added described content to the kitchen-sink.
Could you add a test-case for this, i.e. italic inside ext-link and ext-link inside italic?

**Comment by Integral** [comment]
Yes, I will do it.

**Comment by oliver----** [comment]
Just add another test case to Annotations.test.js. With a tiny fixture for both cases, and then check that it can be loaded and is imported correctly.
