### ISSUE TITLE
<history> tag support

### ISSUE THREAD

**Issue by michael** [substance/texture#128]
@fabiobatalha can you give me an example of the usage of the history tag? Which date-types are you using at SciELO? I'm asking because I want to build a UI for editing the history and would use some predefined date-types which can just be filled out.

Here's what I currently put into our kitchen_sink.xml:

```xml
      <history>
        <date date-type="received" iso-8601-date="1998-01-05">
          <day>05</day>
          <month>01</month>
          <year>1998</year>
        </date>
        <date date-type="rev-request" iso-8601-date="1998-03-14">
          <day>14</day>
          <month>03</month>
          <year>1998</year>
        </date>
        <date date-type="rev-received" iso-8601-date="1998-05-24">
          <day>24</day>
          <month>05</month>
          <year>1998</year>
        </date>
        <date date-type="accepted" iso-8601-date="1998-06-06">
          <day>06</day>
          <month>06</month>
          <year>1998</year>
        </date>
      </history>
```

**Comment by oliver----** [comment]
@michael also have a look at the spec: https://jats.nlm.nih.gov/archiving/tag-library/1.1/attribute/date-type.html

**Comment by oliver----** [comment]
So I'd recommend to support the suggested date-types: accepted,corrected,pub,preprint,retracted,received,rev-recd,rev-request

**Comment by michael** [comment]
I'd allow selecting those pre-defined date-types using a dropdown. Maybe like this?

![image](https://cloud.githubusercontent.com/assets/2931/26556732/97a21a00-449c-11e7-8ce0-15f09702ec20.png)

We can then implement a HistoryComponent which implements the UI and logic.

**Comment by oliver----** [comment]
Sounds good

**Comment by fabiobatalha** [comment]
@michael @oliver---- 

Here at SciELO we are using these date types: received (ok), accepted (ok) and rev-recd

where rev-recd = reviewed status.

I will check if rev-recd is the same of rev-received.

The attribute iso-8601-date is not mandatory for us once we can produce any format from the day, month and year elements.

**Comment by michael** [comment]
Done.
