### ISSUE TITLE
APA citation and reference 

### ISSUE THREAD

**Issue by kwahyu** [substance/texture#1296]
Dear Texture team,
I am a journal editor who seeks a tool to create XML file for our publication. I don't have any background on programming. So far, we created XML file using this https://github.com/Vitaliy-1/DOCX2JATS. However, a bunch of work should be done to edit the produced XML. The tool only supports numbering based citation and reference (Vancouver), meanwhile, our journal applies APA format. We believe that many journals use APA. 

We found Texture and tried desktop apps on Mac. It is a wonderful app. Like a MsWord, it is simple to write or create scholarly content. When inserting reference and citation, the available format in Vancouver. We wonder two things;  **how to create APA-based citation and reference**, and **how to save the .dar file to xml**. We tried searching about that (Texture manual), nothing found. 

In this case, if the feature (APA citation and reference) is not supported yet, we wish it could be considered for further development of Texture.

**Comment by Melissa37** [comment]
HI @kwahyu

This is on the roadmap! We're writing out the user stories for this requirement now and they will be added to the Feature specification board in the next few weeks: https://github.com/substance/texture/projects/3.

Please do review the tickets to make sure they answer to your requirements too.

Thanks!

**Comment by kwahyu** [comment]
Thanks for the upcoming feature. Ok, noted.

**Comment by michael** [comment]
@Melissa37  can we close this, as it will be replaced by proper tickets with user stories anyways?

**Comment by Melissa37** [comment]
Yes, sounds good :-)
