### ISSUE TITLE
Should refs to figures be deleted, when figure is deleted?

### ISSUE THREAD

**Issue by michael** [substance/texture#141]
Currently if we delete a figure, we see an error  because the xref is pointing to a non-existent target.
Since figures can be deleted via a regular editor operation we need some kind of post-hook. Ideas?

**Comment by oliver----** [comment]
We have never had a good solution for this.
I agree, probably we want kind of a hook - but which should only be active when recording a transaction, so that it does not get re-triggered when replaying changes.

**Comment by oliver----** [comment]
Will do an iteration on this.

**Comment by oliver----** [comment]
In addition to the inconsistency problem I see an error related to life-cycle of IsolatedComponents.

**Comment by oliver----** [comment]
I thought about this, and come to the conclusion now, that it is not desirable to remove these attributes.
Imagine, cut'n'pasting a figure, should not remove the refs.

Rather than a post-change hook with automatic deletion, I would prefer a means to detect and show such problems within the document.

**Comment by michael** [comment]
Good point, so you mean we allow broken references in `rid` attribute, and mark those nodes as problematic? I wonder how the UI should look like when you click on such an xref which would bring up the select references prompt. Should there be a selected entry saying "fig-1 - does not exist" which need to be explicitly unchecked or is if fine to immediately 'repair' the xref when the prompt is opened?

**Comment by oliver----** [comment]
Good question.
I have the feeling that it is not right to implicitly change the model just by opening a dialog.
Maybe we tell the user that this `ref` is 'broken', and ask to repair. And only let continue editing the list
when in a valid state?

**Comment by michael** [comment]
Yeah that could work.

**Comment by oliver----** [comment]
We agreed that we do not use `doc.delete()` explicitly, but rely on some type of garbage collection, which needs to be implemented.
