### ISSUE TITLE
API for deletion

### ISSUE THREAD

**Issue by michael** [substance/texture#145]
I wonder what API we should use for element deletion. E.g. to remove an affiliation or an author. Since we have an id for everything we could do something like `doc.delete('aff-2')` or `affNode.delete()` and automagically remove that entry from aff-group.childNodes.

If we want to be more explicit and follow the DOM APi we would rather do:

```js
affGroup.removeChild(affNode)
```

Or we do it similar to jQuery but with an explicit delete call that takes a selector.

```js
doc.delete('aff[id=aff-1]')
```

Thoughts?

**Comment by oliver----** [comment]
I think in the local case it make sense to have `removeChild()`
The latter clashes with our existing `doc.delete(nodeId)`.
What about
```
doc.findAll('...').forEach((el) => { el.remove() })
```

**Comment by oliver----** [comment]
Thinking about it, this is a bit more involved. E.g., there is a difference between `delete` and `remove`:

Should `el.removeChild()` also delete the child? To be consistent, `appendChild()` would then need to create nodes (if not yet created)... 

Otherwise, we could separate deletion and removal. The nodes would still exist in the document -- which I think would be more consistent with the DOM -- but in our case we would need some garbage collection after some time.

@michael what is ur opinion?

**Comment by Integral** [comment]
I think that we shouldn't create/remove children. It's more convenient to
have the same methods which natural DOM have, let's not create a mess. I
would prefare other method which will remove element from children and
delete those nodes.

**Comment by Integral** [comment]
Just a reminder: after this we should look again at removing affiliations/contributors. Currently there are some problems when you try to add new one after deletion.

**Comment by michael** [comment]
Hm.. so in the native DOM API you can create elements in memory, which are garbage collected (exist until last reference is deleted). They become part of the DOM only after `appendChild`, they get removed from the DOM on `removeChild`. In our case `doc.create` makes them part of the doc already. However, it becomes only visible when linked to the root (article) node. 

- I think it's fine to have two separate operations `parent.removeChild(node)` and `doc.delete(nodeId)` —  e.g. that's handy when we want to move a node somewhere (`oldparent.deleteChild`, `newParent.appendChild`)
- in substance every element has an ID, so our API's could support `parentNode.deleteChild(nodeId)` instead or in addition to `parentNode.deleteChild(node)`
- Think I don't like `doc.findAll('...').forEach((el) => { el.remove() })` always found it kind of weird in jQuery to tell an element to delete itself.
- Should we allow deletion before removal? E.g. doing `doc.delete('aff-1')` would mean affGroup has an invalid reference... unless we auto-delete that child or throw an error if you attempt to delete a node that's accessible through the document's root node
- should we allow multiple root nodes? ;) E.g. we could have multiple article nodes in one document, and those could reuse the same elements by referencing them.

**Comment by oliver----** [comment]
- I think relying on garbage collection is ok. Depending on the underlying persistence implementation, this could happen pretty naturally, e.g. when using XML for long term persistence
- On a lower level, I still need to old create/delete API. But I understand, as Daniel said, that this is rather confusing, on the higher level. In a pure XML world, it would be sufficient to have `dom.createElement()`, `el.appendChild()`, and `el.removeChild()`. I need to think, if it was possible to hide the old API.
- Multiple parentNodes are problematic, as some of the DOM API such as `cssSelect` makes use of `parentNode`.

**Comment by oliver----** [comment]
In this regard, we also need to rethink the DOMChange reflection model. As insertion and removal are now the more relevant operations, as opposed to create and delete.

**Comment by oliver----** [comment]
Added `removeChild()` and making use of it in: c18fdead5f57aa8763574f91c3b19aa5b8088ab4
