### ISSUE TITLE
Surface focusing

### ISSUE THREAD

**Issue by Integral** [substance/texture#146]
Looks like surface focusing isn't working.
When I call `focus` method nothing happens: `editorSession.getFocusedSurface` or `surfaceManager.getFocusedSurface` returns `undefined`.

**Comment by oliver----** [comment]
Yeah, that's confusing. It just does what happens when you focus a contentEditable.
I agree, that it would be more useful if it would behave in the same way as input fields do, i.e. setting the selection at the first position

**Comment by oliver----** [comment]
For #130, you will need to set the selection manually.

**Comment by oliver----** [comment]
This has been fixed.
