### ISSUE TITLE
Accessing Metadata Sections

### ISSUE THREAD

**Issue by michael** [substance/texture#149]
The accordion-style navigation for metadata does not work well when there is a lot of content. So I thought of improving the way we access any information in the context panel.

Goals:
- Memorizable way to access info
- Reduce jumpyness
- Ability to search for a setting (for which you don't know in which section it is hiding)
- Structure as flat as possible (we put the TOC on the same level as the "Affiliations Dialog")

Here's a mockup:

![image](https://user-images.githubusercontent.com/2931/27284196-f949c814-54f7-11e7-8274-132dfd80aa66.png)

We could bring up the context switcher on a keyboard shortcut as well (e.g. cmd+T) then typing "Publication date" which selects the Article Record section and pressing ENTER just takes you right there.

**Comment by oliver----** [comment]
Maybe Tabs, or a combination of your proposal and Tabs?

Am 19.06.2017 3:06 nachm. schrieb "Michael Aufreiter" <
notifications@github.com>:

**Comment by Integral** [comment]
@oliver---- just in case if you didn't understand as me - metadata section header acts here as dropdown, and you will see this navigator as dropdown
