### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by michael** [substance/texture#152]
Here's the UI for title and abstract translations.

![image](https://user-images.githubusercontent.com/2931/27288350-c7a684d2-5506-11e7-807e-fd6bed4fd606.png)

**Comment by Integral** [comment]
How it will look like from schema point of view?

**Comment by michael** [comment]
I created a setup for you (translations branch)

Note, that I changed the JATS model a bit and make it more explicit.
https://github.com/substance/texture/commit/d7e1711560b3532885b526b0e1ddb54fbd08d9df


Title translations go into `trans-title-group`: 

https://github.com/substance/texture/blob/translations/data/kitchen-sink.xml#L21

Abstract translations go into `trans-abstract-group`:

https://github.com/substance/texture/blob/translations/data/kitchen-sink.xml#L86
