### ISSUE TITLE
The given range isn't in document

### ISSUE THREAD

**Issue by Integral** [substance/texture#169]
Steps to reproduce:
1) Open contrib panel
2) Put cursor into first contrib's name 
3) Remove first contrib

**Comment by michael** [comment]
Fixed

**Comment by michael** [comment]
whoops wrong issue

**Comment by oliver----** [comment]
This happens if we try to recover the selection on an just deleted surface.

**Comment by oliver----** [comment]
Two issues with different priorities are involved here:
1. Surface disposal is broken (critical)
2. Selection is not invalidated if the containing context has been deleted

**Comment by oliver----** [comment]
Fixed the first issue via https://github.com/substance/substance/pull/1071/commits/f51ad882585b12d6e38c4da5f653ced3dc8df22a
