### ISSUE TITLE
Wrong label generation

### ISSUE THREAD

**Issue by michael** [substance/texture#172]
When I insert a new xref before the first occurence, then select a target that hasn't been referenced before, it should get the label [1] but doesn't.

![wrong-lables](https://user-images.githubusercontent.com/2931/27482305-3613fc7a-5821-11e7-8894-56ccd31f32b0.gif)

**Comment by oliver----** [comment]
Fixed via https://github.com/substance/substance/commit/d4e5a64c0204166276121cd83ea53ddde11a87de
