### ISSUE TITLE
How to represent contrib and aff in SciELO XML and other specifications

### ISSUE THREAD

**Issue by robertatakenaka** [substance/texture#173]
In order to support the producers of SciELO XML files, we have written this guidelines:
http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.6-branch/ (Portuguese).

In this page, there are published English and Spanish version.
https://github.com/scieloorg/scielo_publishing_schema/raw/master/versions/EN-scielo-publishing-schema-1.5.pdf (English)

For instance, we have adopted contrib and aff related by xref.
http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/latest/tagset/elemento-contrib.html
http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/latest/tagset/elemento-aff.html

Attached some XML files

[Ahead of Print.zip](https://github.com/substance/texture/files/1098279/Ahead.of.Print.zip)
[Appendix.zip](https://github.com/substance/texture/files/1098278/Appendix.zip)
[Continuous publication.zip](https://github.com/substance/texture/files/1098282/Continuous.publication.zip)
[Editorial.zip](https://github.com/substance/texture/files/1098280/Editorial.zip)
[Erratum.zip](https://github.com/substance/texture/files/1098283/Erratum.zip)
[Original article.zip](https://github.com/substance/texture/files/1098281/Original.article.zip)
[Reply letter.zip](https://github.com/substance/texture/files/1098284/Reply.letter.zip)
[Review 1.zip](https://github.com/substance/texture/files/1098286/Review.1.zip)
[Review 2.zip](https://github.com/substance/texture/files/1098285/Review.2.zip)
[Translation.zip](https://github.com/substance/texture/files/1098287/Translation.zip)

**Comment by oliver----** [comment]
Thank you very much. This is very helpful.

**Comment by michael** [comment]
@robertatakenaka could you check the latest spec if we missed any of your use-cases?

https://github.com/substance/dar/blob/master/specs/JATS4M.md#authors
https://github.com/substance/dar/blob/master/specs/JATS4M.md#affiliations

**Comment by oliver----** [comment]
Closing this, as we have completed a first iteration.
