### ISSUE TITLE
Improve header indentation

### ISSUE THREAD

**Issue by michael** [substance/texture#177]
When already at highest level the command does not get executed. Then default tab behavior is used, which feels weird in that scenario. To solve this we can always handle the tab key when cursor is at heading. But when level 3 or level 1 is reached we just do nothing (no-op) in the execute function.

**Comment by Integral** [comment]
I'll take that

**Comment by Integral** [comment]
Done.

**Comment by michael** [comment]
is this in restart branch?

**Comment by oliver----** [comment]
is working for me
