### ISSUE TITLE
Don't show disabled switch-text-type options

### ISSUE THREAD

**Issue by michael** [substance/texture#178]
E.g. `H1` is enabled in footnote, where no other text nodes than `<p>` are allowed.

**Comment by Integral** [comment]
Same for disp-quote

**Comment by oliver----** [comment]
Ah. sorry. It is already schema-sensitive. Then I think it is ok as it is.
Or in general we could think of not showing the disabled ones here.

**Comment by oliver----** [comment]
SchemaDrivenCommandManager makes this already schema-sensitive.
But the drop-down, should not show disabled options.

**Comment by oliver----** [comment]
Fixed this in #183
