### ISSUE TITLE
Editing Element vs Mixed Content

### ISSUE THREAD

**Issue by oliver----** [substance/texture#184]
There is a bunch of things in JATS which are expressed using mixed content.
This creates a bit of confusion for Texture, because it is not clear how to edit this.
A form is in our opinion still the best UI for editing properties, but at the same time it is difficult for us to derive the textual form then, without relying on a rendering service.

I was wondering, if we could come up with a solution for that -- an idea which we discussed some years ago already: The idea is to primarily present a form, plus a rendered textual representation of the whole record. The user has some means to change the textual representation in a limited way, like a template string.

**Comment by oliver----** [comment]
Example:
```
    <conf-loc><city>Denver</city>, <state>Colorado</state>, <country>United States</country></conf-loc>

    <conf-loc>
      <city>Denver</city>
      <state>Colorado</state>
      <country>United States</country>
    </conf-loc>
```

Having this UI we would have multiple options:
- use mixed content as single source
- apply a general pattern separating structured from textual content
- introduce a dedicated element for textual content

No matter what we do, we must be able to keep presentation in sync with the structured representation, which the user would edit in first place.

**Comment by oliver----** [comment]
@michael thoughts?

With the JATS -> TextureJATS transformation, we are facing the situation, that almost all of these cases are primarily mixed in JATS -- `<element-citation>` the only exception. Instead of introducing a lot of new elements into TextureJATS we could then stay closer to the original schema.

**Comment by michael** [comment]
We agreed to keep one structured version and derive a mixed/or string version from it, which is a weak copy and gives users the ability to 'just render' it. Additionally we discussed keeping an 'original' record (e.g. when a reference has been imported from word).

**Comment by michael** [comment]
We will only edit element-citations now and derive a display version from it. Closing.
