### ISSUE TITLE
Supporting structured references

### ISSUE THREAD

**Issue by michael** [substance/texture#185]
We want to support structured references, the earlier data exists in a structured form (`<element-citation>` the better.

Workflow:

- User clicks on a reference and gets provided a form to enter the citation information
- Information is stored as an element citation
- RefComponent renders a preview (so needs to implement a renderer for element citations)

![image](https://user-images.githubusercontent.com/2931/27688124-bc6c8a5a-5cd9-11e7-94f9-ba73e98807e8.png)

Implementation:

- introduce a new app context (editReference)
- Create a component for editing references (note we need to support different reference types, e.g.  journal vs book
- for now let's only implement journal article (and display a warning for other types)

**Comment by michael** [comment]
Implement renderering of element citations (see ElementCitationComponent). This does not need to be perfect yet, but we try to follow eLife's rendering style.

![image](https://user-images.githubusercontent.com/2931/27699455-a26885d4-5cfa-11e7-9c0e-4ba4a62f48d4.png)

**Comment by oliver----** [comment]
@michael @Integral Please make sure that you consider cardinality/optional correctly.
https://jats.nlm.nih.gov/publishing/tag-library/1.1/element/element-citation.html
E.g., in <element-citation> everything is optional.

**Comment by Integral** [comment]
Hey,
I don't we can do everything optional…
More over, we are relying on some format… For instance that article citation would have article title and the source.

**Comment by oliver----** [comment]
Sorry, but we need to be robust.

**Comment by oliver----** [comment]
Alternatively, we could also do some 'enhancing' during import.

**Comment by oliver----** [comment]
This we should accompany with a stricter schema in TextureJATS.rng...
We could change the specification from `(...)+` to something with non-optionals and optionals. But then we must make sure to have a transformer (see new implementation)

**Comment by Integral** [comment]
Yes, we need strict schema then.
Cause now element-citation could look very differently.
How could we really on that then we have “custom” form and what we should do when a user add new reference through UI?

**Comment by oliver----** [comment]
The idea would be to formulate 'recommendations' which we propose with JATS4R. So no 'custom' anymore, only one of the predefined ones.
Then we can rely on everything, and make TextureJATS strict.

**Comment by oliver----** [comment]
Still some things such as pages are optional, but not title etc.

**Comment by Integral** [comment]
I think that there is a misunderstanding here, cause I don’t have too much inputs about what are you doing with JATS. Now I understand that you have your own branch, right?
I’m totally agree that we need more strict schema in element-citation. What was your original question? Do you want us to follow some guidelines? Let’s formulate what could be there, what should be there, what should be optional.
Or let’s create a form builder which will generate form based on schema, as I understand you don’t want to do it in this iteration…
Currently we have a form which expects certain number of elements inside element-citation and we also have an empty record which got appended to xml when you add a new reference through texture...

**Comment by oliver----** [comment]
I merged my stuff.
Our new route is to come up with a stricter JATS schema, which we either propose as JATS4R, i.e. everything what should be a good common agreement, and TextureJATS, where we add our customizations, which are necessary to build an editor.
Example for the first, would indeed by `<element-citation>`, event further, how to use `<ref>` so that it is crystal clear, and there is only one way.
Example for the latter is `<abstract-content>` which we need to separate meta from content, but which we would not be able to propose to be included into JATS.

So for now, we would define what is not-optional, in `<element-citation>` or maybe even, for the different types, such as book, and make the Component robust, so it doesn't crash (which it does right now).

**Comment by Integral** [comment]
100% agree, let’s describe it. Who should do this?

**Comment by oliver----** [comment]
Maybe we take a look at the bibtex spec?

**Comment by michael** [comment]
Basic editor is ready, I will add a strict schema for TextureJATS.

**Comment by michael** [comment]
Done. We don't support the full thing but we are strict for journal and book citations. More in the next releases.
