### ISSUE TITLE
Modelling structured refs in TextureJATS

### ISSUE THREAD

**Issue by michael** [substance/texture#190]
We need to fully model structured refs in TextureJATS, and be more strict as in the original spec.

One thing I proposed is using separate elements with strict schema for each publication type

```xml
<ref id="r1">
  <journal-citation>
    ...
  </journal-citation>
</ref>
```

- the good thing would be that we have a strict schema, we could even
  derive forms automatically
- but it's hard to determine wether book-citation or journal-citation or other
  is in a ref - we would need to find() all elements to find out
- it may be harder to implement renderers for each subtype

Alternatively we could also stick to the original element-citation model:

- i would be okay with that as long we can enforce that certain elements are present
  when publication-type==='journal' and others are not.
- how could we model that? think that can not be enforced with RelaxNG schemas,
  so we would have to keep a separate lookup table somewhere
- i'd only change the schema for elements like year to be plaintext etc.
- this would be closest to jats, so not much work needed for transformers

## Problems with optional elements

We need a strategy how to deal with optional elements, and how to represent
them in the XML. Consider the following situation. 

- you have an element-citation where no issue element is present
- still you want to render a form field for the issue

Solution 1: we always require all elements to be present, so there are no longer optional
            elements, instead they can be empty (not filled out)

Solution 2: we add/delete elements on the fly. e.g. after filling out the issue input field
            when no issue element exists, we create it, otherwise update it

## How to switch from one publication type to another

- this is tricky, e.g. when you switch from journal to book we need to remove article-title and instead
  add chapter-title. i think it is hard to preserve some data (e.g. the authors list?)
- this would lead to a complex operation which needs to be implemented for each transition
  it may be better to just wipe everything on the switch?
- this would be easy if we had separate elements, i would then remove the book-citation element and create a fresh empty journal-citation

Thoughts?

**Comment by oliver----** [comment]
We decided to move towards attribute-sensitive schema refinements, and stick with `<element-citation>`. While we introduce strict rules in JATS4R according to the type attribute, we will allow all combinations in TextureJATS so that it is possible to switch the type and retain some variables.
Only when we convert back to JATS, these extra fields will be discarded, to adhere to the restrictions introduced in JATS4R.
