### ISSUE TITLE
Broken image links  in figures cause flickering/jumping

### ISSUE THREAD

**Issue by oliver----** [substance/texture#193]
I checked by not displaying the figure content, there is no flicker.
Maybe we use some fall-back, so that always some content is rendered.

**Comment by oliver----** [comment]
The solution is to add `onload` and `onerror` hooks, and setting a state if error has happened, or the image has zero width and height.
When in error state, render some placeholder image.
The error state should be removed whenever the image url has been updated.

**Comment by Integral** [comment]
@oliver---- is it still happening? If so, could you please tell me how to reproduce this flickering?

**Comment by michael** [comment]
You could open a Dar with images, then delete the image on the FS to get a broken image url. Then you should see the flickering, when activating the Isolated Node.

**Comment by Integral** [comment]
@michael I'm trying to do that with kitchen-sink example and can't see any flickering... Can you describe steps more detailed or record a gif?

**Comment by oliver----** [comment]
It is a bit hard to see in the gif. If you click inside the caption and then into the paragraph above you see flickering. If you click in the paragraph below, you see a scrolling glitch (which seems to have the same source of problem).

**Comment by michael** [comment]
Fixed.
