### ISSUE TITLE
Installing Issues.

### ISSUE THREAD

**Issue by fabiobatalha** [substance/texture#197]
I'm trying to install from the source. But I'm having some issues. Any thoughts?

Fabios-MacBook-Pro:texture fabiobatalha$ npm install
npm notice created a lockfile as package-lock.json. You should commit this file.
up to date in 0.486s

Fabios-MacBook-Pro:texture fabiobatalha$ git status
On branch develop
Your branch is up-to-date with 'fabio/develop'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	package-lock.json

nothing added to commit but untracked files present (use "git add" to track)

Fabios-MacBook-Pro:texture fabiobatalha$ npm run start

> substance-texture@1.0.0-alpha.2 start /Users/fabiobatalha/Trabalho/texture
> node make dev -s -w

Remove: tmp/
Creating virtual file system: tmp/vfs.js
..finished in 25 ms.
Compiling schema 'JATS-publishing'...

Error during execution of Command  custom
Error: Cannot find module 'substance'
Stacktrace:
Error: Cannot find module 'substance'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at CustomAction.execute [as _execute] (/Users/fabiobatalha/Trabalho/texture/make.js:111:63)
    at CustomAction.execute (/Users/fabiobatalha/Trabalho/texture/node_modules/substance-bundler/src/commands/CustomCommand.js:152:33)
    at CustomCommand._executeWithCollection (/Users/fabiobatalha/Trabalho/texture/node_modules/substance-bundler/src/commands/CustomCommand.js:105:27)
    at CustomCommand.execute (/Users/fabiobatalha/Trabalho/texture/node_modules/substance-bundler/src/commands/CustomCommand.js:36:19)
    at Bundler._next (/Users/fabiobatalha/Trabalho/texture/node_modules/substance-bundler/src/Bundler.js:289:30)
    at Bundler._step (/Users/fabiobatalha/Trabalho/texture/node_modules/substance-bundler/src/Bundler.js:330:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! substance-texture@1.0.0-alpha.2 start: `node make dev -s -w`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the substance-texture@1.0.0-alpha.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/fabiobatalha/.npm/_logs/2017-07-11T13_22_46_400Z-debug.log

Fabios-MacBook-Pro:texture fabiobatalha$ npm ls
substance-texture@1.0.0-alpha.2 /Users/fabiobatalha/Trabalho/texture
├── font-awesome@4.5.0
├── lodash@4.17.4
├─┬ substance@1.0.0-beta.7-preview.16 (github:substance/substance#ded49d364dcc80c8977d5dbaf2172a695d7b66ba)
│ ├── boolbase@1.0.0
│ ├── css-what@2.1.0
│ ├── domelementtype@1.3.0
│ ├── entities@1.1.1
│ ├── lodash-es@4.13.1
│ └─┬ nth-check@1.0.1
│   └── boolbase@1.0.0 deduped
├─┬ substance-bundler@0.18.4
│ ├─┬ fsevents@1.1.2
│ │ ├── nan@2.6.2
│ │ └─┬ node-pre-gyp@0.6.36
│ │   ├─┬ mkdirp@0.5.1
│ │   │ └── minimist@0.0.8
│ │   ├─┬ nopt@4.0.1
│ │   │ ├── abbrev@1.1.0
│ │   │ └─┬ osenv@0.1.4
│ │   │   ├── os-homedir@1.0.2
│ │   │   └── os-tmpdir@1.0.2
│ │   ├─┬ npmlog@4.1.0
│ │   │ ├─┬ are-we-there-yet@1.1.4
│ │   │ │ ├── delegates@1.0.0
│ │   │ │ └── readable-stream@2.2.9 deduped
│ │   │ ├── console-control-strings@1.1.0
│ │   │ ├─┬ gauge@2.7.4
│ │   │ │ ├── aproba@1.1.1
│ │   │ │ ├── console-control-strings@1.1.0 deduped
│ │   │ │ ├── has-unicode@2.0.1
│ │   │ │ ├── object-assign@4.1.1
│ │   │ │ ├── signal-exit@3.0.2
│ │   │ │ ├─┬ string-width@1.0.2
│ │   │ │ │ ├── code-point-at@1.1.0
│ │   │ │ │ ├─┬ is-fullwidth-code-point@1.0.0
│ │   │ │ │ │ └── number-is-nan@1.0.1
│ │   │ │ │ └── strip-ansi@3.0.1 deduped
│ │   │ │ ├─┬ strip-ansi@3.0.1
│ │   │ │ │ └── ansi-regex@2.1.1
│ │   │ │ └─┬ wide-align@1.1.2
│ │   │ │   └── string-width@1.0.2 deduped
│ │   │ └── set-blocking@2.0.0
│ │   ├─┬ rc@1.2.1
│ │   │ ├── deep-extend@0.4.2
│ │   │ ├── ini@1.3.4
│ │   │ ├── minimist@1.2.0
│ │   │ └── strip-json-comments@2.0.1
│ │   ├─┬ request@2.81.0
│ │   │ ├── aws-sign2@0.6.0
│ │   │ ├── aws4@1.6.0
│ │   │ ├── caseless@0.12.0
│ │   │ ├─┬ combined-stream@1.0.5
│ │   │ │ └── delayed-stream@1.0.0
│ │   │ ├── extend@3.0.1
│ │   │ ├── forever-agent@0.6.1
│ │   │ ├─┬ form-data@2.1.4
│ │   │ │ ├── asynckit@0.4.0
│ │   │ │ ├── combined-stream@1.0.5 deduped
│ │   │ │ └── mime-types@2.1.15 deduped
│ │   │ ├─┬ har-validator@4.2.1
│ │   │ │ ├─┬ ajv@4.11.8
│ │   │ │ │ ├── co@4.6.0
│ │   │ │ │ └─┬ json-stable-stringify@1.0.1
│ │   │ │ │   └── jsonify@0.0.0
│ │   │ │ └── har-schema@1.0.5
│ │   │ ├─┬ hawk@3.1.3
│ │   │ │ ├─┬ boom@2.10.1
│ │   │ │ │ └── hoek@2.16.3 deduped
│ │   │ │ ├─┬ cryptiles@2.0.5
│ │   │ │ │ └── boom@2.10.1 deduped
│ │   │ │ ├── hoek@2.16.3
│ │   │ │ └─┬ sntp@1.0.9
│ │   │ │   └── hoek@2.16.3 deduped
│ │   │ ├─┬ http-signature@1.1.1
│ │   │ │ ├── assert-plus@0.2.0
│ │   │ │ ├─┬ jsprim@1.4.0
│ │   │ │ │ ├── assert-plus@1.0.0
│ │   │ │ │ ├── extsprintf@1.0.2
│ │   │ │ │ ├── json-schema@0.2.3
│ │   │ │ │ └─┬ verror@1.3.6
│ │   │ │ │   └── extsprintf@1.0.2 deduped
│ │   │ │ └─┬ sshpk@1.13.0
│ │   │ │   ├── asn1@0.2.3
│ │   │ │   ├── assert-plus@1.0.0
│ │   │ │   ├─┬ bcrypt-pbkdf@1.0.1
│ │   │ │   │ └── tweetnacl@0.14.5 deduped
│ │   │ │   ├─┬ dashdash@1.14.1
│ │   │ │   │ └── assert-plus@1.0.0
│ │   │ │   ├─┬ ecc-jsbn@0.1.1
│ │   │ │   │ └── jsbn@0.1.1 deduped
│ │   │ │   ├─┬ getpass@0.1.7
│ │   │ │   │ └── assert-plus@1.0.0
│ │   │ │   ├─┬ jodid25519@1.0.2
│ │   │ │   │ └── jsbn@0.1.1 deduped
│ │   │ │   ├── jsbn@0.1.1
│ │   │ │   └── tweetnacl@0.14.5
│ │   │ ├── is-typedarray@1.0.0
│ │   │ ├── isstream@0.1.2
│ │   │ ├── json-stringify-safe@5.0.1
│ │   │ ├─┬ mime-types@2.1.15
│ │   │ │ └── mime-db@1.27.0
│ │   │ ├── oauth-sign@0.8.2
│ │   │ ├── performance-now@0.2.0
│ │   │ ├── qs@6.4.0
│ │   │ ├── safe-buffer@5.0.1
│ │   │ ├── stringstream@0.0.5
│ │   │ ├─┬ tough-cookie@2.3.2
│ │   │ │ └── punycode@1.4.1
│ │   │ ├─┬ tunnel-agent@0.6.0
│ │   │ │ └── safe-buffer@5.0.1 deduped
│ │   │ └── uuid@3.0.1
│ │   ├─┬ rimraf@2.6.1
│ │   │ └─┬ glob@7.1.2
│ │   │   ├── fs.realpath@1.0.0
│ │   │   ├─┬ inflight@1.0.6
│ │   │   │ ├── once@1.4.0 deduped
│ │   │   │ └── wrappy@1.0.2 deduped
│ │   │   ├── inherits@2.0.3 deduped
│ │   │   ├─┬ minimatch@3.0.4
│ │   │   │ └─┬ brace-expansion@1.1.7
│ │   │   │   ├── balanced-match@0.4.2
│ │   │   │   └── concat-map@0.0.1
│ │   │   ├── once@1.4.0 deduped
│ │   │   └── path-is-absolute@1.0.1
│ │   ├── semver@5.3.0
│ │   ├─┬ tar@2.2.1
│ │   │ ├─┬ block-stream@0.0.9
│ │   │ │ └── inherits@2.0.3 deduped
│ │   │ ├─┬ fstream@1.0.11
│ │   │ │ ├── graceful-fs@4.1.11
│ │   │ │ ├── inherits@2.0.3 deduped
│ │   │ │ ├── mkdirp@0.5.1 deduped
│ │   │ │ └── rimraf@2.6.1 deduped
│ │   │ └── inherits@2.0.3
│ │   └─┬ tar-pack@3.4.0
│ │     ├─┬ debug@2.6.8
│ │     │ └── ms@2.0.0
│ │     ├── fstream@1.0.11 deduped
│ │     ├─┬ fstream-ignore@1.0.5
│ │     │ ├── fstream@1.0.11 deduped
│ │     │ ├── inherits@2.0.3 deduped
│ │     │ └── minimatch@3.0.4 deduped
│ │     ├─┬ once@1.4.0
│ │     │ └── wrappy@1.0.2
│ │     ├─┬ readable-stream@2.2.9
│ │     │ ├── buffer-shims@1.0.0
│ │     │ ├── core-util-is@1.0.2
│ │     │ ├── inherits@2.0.3 deduped
│ │     │ ├── isarray@1.0.0
│ │     │ ├── process-nextick-args@1.0.7
│ │     │ ├─┬ string_decoder@1.0.1
│ │     │ │ └── safe-buffer@5.0.1 deduped
│ │     │ └── util-deprecate@1.0.2
│ │     ├── rimraf@2.6.1 deduped
│ │     ├── tar@2.2.1 deduped
│ │     └── uid-number@0.0.6
│ └─┬ source-map-support@0.4.15
│   └── source-map@0.5.6
└─┬ substance-test@0.5.1
  └─┬ source-map-support@0.4.3
    └── source-map@0.5.6 deduped

Fabios-MacBook-Pro:texture fabiobatalha$ npm --version
5.0.3

Fabios-MacBook-Pro:texture fabiobatalha$ node --version
v8.1.3

**Comment by oliver----** [comment]
You are right, we haven't bumped dependencies correctly.
Will pink you when this is ready.

**Comment by fabiobatalha** [comment]
ack
@oliver----

**Comment by fabiobatalha** [comment]
Ops. Closed by mistake.

Reopening.

**Comment by michael** [comment]
@fabiobatalha install should be working now. Please note, we still have some critical bugs, which will we hope will be fixed until end of week and then tag a release.

Will also work on an updated README.md, currently out of date instructions there.

**Comment by fabiobatalha** [comment]
Thanks @michael.

That is ok if we have some bugs, I'm just trying to become more familiar with the source.
I will also install the Texture in a sandbox server to allow the production team to try the Texture interface when it is done.

Tested and working.
