### ISSUE TITLE
Go back to Green JATS?

### ISSUE THREAD

**Issue by michael** [substance/texture#206]
There's a bunch of things that wouldn't hurt us, which don't pass in blue JATS. E.g. `<object-id>` in abstract as used in eLife articles.

**Comment by oliver----** [comment]
I agree. Green is actually not that bad. And it comes with `<x>` which is the only way, e.g. to have a consistent way to allow a textual form of some structural nodes, such as `<aff>` and `<contrib>`

**Comment by blahah** [comment]
Are the terms *blue* and *green* JATS something defined in the spec? Is it something people like me who are using JATS as an output format should learn about? Or just trust it to texture? :)

**Comment by michael** [comment]
There's different tag libraries for JATS. Authoring (Brown), Publishing (Blue) and Archiving (Green). 

See: 
https://jats.nlm.nih.gov/articleauthoring/
https://jats.nlm.nih.gov/publishing/
https://jats.nlm.nih.gov/archiving/

Archiving is the most detailed one and a superset of publishing, which is  superset of authoring. We thought that going with the smaller / more restrictive blue JATS would make things easier for us to implement and be sufficient for our use-cases but that turns out to be wrong, so I think we base our restrictions on Arching as originally planned.

**Comment by oliver----** [comment]
Done
