### ISSUE TITLE
Full support for editing Contributors and Affiliations

### ISSUE THREAD

**Issue by oliver----** [substance/texture#217]
These can only be considered as a evaluation spyke. They are not capable of dealing with realistic data. We should address #196 and implement this properly.

- [ ] Add `<prefix>` to name element

**Comment by michael** [comment]
Agreed. Before we start we need to have a confirmed set of requirements and a final tagging syntax, which we will enforce via JATS4R.rng schema.

Proposal for a general direction:

```xml
<contrib-group>
  <contrib contrib-type="author" aff-ids="aff1 aff2">
    <x specific-use="display">John Doe</x>
    <name>
      <surname>Doe</surname>
      <given-names>John</given-names>
    </name>
  </contrib>
  <contrib contrib-type="author" aff-ids="aff2">
    <x specific-use="display">Jane Doe</x>
    <name>
      <surname>Doe</surname>
      <given-names>Jane</given-names>
    </name>
  </contrib>
</contrib-group>
<aff id="aff1">
  <x specific-use="display">Foo University, London, UK</x>
  <institution>Foo University</institution>
  <city>London</city>
  <country>UK</country>
</aff>
<aff id="aff2">
  <x specific-use="display">Bar Ltd, London, UK</x>
  <institution>Bar Ltd</institution>
  <city>London</city>
  <country>UK</country>
</aff>
```

Please provide a refined proposal until we are all happy and all needed information is covered. ping @fabiobatalha, @axfelix, @cormier, @oliver----, @Melissa37, @NateWr

**Comment by NateWr** [comment]
I imagine at the very least we'll need `<prefix>` for names, but I can't speak to any of the other elements. The `name-style` attribute has some helpful guidance:

https://jats.nlm.nih.gov/publishing/tag-library/1.1/attribute/name-style.html

**Comment by michael** [comment]
Agree on `<prefix>` 👍  

Not sure about including the `name-style` attribute in the user interface (it's someting that the author/editor should not have to think about). I mean we definitely need a rendering strategy so we can compute the display version of the name (`<x specific-use="display">John Doe</x>`), but that could be more a Texture config parameter. E.g. in OJS you could specify that somewhere in an admin panel.

**Comment by NateWr** [comment]
That makes sense if the name strategy is journal-specific. But would it ever be name-specific? :man_shrugging:

**Comment by michael** [comment]
Good question!

**Comment by fabiobatalha** [comment]
At SciELO we are receiving XML's with the **prefix** element, it is not mandatory. (It is working the way JATs specified it to works)

For **contrib-group** and **aff** there are some slightly differences between the previous example and the way SciELO PS specifies the use of these elements. This example is also compliance with JATS, but I'm not sure if it is under compliance with JATS4R recommendations.

```xml
<contrib-group>
    <contrib contrib-type="author">
        <name>
            <surname>Dores</surname>
            <given-names>Helder</given-names>
        </name>
        <xref ref-type="aff" rid="aff1">1</xref>
        <xref ref-type="aff" rid="aff2">2</xref>
        <xref ref-type="aff" rid="aff3">3</xref>
        <xref ref-type="aff" rid="aff4">4</xref>
        <xref ref-type="corresp" rid="c1"/>
    </contrib>
    <contrib contrib-type="author">
        <name>
            <surname>Mendes</surname>
            <given-names>Lígia</given-names>
        </name>
        <xref ref-type="aff" rid="aff1">1</xref>
        <xref ref-type="aff" rid="aff2">2</xref>
    </contrib>
    <contrib contrib-type="author">
        <name>
            <surname>Ferreira</surname>
            <given-names>António</given-names>
        </name>
        <xref ref-type="aff" rid="aff2">2</xref>
    </contrib>
    <contrib contrib-type="author">
        <name>
            <surname>Santos</surname>
            <given-names>Jose Ferreira</given-names>
        </name>
        <xref ref-type="aff" rid="aff1">1</xref>
    </contrib>
</contrib-group>
<aff id="aff1">
    <label>1</label>
    <institution content-type="orgname">Hospital da Luz Setúbal</institution>
    <addr-line>
        <named-content content-type="city">Setúbal</named-content>
    </addr-line>
    <country country="PT">Portugal</country>
    <institution content-type="original">Hospital da Luz Setúbal, Setúbal -
        Portugal</institution>
</aff>
<aff id="aff2">
    <label>2</label>
    <institution content-type="orgname">Hospital da Luz Lisboa</institution>
    <addr-line>
        <named-content content-type="city">Lisboa</named-content>
    </addr-line>
    <country country="PT">Portugal</country>
    <institution content-type="original">Hospital da Luz Lisboa, Lisboa -
        Portugal</institution>
</aff>
<aff id="aff3">
    <label>3</label>
    <institution content-type="orgname">Hospital das Forças Armadas</institution>
    <addr-line>
        <named-content content-type="city">Lisboa</named-content>
    </addr-line>
    <country country="PT">Portugal</country>
    <institution content-type="original">Hospital das Forças Armadas, Lisboa -
        Portugal</institution>
</aff>
<aff id="aff4">
    <label>4</label>
    <institution content-type="orgname">NOVA Medical School</institution>
    <addr-line>
        <named-content content-type="city">Lisboa</named-content>
    </addr-line>
    <country country="PT">Portugal</country>
    <institution content-type="original">NOVA Medical School, Lisboa -
        Portugal</institution>
</aff>
```
I agree the display version of the authors name could be a computed value.

**Comment by michael** [comment]
Thank you @fabiobatalha. I think the tagging style of `<contrib> is fine. Actually, I put a wrong example (`aff-ids` attribute of course does not exist in JATS/JATS4R) so we use xref for linking contribs with affs.

Regarding `<aff>` elements I think there is work to do, as there are many different variations (see https://github.com/substance/texture/issues/196), and we should define a clear set of tags, that we can map to a form to be filled out. 

- `<label>`: that number is computed and personally i would rather drop it to avoid confusion (you would assume you can edit the affiliation label, when it actually just depends on the order of the aff entries). Also it is redundant information. Would you be ok with dropping the label?

- I would not use the `<institution>` with two different semantics (original vs. orgname)
- Can you provide all the "fields" (as in a form) that Scielo articles need to capture at a minimum? So far I see: organisation name, city, country.... what else do we need?

**Comment by michael** [comment]
I've come up with a proposal in #240. Let's discuss there!

**Comment by Melissa37** [comment]
I agree that JATS4R should come out with some leads on this, but some comments from eLife's end:

There are more attributes on contrib, which we use and are common:
corresp="yes"
equal-contrib="yes" 
deceased="yes"
id="author-00001" (internal number)

We don't allow prefix for authors but do allow suffix!

I agree with the principle of not adding labels to things if not necessary for semantics and display, but we are sometimes restricted by PMC - if it does not display well on PMC then we've had to revert, for instance:

```
xml
 <contrib contrib-type="author" aff-ids="aff1 aff2">
...
<xref ref-type="aff" rid="aff1"/>
``` 
Had to be changed to:

```
xml
...
<xref ref-type="aff" rid="aff1">1</xref>
```
otherwise our content did not work on the PMC site. It's worth factoring in the PMC guidelines.

Some other things to consider:
ORCID tagging:
```
xml
<contrib-id contrib-id-type="orcid"  authenticated="true">https://orcid.org/0000-0003-4921-6155</contrib-id>
```

Group author details - this is a real headache and we're spent a lot of time on this - members of a group authorship who have addresses, roles, contributions etc.

**Comment by michael** [comment]
This is done.
