### ISSUE TITLE
Introduce Guidelines for Component implementation

### ISSUE THREAD

**Issue by oliver----** [substance/texture#218]
Implementing a schema sensitive Editor is not as simple as just rendering some data.
The current UI implementation is not a good role-model, as it takes naive and optimistic decisions about the content, without being robust or on the other hand being stricter in schema.

In future I want to be involved in every PR adding a Component, until we have a Guideline for implementors to follow.

**Comment by oliver----** [comment]
The key policy here is, either the validator rejects input, or the editor does it right.
Not as it was in the past, and it is again, failing late -- which makes maintainability incredibly hard.

**Comment by Integral** [comment]
Ok, we did dump implementation and it was rather careful decision than
naive one. When we should make it more robust?

**Comment by oliver----** [comment]
I am not critizising you personally. Just want to make clear, that we don't have the right process.
Probably it needs more experience, to do wise decisions regarding schema.

When, is a good question. I need to discuss with @michael what we want and what we must do.

**Comment by Integral** [comment]
Absolutely.
That was what we thought - that we need more experiences before next iteration.
Let me know if come to something, with this guideline I would gladly prepare new PRs.
