### ISSUE TITLE
Implement <pages>

### ISSUE THREAD

**Issue by oliver----** [substance/texture#220]
- Introduce a new element in TexureJATS `<pub-loc>` being a super element for `<fpage>`, `<lpage>`, `<page-range>`, and `<elocation-id>`
- `<pub-loc>` has an attribute `type='print|electronic'`
- UI should 
  - provide a means to switch between the two types
  - show a form with either `fpage`, `lpage`, and `page-range`, or `elocation-id` depending on the type
- Converter should
  - wrap original elements into a `<pub-loc>` detecting the type during import
  - map back to the original JATS elements, dropping unnecessary fields, depending on the type

**Comment by blahah** [comment]
@oliver---- @michael can I just confirm my understanding that `texture` will provide both the TextureJATS model and a UI?

If my understanding is correct, is it possible to separate these out? My use-case is that the model will be used in CLI node tools for normalising and validating JATS documents, while the UI will be used in electron apps.

**Comment by oliver----** [comment]
@blahah The goal is to define JATS4R as being JATS without ambiguities. There is some effort necessary to transform all JATS dialects into JATS4R. How we want to maintain this is not yet clear, would be good to have this in Texture, too.
Texture itself takes JATS4R, transforming it into TextureJATS, which is actually not JATS anymore, but should be transformed 100% loss-free in both directions.
Texture comes with validators for JATS, JATS4R, particularly the latter being the precondition for being editable within Texture UI.

So I think this should be what you need, but there is some work to be done in the JATS -> JATS4R layer.

**Comment by blahah** [comment]
@oliver---- sorry, I commented here then moved my comment to a new issue to avoid overlapping concerns - but failed as our comments crossed on the wire!

OK, so am I correct in understanding that once the primary goal is achieved, that will be the time to raise issues of how the architecture can be useful in secondary use-cases?

**Comment by oliver----** [comment]
I think so. With Texture we do not want to promote TextureJATS as exchange model. Maybe in the far future, but it is not realistic to propose a schema that is incompatible with JATS. We called it TextureJATS, to reduce fear ;) and also because it is JATS + some minor extension.
Instead we want to propose JATS4R as the JATS interchange format, so that other people know how to adapt their JATS toolchains to be compatible with output from Texture.
We should probably write a technical blog soon, explaining the whole picture including some use-cases.

**Comment by blahah** [comment]
Thanks for explaining - I will await more details + release before asking more questions. If you have any questions RE my use-case, you know where to find me in the meantime :)

**Comment by oliver----** [comment]
Done.
