### ISSUE TITLE
Unify <pub-date> and <history>

### ISSUE THREAD

**Issue by oliver----** [substance/texture#221]
JATS allows two ways to specify publication dates, either multiple `<pub-date>s` in `<article-meta>`, or `<date>s` in `article-meta > history`

We want to unify this, preferring `<history>` as it makes `<article-meta>` simpler.

Task:
- Introduce restrictions to JATS4R disallowing `<pub-date>s`
- Make `<date>` fields mandatory in TextureJATS
- UI:
  - Include the 'Publication History' panel into 'Article Record'
  - Support structured `<date>s`
- Converter:
  - Create empty date fields, when not present in JATS4R
  - Drop empty date fields if emtpy
  - Maybe support the iso-format as an export sugar

**Comment by oliver----** [comment]
Looking at `<date>` there are some UX challenges:
`(((day?, month?) | season)?, year?, era?, string-date?)`

We will introduce a `date-format` attribute, allowing us to have stricter validation.
On the long term, this could/should go into JATS4R.

**Comment by oliver----** [comment]
The only problem we now have, is that `<pub-date>` can have have `@pub-type` but `<date>` not.

**Comment by robertatakenaka** [comment]
@oliver---- @michael : DTD requires pub-date... So, is this issue about changing the DTD?

(article-id*, article-categories?, title-group, (contrib-group | aff | aff-alternatives)*, author-notes?, **pub-date+**, volume*, volume-id*, volume-series?, issue*, issue-id*, issue-title*, issue-sponsor*, issue-part?, volume-issue-group*, isbn*, supplement?, ((fpage, lpage?, page-range?) | elocation-id)?, (email | ext-link | uri | product | supplementary-material)*, history?, permissions?, self-uri*, (related-article | related-object)*, (abstract)*, trans-abstract*, (kwd-group)*, funding-group*, conference*, counts?, custom-meta-group?)

**Comment by oliver----** [comment]
Oh, Is it really `pub-date+`. 
We were just thinking about just using `history`, as it allows for the same content.
If pub-date is not optional, we can't do it. 

What is your opinion on this (one mandatory pub-date, and the rest inside of history)?

```
(article-id*, article-categories?, title-group, (contrib-group | aff | aff-alternatives)*, author-notes?, **pub-date**, volume*, volume-id*, volume-series?, issue*, issue-id*, issue-title*, issue-sponsor*, issue-part?, volume-issue-group*, isbn*, supplement?, ((fpage, lpage?, page-range?) | elocation-id)?, (email | ext-link | uri | product | supplementary-material)*, **history?**, permissions?, self-uri*, (related-article | related-object)*, (abstract)*, trans-abstract*, (kwd-group)*, funding-group*, conference*, counts?, custom-meta-group?)
```

**Comment by oliver----** [comment]
We are just confused, because `pub-date` allows for the same `date-types`, such as `received` etc.

**Comment by oliver----** [comment]
Re changing the DTD: we are more thinking in direction of a guide-line. It should still be compatible with the JATS DTD.

**Comment by oliver----** [comment]
BTW: JATS publishing is having `<pub-date>+` but JATS archiving `<pub-date>*`

**Comment by oliver----** [comment]
@robertatakenaka Thank you for the heads up. We realized that our proposal is the wrong way.

**Comment by oliver----** [comment]
We are closing this, as there is a semantical difference between pub-dates and history dates.
