### ISSUE TITLE
separating model and UI

### ISSUE THREAD

**Issue by blahah** [substance/texture#223]
@oliver---- @michael can I just confirm my understanding that texture will provide both the TextureJATS model and a UI?

If my understanding is correct, is it possible to separate these out? My use-case is that the model will be used in CLI node tools for normalising and validating JATS documents, while the UI will be used in electron apps.

If you prefer to keep them in a single module that is of course your prerogative, but I wanted to raise a use-case where keeping the conversion/modelling distinct from any rendering has benefits.

**Comment by oliver----** [comment]
See my comment on #220

**Comment by oliver----** [comment]
Conversion will be CLI'able. UI uses a fixed set of converters - the very same as CLI - to go between JATS4R and the internal variation called TextureJATS.
Lens would see JATS4R in first place. If were to rewrite Lens using components from Texture, we would just apply the same conversion as for the editor.
