### ISSUE TITLE
Add support to math

### ISSUE THREAD

**Issue by rgaiacs** [substance/texture#230]
I discovered the project after read https://elifesciences.org/labs/8de87c33/texture-an-open-science-manuscript-editor#new_tab and gave a short try at http://cdn.substance.io/texture-alpha-3/.

Is math support on your roadmap? If yes, are you planning to use MathML to support math?

**Comment by michael** [comment]
Hi! Math support is on our roadmap. We have implemented that already in other applications and plan to do it in a similar way. You'd be able to enter AsciiMath or Tex and we render the formula with KaTeX or MathJax.

Please try out http://stenci.la to see it in action (Insert -> Math).

**Comment by oliver----** [comment]
There is basic support now for inline-math. We will add support for `<disp-formula>` soon.

For sophisticated mathematical publications, there needs to be done more. E.g. dedicated support for Lemma, Proofs, etc. with automatic numbering.
