### ISSUE TITLE
Generate a spec from JATS4R.rng

### ISSUE THREAD

**Issue by michael** [substance/texture#237]
@oliver---- can we turn the schema into a readable spec we can share with peers? Think that must be already partially implemented (as seeing this in the import error reports).

**Comment by oliver----** [comment]
There is already a .md file generetad in `tmp/`. Take a look if this is good enough, or if we should improve that.

**Comment by oliver----** [comment]
We should maybe generate into the repo, so it is easier to open.

**Comment by michael** [comment]
Good enough to have it in tmp, it's not very readable anyway and we have the manually crafted JATS4M spec.
