### ISSUE TITLE
JATS4M: spec for <contrib> and <name>

### ISSUE THREAD

**Issue by michael** [substance/texture#239]
## `<contrib>`

```
(collab | name), xref*
```

## `<name>`

```
prefix?, suffix?, surname?, given-names?
```

Example: 

```xml
<contrib contrib-type="author">
  <name>
    <surname>Doe</surname>
    <given-names>John</given-names>
  </name>
  <xref ref-type="aff" rid="aff1"/>
  <xref ref-type="aff" rid="aff2"/>
</contrib>
```

- We've only considered authors so far, what else do we need?
- How to model group authors?

*Please help improve and finanlize this spec. It will be used for realizing the Texture user interface.*

**Comment by Melissa37** [comment]
I think I am being stupid here, but why do we need the 

```
xml
<x specific-use="display">John Doe</x>
```
? I don't like use of <x> tagging, and this information is in the surname/given name tags and it would be up to the renderer to display how it should?

Also, add <suffix>

**Comment by fabiobatalha** [comment]
@Melissa37 

I believe it is an specific use of Texture to display the authors name in the document while it is being edited by the user.

Thinking in the final XML results. It is not relevant for us to have this metadata represented in this way. For us the elements surname/given-name are enough. While exporting, downloading or reproducing the XML files from Texture, these display elements could be removed.

The x element is only available on JATS Archiving, our XML's and processes are all based on JATS Publishing, so this x element will not be compatible with our current processes. If they are available in the final XML, we will net to remove them before use the XML files.

**Comment by robertatakenaka** [comment]
@michael : we use also suffix: Sr, Jr, etc are suffixes. They are more usual than prefixes, which are such Doctor, Professor, President etc.

**Comment by Melissa37** [comment]
@fabiobatalha Thanks that makes sense. So, we would potentially use it to monitor who is making the changes to the document at a particular time, and could be for use in the database recording actions, and it's not used to record final publishable XML.

I am thinking a database recording actions on an article is not in the remit of this project, but the relaying of this will be important. It's akin to using the XML delivered to provide processing instructions?

**Comment by axfelix** [comment]
We need to be somewhat flexible for cases where we don't have given-name and surname disambiguated.

**Comment by oliver----** [comment]
@Melissa37 @fabiobatalha 

Re: `<x>`

I suppose, we only thought this was necessary to allow a self-contained file, i.e. having source and generated output in one file. Not mixing output and source is absolutely what we prefer. That said, if there are no objections, we would remove that here. Instead we should think about shipping a default renderer with Texture for people who do not know how to deal with the structured content.

**Comment by axfelix** [comment]
This would be preferable for us too!

**Comment by oliver----** [comment]
Great!

**Comment by fabiobatalha** [comment]
@oliver---- For us it is ok also.

**Comment by Melissa37** [comment]
Same here
