### ISSUE TITLE
JATS4M: spec for <aff>

### ISSUE THREAD

**Issue by michael** [substance/texture#240]
## `<aff>`

```
x[specific-use="display"], x[specific-use="original"]?, institution[content-type=orgname],
institution[content-type=orgdiv1]?, institution[content-type=orgdiv2]?,
institution[content-type=orgdiv3]?, addr-line[content-type=street-address]?,
addr-line[content-type=complements]?,
city?, state?, postal-code?, country?,
phone?, fax?, email?, uri?
```

Needs sign off by:

- [ ] PKP
- [ ] Erudit
- [ ] SciELO
- [ ] eLife

Example: 

```xml
<aff id="aff1">
  <institution content-type="orgname">Settles-Young Research Corporation</institution>
  <institution content-type="orgdiv1">Laboratory of Neural Systems</institution>
  <addr-line content-type="address-street">283 Hawthorne Drive</addr-line>
  <addr-line content-type="complements">Suite 310</addr-line>
  <city>Lexington</city>
  <state>KY</state>
  <postal-code>40503</postal-code>
  <country>USA</country>
  <phone>(859) 273-8543</phone>
  <fax>(859) 299-4683</fax>
  <email>lsy@settles-young.com</email>
  <uri>http://www.settles-young.com</uri>
</aff>
```

User Interface:

![image](https://user-images.githubusercontent.com/2931/29213564-05f44596-7ea4-11e7-9a5b-42395e228b82.png)

*Please help improve and finanlize this spec. It will be used for realizing the Texture user interface.*

**Comment by michael** [comment]
@fabiobatalha, @axfelix, @cormier, @oliver----, @Melissa37, @NateWr please have a look and let me know what could be done better.

My intention was to create a truly structured tagging, and provide a generated `<x>` element with a rendered version.

**Comment by fabiobatalha** [comment]
For the institutions departments/divisions we are using a most generic definition, once it could be different from institutions to institutions. (http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.6-branch/tagset/elemento-institution.html)

It means we are not fixing a name for a department or section, sub section, sub department, etc...

the content-type allowed is:

content-type | description
-- | --
orgname | Represents the first (highest) level of a multi-tier institution mentioned in the affiliation.
orgdiv1 | Represents the first subdivision of the institution mentioned.
orgdiv2 | Represents the second subdivision of the institution mentioned.
normalized | Name of the institution as normalized by SciELO.
original | Identifies the complete affiliation as it appears in the text of the article

**Normalized** is a SciELO requirement, this element should have the name of the institution based on a Official Institution Names directory. It may not be a mandatory requirement for texture.

**Comment by fabiobatalha** [comment]
@javani Could you give us some usage examples for Institutions?

**Comment by javani** [comment]
```
<aff id="aff1">
				<label>1</label>
				<institution content-type="original">Departamento de Botânica, Centro de Ciências
					Biológicas, Universidade Federal de Pernambuco, 50670-901, Recife, PE,
					Brazil</institution>
				<institution content-type="normalized">Universidade Federal de
					Pernambuco</institution>
				<institution content-type="orgdiv2">Departamento de Botânica</institution>
				<institution content-type="orgdiv1">Centro de Ciências Biológicas</institution>
				<institution content-type="orgname">Universidade Federal de Pernambuco</institution>
				<addr-line>
					<named-content content-type="city">Recife</named-content>
					<named-content content-type="state">PE</named-content>
				</addr-line>
				<country country="BR">Brazil</country>
			</aff>
```
```
	<aff id="aff2">
				<label>2</label>
				<institution content-type="original"> Centro de Investigaciones y Estudios sobre Cultura y Sociedad, Universidad Nacional de Córdoba, Córdoba, Argentina.</institution>
				<institution content-type="normalized">Universidad Nacional de Córdoba</institution>
				<institution content-type="orgdiv1">Centro de Investigaciones y Estudios sobre Cultura y Sociedad</institution>
				<institution content-type="orgname">Universidad Nacional de Córdoba</institution>
				<addr-line>
					<named-content content-type="city">Córdoba</named-content>
				</addr-line>
				<country country="AR">Argentina</country>
			</aff>
```
```
<aff id="aff1">
				<label>1</label>
				<institution content-type="original">Graduate Program in Dentistry, School of Life Sciences, PUCPR, Curitiba, PR, Brazil</institution>
				<institution content-type="normalized">Pontifícia Universidade Católica do Paraná</institution>
				<institution content-type="orgname">PUCPR</institution>
				<addr-line>
					<named-content content-type="city">Curitiba</named-content>
					<named-content content-type="state">PR</named-content>
				</addr-line>
				<country country="BR">Brazil</country>
			</aff>
```

**Comment by michael** [comment]
@fabiobatalha, @javani thanks! The structure `orgname > orgdiv1 > orgdiv2` looks ok to me. I understand that the first division not always is a department. Arrr, why can't all orgs worldwide be organised the same way?! :D Then we could put the right semantics.

Are you find with using `<city>` and `<state>` tags instead of `<named-content>`? We want to get the JATS4R spec as expressive as possible. However, we could provide a small transformer so SciELO could stick with their tagging for a while. However in the long run it would be great if we could all speak the same language so it does not matter anymore if SciELO or eLife produced the article.

As for `original`: Would you be ok with moving this into an `<x>` element instead? We would not capture this element when the article is created from scratch in Texture but you could include it as part of your conversion process so that information is not lost.

In my eyes your `normalized` version of the institution is equivalent with what I had in mind for `<x specific-use="display">...</x>`. This is a generated string based on the structured data we now have. You'll be able to configure Texture how that normalized string should be computed (e.g. with a template string).

Will update the proposal above, and you can review.

**Comment by michael** [comment]
What about using `name > division > subdivision` instead? Slightly more expressive...

**Comment by fabiobatalha** [comment]
No sure about this, and If an Institution may have their departments organized in more than 2 levels?

name > division > subdivision > subsubdivision....

orgname > orgdiv1 > orgdiv2 > orgdiv3...

 thoughts?

**Comment by fabiobatalha** [comment]
@michael 

The next version of the SciELO PS 1.7 will deprecate the named-content element. So Texture can adopt the elements country, city and state, instead of the named-content.

**Comment by michael** [comment]
Ok, let's go with orgname, orgdiv1, orgdiv2, orgdiv3 if no objections? It's expressive enough and then SciELO don't have to change their tagging.

@oliver---- are we able to validate this on attribute level in our schema interpretation? Like:

```
institution[orgname], institution[orgdiv1]?, institution[orgdiv2]?, institution[orgdiv3]?
```

**Comment by oliver----** [comment]
Probably it is possible in RNG, but our validator does not yet support tagName+attr combinations.
But let's assume it could.

**Comment by michael** [comment]
How would we model that in RNG now, so that it works on tagname level now and tagname+attr level later?

**Comment by oliver----** [comment]
Dunno yet.
Let's put (institution+) in JATS4R for now, and throw in the converter for now.

**Comment by michael** [comment]
ok, sounds good!

@fabiobatalha how do you tag `addr-line` at SciELO?

```
addr-line[addrline1], addr-line[addrline2], addr-line[addrline3]
```

would addrline1 always be the street? Generally I wonder if we should tag streetname + street number separately.. and then have everything else in extra addr-line statements (Building A, 1st foor, door 3 etc) ?

**Comment by michael** [comment]
@NateWr would you be in for implementing this improved affiliation editing and/or #239 ? should be relatively straight forward.. and i can help with schema validation + transformers. Let me know, and i can create complete UI mockups for you.

**Comment by fabiobatalha** [comment]
My first thought is we will not be able to establish an order on it. So the same idea of orgdiv1 orgdiv2 may not works well for addresses.

Maybe we should use something more precise, like.

addr-line[address], addr-line[number], addr-line[city], addr-line[country], addr-line[state], addr-line[complements] may cover most of the situations.

The display mode could work like Affiliations, allowing the user to establish a display pattern that will be automatically build and stored in <x display>.

I will check this with my colleagues.

**Comment by michael** [comment]
Agree. I'd like to have as much semantics as possible, but not sure about practicability. E.g. separate street + number may be more semantic but not practical.

Microformats uses the following field semantics:

```
p-street-address - house/apartment number, floor, street name
p-extended-address - additional street details
p-post-office-box - post office mailbox
p-locality - city/town/village
p-region - state/county/province
p-postal-code - postal code, e.g. ZIP in the US
p-country-name - should be full name of country, country code ok
p-label - a mailing label, plain text, perhaps with preformatting
p-geo (or u-geo with a RFC 5870 geo: URL), optionally embedded h-geo
p-latitude - decimal latitude
p-longitude - decimal longitude
p-altitude - decimal altitude - new in vCard4 (RFC6350)
```

Example:

```html
<p class="h-adr">
  <span class="p-street-address">17 Austerstræti</span>
  <span class="p-locality">Reykjavík</span>
  <span class="p-country-name">Iceland</span>
  <span class="p-postal-code">107</span>
</p>
```

**Comment by michael** [comment]
Thinking about i think we should keep streetname and number separate for practical reasons. Otherwise we need to also store wether the number should be prefixed or postfixed.

How about this:

```
addr-line[content-type=street-address],addr-line[content-type=complements]?,
city, state, postal-code, country
```

**Comment by NateWr** [comment]
> would you be in for implementing this improved affiliation editing and/or #239 ?

Sure! This week is pretty busy but I'd be happy to give it a shot. I may not need UI mockups, but happy to look at anything you want. Is the spec in the first message the one to work towards?

**Comment by michael** [comment]
@NateWr great! Yes the spec in the first message should be pretty close to what we want to achieve. Befor you start, could you verify if the proposed spec is suitable for PKP too?

I'll be on holiday next week, you can start it, but if you hit any blockers just wait for me until I'm back. There's no rush. Thanks a lot for helping out!

**Comment by Melissa37** [comment]
I really hope the OrgID group is going to come up with something so we can just pull metadata from a common database and incorporate that! But it's going to be a while.

**Comment by axfelix** [comment]
Am I misunderstanding, or are we making city, state, etc, required?

**Comment by michael** [comment]
Let's keep them optional and instead display warnings later, once we get the linter in place.

**Comment by fabiobatalha** [comment]
@axfelix it seems they are mandatory. But I think they should not be.

At least in SciELO use cases we don't have all this information, so texture should deal with a more flexible content set.

**Comment by fabiobatalha** [comment]
@michael Ok!

**Comment by oliver----** [comment]
Exactly!

**Comment by axfelix** [comment]
Sounds good. Only email and institution should be required.

**Comment by fabiobatalha** [comment]
@axfelix

I'm not sure about the email. I think it should be optional also.

**Comment by Melissa37** [comment]
Would there be a mechanism for individual publishers to indicate what fields should be displayed and mandatory on their interface? Therefore they could be all optional fields and the default is they all display. Then authors using this tool not connected to publication with a journal have flexibility and the journal then can have the flexibility to be more specific?

If eLife uses this we'd hide some fields, make some mandatory...every publisher is going to be slightly different!


Or is that adding too much complexity?

**Comment by michael** [comment]
@Melissa37 I'd try to have the same schema for everyone and go with optional fields when necessary. In order to allow journals to define their own quality criteria we are planning to implement a "Linter mechanism", where rules can be specified and warnings are printed if the rules are not met. This is basically what schematron does for you now, but we could integrate that tightly with the Texture UI (e.g. add color to problematic fields).

**Comment by Melissa37** [comment]
Cool, sounds good!

**Comment by pigeonm** [comment]
Hi, 

About what is required and what is optional : 

Once again, your work goes beyond what we are currently doing with affiliations. 

According to the needs of Erudit, everything in the affiliation must be optional (the affiliation itself, the email address, the institution and the address). We also need to be able to seize an unstructured affiliation (text string only) which is allowed in JATS 1.1. Is it in JATS4R ?

About an institution and its subdivisions, what you're proposing (orgname, orgdiv1, orgdiv2) is ok with Erudit.

**Comment by Melissa37** [comment]
I'm cool with this work now and happy to sign off on it. However, there is a JATS4R sub-group working on authors and affiliations and I think they would really value your input and feedback. I will alert the subgroup chair to this thread, and you might need to change slightly depending on the outcomes of that working group.

**Comment by michael** [comment]
Thank you everyone for the fruitful discussions here. I've consolidated all the specification work into a single document: https://github.com/substance/texture/blob/master/docs/JATS4M.md

I will close this issue now, as I think we created a good base. Please open new issues anytime if you have questions, suggestions how to improve the current spec.
