### ISSUE TITLE
Texture:  indicates error to duplicate ```<person-group>``` in ```<element-citation>```

### ISSUE THREAD

**Issue by suelylc** [substance/texture#244]
We noted that the Texture indicates a problem when there are two groups of  authors in  <element-citation publication-type="book">, as in the example below.
 
![error_person group](https://user-images.githubusercontent.com/6921625/29787996-5db36346-8c07-11e7-8d02-50cc58f68906.JPG)

It would be important to keep these two groups tagged already they compose the reference in its complete form and there would be no missing date.
EX:
```<ref id="B07">
					<label>2</label>
					<mixed-citation>Calkins BM, Mendeloff AI. The epidemiology of idiopathic inflammatory bowel disease. In: Kirsner JB, Shorter RG, eds. Inflammatory bowel disease, 4th ed. Baltimore: Williams &amp; Wilkins. 1995:31-68.</mixed-citation>
					<element-citation publication-type="book">
						<person-group person-group-type="author">
							<name>
								<surname>Calkins</surname>
								<given-names>BM</given-names>
							</name>
							<name>
								<surname>Mendeloff</surname>
								<given-names>AI</given-names>
							</name>
						</person-group>
						<chapter-title>The epidemiology of idiopathic inflammatory bowel
							disease.</chapter-title>
						<person-group person-group-type="editor">
							<name>
								<surname>Kirsner</surname>
								<given-names>JB</given-names>
							</name>
							<name>
								<surname>Shorter</surname>
								<given-names>RG</given-names>
							</name>
						</person-group>
						<source>Inflammatory bowel disease</source>
						<edition>4th ed</edition>
						<publisher-loc>Baltimore</publisher-loc>
						<publisher-name>Williams &amp; Wilkins</publisher-name>
						<year>1995</year>
						<fpage>31</fpage>
						<lpage>68</lpage>
					</element-citation>
				</ref>```

Whether is useful we can see the use to <person-group> and its attributes is available in https://jats.nlm.nih.gov/publishing/tag-library/1.0/index.html

**Comment by michael** [comment]
I see that the second `person-group` refers to editors, while the first has the authors. I wonder if editors need to be really tracked in a JATS reference. I assume the editor will not be rendered in the rendered citation string. So why do we need to capture that information in a ref element if it's never going to be used?

**Comment by suelylc** [comment]
@michael we do think that it's important to provide editing fields that contemplate all information of each bibliographic reference. As this is done, allows the preservation of all data in a structured according the xml file specifications that is expected in SciELO  and PMC

**Comment by michael** [comment]
The question is how much info should go into an element-citation? Where is the line to stop? I mean one could even include the abstract of in an element-citation. Or the copyright statement.

@Melissa37 what's your policy at eLife for that?

**Comment by Melissa37** [comment]
I agree with the others - we collect 2 person-groups  with @person-group-type="author" and @person-group-type="editor" and both these groups are displayed int he output. Ur renderer adds "Eds" to the editors list so it is clear to the reader who these authors are.
Readers are interested in names of people involved in the production of this content and a big name editor of a book adds weight to the reference, but the author of the chapter is the author of this content being referenced.

Hope that helps?

**Comment by michael** [comment]
Thanks a lot! I'm convinced now that we need two person groups (author and editor). Will update the spec document. (#238)

**Comment by michael** [comment]
Multiple person groups are supported now via #274 .
