### ISSUE TITLE
Support to Blockquote (`<disp-quote>`) is not working.

### ISSUE THREAD

**Issue by cinthia-vieira** [substance/texture#247]
Documents and archives with the tag `<disp-quote>` in their `<body>` are not being opened to edition on the Texture Wrapper.

Once uploaded a XML file which contains a `<disp-quote>` tag, the document doesn't open the editor, leaving the screen blank, as it can be seen [here](http://homolog.texture.scielo.org/editor?file=/files/prod/v27nspe/0034-7744-rbt-63-03-00004.xml).

If you remove the `<disp-quote>` tag, the document is loaded fully to edition, or validation, as [this version](http://homolog.texture.scielo.org/editor?file=/files/prod/v27nspe/0034-7744-rbt-63-03-00004-b.xml) of the XML above, which has no `<disp-quote>` used in its body, shows.

The following link shows the XML file which contains the `<disp-quote>` tag in use, according to the proposed schema (outside the `<p>` tag, e.g.): [0034-7744-rbt-63-03-00004](http://homolog.texture.scielo.org/files/prod/v27nspe/0034-7744-rbt-63-03-00004.xml). As it can be seen, the `<disp-quote>` is marked correctly on the XML document.

As the blank page can also be a problem with my browser (since in the first time I tested the blockquotes just were being supressed from the article text), here are some extra info: the tests were run on Mozilla Firefox 54.0.1 (32-bit) and Google Chrome 60.0.3112.113 (64-bit), on a Windows7 64-bit SO.

**Comment by michael** [comment]
`disp-quote` elements should be supported already. There's an example in the kitchen_sink.xml file. See: http://cdn.substance.io/texture-alpha-3/?file=data/kitchen-sink.xml

It must fulfil a certain tagging style though, like this:

```xml
<disp-quote>
  <p>lorem</p>
  <p>ipsum</p>
  <attrib>Mr. XYZ</attrib>
</disp-quote>
```

Can you provide the full markup of the disp-quote element not being editable?

**Comment by michael** [comment]
Dup of #256.
