### ISSUE TITLE
Texture: There isn't field to collaborative author 

### ISSUE THREAD

**Issue by suelylc** [substance/texture#248]
The structure to collaborative author is not available for adding data in Edit Reference

It would be suitable for this xml structure, usade in bibliographic reference

Ex:

``` <person-group person-group-type="author">
          <collab>World Health Organization (WHO)</collab>
     </person-group>
```

Links:
https://jats.nlm.nih.gov/publishing/tag-library/1.0/n-cu50.html

http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/master/tagset/elemento-collab.html#exemplo-de-collab-em-back

**Comment by michael** [comment]
This will be added in the next version. See https://github.com/substance/texture/issues/238 where it is specced out.
