### ISSUE TITLE
Possibility to allow <publisher-name/loc> more than once

### ISSUE THREAD

**Issue by cinthia-vieira** [substance/texture#249]
The current Schema allow just one Publisher Name (`<publisher-name>`) and Location (`<publisher-loc>`) by `<ref>`, showing a message error in case the reference got the tags used more than once.

It'd be intersting to change the current schema (that allows the tags use zero or one time) to allow its occurence to be zero or more times (`~publisher-name* ~publisher-loc*`). 

The reason is that even if it's not common, there are books published in two different locations, or by two Publishers (or both) and this is cited in the refs., e. g.:

> HESSEN, Johannes. *Teoria do conhecimento*. 7. ed. **Coimbra: Armênio Amado; São Paulo: Martins Fontes**, 1979

As we can see, the example above was published by both Armênio Amado and Martins Fontes, located respectively at Coimbra, Portugal and São Paulo, Brazil. There are also cases that the Publisher has two official locations and put both of them in their bibliographic information. Since the person who will make the references cannot choose one of the sites as the "truly official" one, both of them are put in the reference text, generating two `<publisher-loc>` in the XML tagging. 

[This file](http://homolog.texture.scielo.org/editor?file=/files/prod/v27nspe/1678-3921-pab-51-12-e34.xml) shows the mentioned message error -- [this being](http://homolog.texture.scielo.org/files/prod/v27nspe/1678-3921-pab-51-12-e34.xml) its XML form -- and the following printscreen shows the message by itself.

![image](https://user-images.githubusercontent.com/27728729/29935375-ef83bdee-8e54-11e7-8538-55cf0eed4a58.png)

**Comment by michael** [comment]
Hi @cinthia-vieira! Thank you for bringing up that use-case. We are open to consider changing the schema to allow multiple publisher-name and publisher-loc elements. However, I'm worried that this would complicate the user interface. Instead of just showing two form fields with labels to fill out we'd need a UI that allows creating new publisher-loc/name entries and deleting them, which would 
 be fairly complicated.  Can you think of other (better ways) to tag such situations? If this is really a rare case could we accept putting both publisher names into one field, separated with a comma? Another solution would be allowing 0,1 or 2 elements. And always show two input fields in the user interface. But that's only possible if there never be 3 publishers involved? Let me know what you think.

**Comment by cinthia-vieira** [comment]
Hey, @michael, thanks for the feedback!

I don't think it's interesting to tag both publishers/locations in just one tag because this would generate some problems both to retrieve and archive the infos of said references. 

However, the second option (allowing its use twice or three times max.), and always showing the fields suits our needs better. As I said, it's an uncommon situation, but it happens anyway. That said, it is really difficult (to not saying impossible and inexistent) to see a book published in more than two places (I mean, in this way of publishing), so I think that limitating the fields up to two it's fine. 

This example in JATS also illustrates better what we're talking about and how the XML tagging is done when this happens: https://jats.nlm.nih.gov/publishing/tag-library/1.0/n-dv70.html

**Comment by michael** [comment]
Thank you for the explanation.

@Melissa37 @fabiobatalha what are your thoughts here?

**Comment by Melissa37** [comment]
We often have a book publisher with 2 locations (ie Europe and US) and we tput them in the same <publisher-loc>, comma separated.

Also, if an author has provided a city and country for the publisher location, they both go in this tag, comma separated.

So I already feel like this tag is not great for machine readability with the way we use it, and there is no good API like PubMed or Crossref for non-journal content, so we are more flexible and less semantic about tagging this but feel the effort to get it right far outweighs the use cases.

Sorry to not be more helpful!

**Comment by fabiobatalha** [comment]
@michael 

I have the @cinthia-vieira explanations as my words.
By the way, @cinthia-vieira is a Technician of the SciELO team.

**Comment by michael** [comment]
Thank you everyone! I think I understand the problem now.

We need to make a decision here, I see two reasonable options:

1. Only allow one publisher-loc/publisher name and do comma separation as done by eLife
2. Allow any number of loc/name pairs and display 2 input fields in Texture by default, if more elements are provided in the XML they are shown in the UI.

Option 1 is already implemented. Option 2 needs a  fair bit of work, as we need to internally transform the data into a more usable form. For explanation, that's how we would model it internally.

```xml
<publishers>
   <publisher>
     <publisher-name>A</publisher-name>
     <publisher-loc>X</publisher-loc>
   </publisher>
   <publisher>
     <publisher-name>B</publisher-name>
     <publisher-loc>Y</publisher-loc>
   </publisher>
</publishers>
```

@cinthia-vieira would option 1 be acceptable for you for a while? I'm not sure we should make this edge case a high priority, there's so much else to do.

**Comment by michael** [comment]
@cinthia-vieira after some consideration I'd like to with just one publisher-name / publisher-loc pair in the user interface. This will do for 95% of the cases, and if multiple publishers are referenced you can enter them comma separated. However for input/output we could allow multiple publisher-name/publisher loc instances, so it's only a matter of entering the data, but keeping it separated in the XML.

Would that be an acceptable solution for you?

**Comment by francine-curivil** [comment]
Hi @michael 
We discuss this internally and conclude that this solution is acceptable to us.

_P.S.: i'm a librarian of the SciELO team._

**Comment by michael** [comment]
Nice to meet you @francine-curivil! Thank you for confirming. We will implement it that way and ship it with the next release!

**Comment by michael** [comment]
@Integral you could take over this one.

Steps needed:

- Update JATS4M spec (substance/dar) to allow multiple publisher-name/loc elements. Point me to PR when done
- Add a sample to kitchen_sink (2 publisher-name/loc pairs for one of the references)
- Introduce a transformer that turns them into `;` separated strings (EntityDatabase model does not need to be changed) on import and creates multiple publisher-name/loc elements on export.

**Comment by Integral** [comment]
I will take this, thx

**Comment by Integral** [comment]
@michael pls review #397

**Comment by michael** [comment]
This is now done, we will ship that feature with Alpha 4 in a few days.
