### ISSUE TITLE
Texture indicates error to <ext-link> in <element-citation>

### ISSUE THREAD

**Issue by alexxpsilva** [substance/texture#250]
We have identified that when there are references that have external links the error below.

![texture_ext-link](https://user-images.githubusercontent.com/15328777/29938463-2e70c510-8e5f-11e7-9822-80d0173a9535.png)

It would be important to keep this tag marked as it composes the reference in its complete form.

Example:

```<ref id="B001">
				<element-citation publication-type="journal">
					<person-group person-group-type="author">
						<name>
							<surname>Anekella</surname>
							<given-names>K.</given-names>
						</name>
						<name>
							<surname>Orsat</surname>
							<given-names>V.</given-names>
						</name>
					</person-group>
					<year>2013</year>
					<article-title>Optimization of microencapsulation of probiotics in raspberry
						juice by spray drying</article-title>
					<source>Lebensmittel-Wissenschaft + Technologie</source>
					<volume>50</volume>
					<issue>1</issue>
					<fpage>17</fpage>
					<lpage>24</lpage>
					<ext-link ext-link-type="uri"
						xlink:href="http://dx.doi.org/10.1016/j.lwt.2012.08.003"
						>http://dx.doi.org/10.1016/j.lwt.2012.08.003</ext-link>
				</element-citation>
				<mixed-citation>Anekella, K., &amp; Orsat, V. (2013). Optimization of
					microencapsulation of probiotics in raspberry juice by spray drying.
						<italic>Lebensmittel-Wissenschaft + Technologie</italic>, 50(1), 17-24.
						<ext-link ext-link-type="uri"
						xlink:href="http://dx.doi.org/10.1016/j.lwt.2012.08.003"
						>http://dx.doi.org/10.1016/j.lwt.2012.08.003</ext-link>. </mixed-citation>
			</ref>
```

I use it to inform the use of the <element-citation> tag for us Team SciELO
http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.6-branch/tagset/elemento-element-citation.html#element-citation and JATS 1.0 is allowed https://jats.nlm.nih.gov/publishing/tag-library/1.0/n-bnu0.html

**Comment by michael** [comment]
Are there more use-cases for ext-link other than linking to a DOI? 

For DOI's it would be better to use a `<pub-id pub-id-type="doi"> 10.1016/j.lwt.2012.08.003</pub-id>` element.

I'd be happy to add an `ext-link` element, but would rather not use it for expressing doi's. Well actually there's a `<uri>` element too which would fit much better. `<ext-link>` imo is more used in the text flow, while uri acts more like a property (thus more semantic). What do you think?

**Comment by alexxpsilva** [comment]
We use  ```<ext-link>```   to "uri" and "clinical-trial" http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.6-branch/tagset/elemento-ext-link.html#ext-link

About the "uri" I agree with you.

**Comment by michael** [comment]
I'm all for using pub-ids instead of ext-links. If it's hard for you to update your documents to reflect this, we can help out with a transformer specific for SciELO that turns ext-link elements into the correct pub-id taggings. Ok with that approach?

**Comment by javani** [comment]
It's common have URLs in references besides of pud-id. The ext-link element is used to identify them.

**Comment by michael** [comment]
Please see JATS4M schema for element-citation. 

https://github.com/substance/dar/blob/master/specs/JATS4M.md#references

If something is missing or wrong, please create an issue in the Dar repository.
