### ISSUE TITLE
fig issues?

### ISSUE THREAD

**Issue by axfelix** [substance/texture#252]
Hi folks,

Any chance that Texture is picky about figure content right now?
![fig](https://user-images.githubusercontent.com/252047/29947955-1221beda-8e61-11e7-97c2-178a054f2c37.png)

Getting this in the most recent build... still happens when figure elements are removed from the document though, so it might be due to something unrelated? (I know this one has front matter issues too but it's triggered on others that pass otherwise)

[figdoc.xml.txt](https://github.com/substance/texture/files/1268667/figdoc.xml.txt)

**Comment by michael** [comment]
Is this happening immediately after loading, or during editing? 

Generally figures definitely need work. We are also missing an agreed JATS4R spec yet. I will open a requirements issue to kick this off as soon as I get some time.

**Comment by axfelix** [comment]
OK, I confirmed this doesn't happen when figures are removed from the document, it is actually an issue with their inclusion.

Right now we're hitting whitescreens with both fig and disp-quote in many cases -- both are probably due to some non-validating behaviour in our parsing engine, which we can work on, but it's worth noting that these are a) making it through your validator, i.e., not failing gracefully, and b) causing problems for a *significant* number of documents output by OTS, which is interfering with our ability to use Texture right now. So while we're trying to fix our parsing, we would still benefit significantly from Texture being able to better-handle XML that it doesn't like (even if that means just discarding elements).

**Comment by vishnukpkp** [comment]
actually this same issue is happening to me when i edited the sample xml and reloaded it.
What i found is the output xml after editing doesnt hve title in it..Some how all title tags r removed

**Comment by axfelix** [comment]
Can we figure out what's causing problems here currently? I imagine it's something similar to the issues with disp-quote -- technically valid JATS that breaks when it's expanded in the current release. These seems to be our only two whitescreening issues right now.

**Comment by axfelix** [comment]
the structure that Texture doesn't like currently just looks like this:

    <fig>
      <graphic xlink:href="var/documents/309/1177/cermine/document.images/img_4_1.png"/>
    </fig>

**Comment by michael** [comment]
I will have a look.

**Comment by michael** [comment]
This breaks late in the component code, not on the converter. It's because the caption title element is missing.

![image](https://user-images.githubusercontent.com/2931/30491272-13604a54-9a3d-11e7-96db-6b90a5f3a09e.png)

These things will all fixed with the next iteration when #265 gets implemented. We will then ensure that a title element always gets expanded even if not existing in the source.

Looking at the example you gave me: label + caption should not go into the graphic element.

```xml
<fig position="float" orientation="portrait">
  <graphic xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="media/image1.png" id="IDd2a8881d-ee4a-4b2d-873c-fb6b56e50c35" position="float" orientation="portrait" xlink:type="simple">
    <label>Figure 1</label>
    <caption>
      <p>Brain wave samples with dominant frequencies belonging to beta, alpha, theta, and delta band</p>
    </caption>
  </graphic>
</fig>
```

They should be under fig. In order to make this document pass in Texture Alpha 3 the markup should be like so:

```xml
<fig position="float" orientation="portrait">
  <label>Figure 1</label>
  <caption>
    <!-- Texture does not handle missing titles atm so provide an empty one -->
    <title></title>
    <p>Brain wave samples with dominant frequencies belonging to beta, alpha, theta, and delta band</p>
  </caption>
  <graphic xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="media/image1.png" id="IDd2a8881d-ee4a-4b2d-873c-fb6b56e50c35" position="float" orientation="portrait" xlink:type="simple"></graphic>
</fig>
```

**Comment by axfelix** [comment]
OK, thanks! We can revise the placement of label + caption for now.

**Comment by michael** [comment]
Closing this. Further discussion in #265.
