### ISSUE TITLE
JATS4M: Generated display version of <ref>

### ISSUE THREAD

**Issue by michael** [substance/texture#257]
In addition to capturing structured information for citations (specified in #238) we need a way to render/preview them in Texture. On the bottom of the manuscript we want to display a list of references, rendered closely to how they would look in a final publication or the printed PDF.

@Integral please start with implementing a Preview component for each journal and book citation types and then dispatch in the RefComponent using the component registry. Think you can remove ElementCitationComponent which currently does the rendering job.

Here's how it would look like for JournalCitationPreview:

```js
class JournalCitationPreview extends Component {
  render($$) {
    let el = $$('sc-journal-citation-preview')
    let articleTitle = elementCitation.find('article-title').text()
    let source = elementCitation.find('source').text()
    let year = elementCitation.find('year').text()
    let issue = elementCitation.find('issue').text()
    let fpage = elementCitation.find('fpage').text()
    let lpage = elementCitation.find('lpage').text()

    el.append(
      authorsString(elementCitation),
      '. ',
      year,
      '. ',
      articleTitle,
      source,
      $$('bold').append(
        issue
      ),
      ':',
      fpage,
      '-',
      lpage
    )
  }
}
```

**Comment by michael** [comment]
Thinking more about I think we should consider not adding the `<x>` elements. Any objections?

See also https://github.com/substance/texture/issues/239 where we decided to drop the x.

**Comment by oliver----** [comment]
Let's do it consistently. It seems that `<x>` is problematic, as it is only part of JATS archiving.

**Comment by Integral** [comment]
@michael i've created a PR. Please don't merge, but review it.
What I also want to discuss is what we should do with editors. Also this way we have pretty nice default citation, e.g. if you'll click on add new reference you will see `. . . :-`.

**Comment by michael** [comment]
No longer applicable.
