### ISSUE TITLE
Proposal: JATS4M as a pure source format

### ISSUE THREAD

**Issue by michael** [substance/texture#273]
This is a proposal for considering turning JATS4R into a pure source-format.

Goals:

- One pure (semantic) source format suitable for every journal (no labels for fig, xref, ref-list are part of the content)
- Allow journals to apply their preferred style automatically (choose citation style, language, journal-specific rules) using a post-processor.
- Speed up Texture development by separation of concerns
- Get rid of print-legacy artefacts in JATS

Consider an `article.source.xml` file that conforms to JATS4R, here's a snippet:

```xml
<p>Lorem ipsum <xref ref-type="bibr" rid="r2"/></p>
<fig>
  <caption>...</caption>
  <graphic/>
</fig>
```

This can be loaded and edited in Texture and saved. During editing automatic numbered labels (e.g. [2]) are displayed. Next, a post-processor is run based on a journal specific configuration:

- citation style
- language
- overrides (e.g. use 'Scheme 1' instead of 'Figure 1')

The result is an `article.archive.xml` suitable for PMC (PubMedCentral) archiving, or as a source for PDF generation:

```xml
<p>Lorem ipsum <xref ref-type="bibr" rid="r2">Biederman, 1987</xref></p>
<fig>
  <label>Figure 1.</label>
  <caption>...</caption>
  <graphic/>
</fig>
```

Advantages:

- Lightweight numbered generator for labels can be used in Texture
- Heavier toolchains such as Citeproc are easy to integrate in a post-processing step

Real-world workflow:

1.) Open source document in Texture: Semantic editing of pure content
2.) Live Preview (see how the publication will look like when published
3.) Source and archive XML files are stored on disk.

**Comment by Melissa37** [comment]
Sounds good to me.

PMC (PubMedCentral) is the archiving location, PubMed is just abstracts :-)

**Comment by michael** [comment]
Thanks for the clarification. :) Updated the text.

**Comment by michael** [comment]
Think we can continue with a combined approach for now. Labels are included in the source format, but will be replaced when opened in Texture.
