### ISSUE TITLE
latest branch also not working after editing 

### ISSUE THREAD

**Issue by vishnukpkp** [substance/texture#275]
<img width="1306" alt="screen shot 2017-09-22 at 3 24 01 pm" src="https://user-images.githubusercontent.com/30597979/30739285-62a53ada-9faa-11e7-91db-9e8a6f6aaeca.png">

**Comment by michael** [comment]
Please provide more context info. Can you provide a stripped down XML file that has the content that produces that error.

element-citation editing is a work in progress, so it's likely there are errors related to it. See #238

**Comment by michael** [comment]
Guess this is no longer applicable. Closing.
