### ISSUE TITLE
JATS4M: Example with group authors, affiliations, equal-contrib

### ISSUE THREAD

**Issue by michael** [substance/texture#277]
Here's our proposed tagging for group authors according to [eLife kitchen sink XML](https://github.com/elifesciences/XML-mapping/blob/master/elife-00666.xml) and the [PMC tagging standards](https://www.ncbi.nlm.nih.gov/pmc/pmcdoc/tagging-guidelines/article/dobs.html#dob-collab):

```xml
<article-meta>
...
<contrib-group content-type="authors">
  <contrib contrib-type="author">
    <name>
      <surname>Church</surname><given-names>Deanna M.</given-names>
    </name>
    <xref ref-type="aff" rid="aff1"/>
  </contrib>
  <contrib contrib-type="author">
    <name>
      <surname>Goodstadt</surname><given-names>Leo</given-names>
    </name>
    <xref ref-type="aff" rid="aff1"/>
  </contrib>
  <contrib contrib-type="author" equal-contrib="yes">
    <name>
      <surname>Hillier</surname><given-names>LaDeana W.</given-names>
    </name>
    <xref ref-type="aff" rid="aff1"/>
  </contrib>
  <contrib contrib-type="author-group" equal-contrib="yes">
    <collab>
      The Mouse Genome Sequencing Consortium
      <xref ref-type="aff" rid="aff1"/>
      <contrib-group>
        <contrib>
          <name>
            <surname>Kelly</surname><given-names>Laura A.</given-names>
          </name>
        </contrib>
        <contrib>
          <name>
            <surname>Randall</surname><given-names>Daniel Lee</given-names>
            <suffix>Jr.</suffix>
          </name>
        </contrib>
      </contrib-group>
    </collab>
  </contrib>
</contrib-group>

<contrib-group content-type="editors">
  <contrib contrib-type="editor">
    <name>
      <surname>Jane</surname><given-names>Doe</given-names>
    </name>
    <xref ref-type="aff" rid="aff1"/>
  </contrib>
</contrib-group>

<aff id="aff1">
  <institution content-type="orgname">Settles-Young Research Corporation</institution>
  <institution content-type="orgdiv1">Laboratory of Neural Systems</institution>
  <addr-line content-type="address-street">283 Hawthorne Drive</addr-line>
  <addr-line content-type="complements">Suite 310</addr-line>
  <city>Lexington</city>
  <state>KY</state>
  <postal-code>40503</postal-code>
  <country>USA</country>
  <phone>(859) 273-8543</phone>
  <fax>(859) 299-4683</fax>
  <email>lsy@settles-young.com</email>
  <uri>http://www.settles-young.com</uri>
</aff>
...
</article-meta>
```

**Comment by michael** [comment]
A note on the implementation strategy: What we will do internally is detecting group authors (match contrib > collab structures) and turn them into an explicit schema which we can use during editing in JATS. That way we can prevent creating nested group author structures in the editor, etc. However after save, it will again look exactly like above.

```xml
<group-author-contrib>
  <name>    The Mouse Genome Sequencing Consortium</name>
  <group-author-contrib-group>
    <contrib equal-contrib="yes">
      <name>
        <surname>Kelly</surname><given-names>Laura A.</given-names>
      </name>
      <xref ref-type="aff" rid="aff1"/>
    </contrib>
    <contrib equal-contrib="yes">
      <name>
        <surname>Randall</surname><given-names>Daniel Lee</given-names>
        <suffix>Jr.</suffix>
      </name>
      <xref ref-type="aff" rid="aff1"/>
    </contrib>
  </group-author-contrib-group>
</group-author-contrib>
```

**Comment by michael** [comment]
@robertatakenaka @fabiobatalha can you comment on this (proposal in first post)?

**Comment by Melissa37** [comment]
HI there

Some comments from eLife:

We talked about the @equal-contrib you have on a member of a group. We've thought only the group name at the higher level as potentially the equal contributor. But I can see how some members of a group may want to signal their equal contribution with each other. However, it would get very complex and I'd advise against coding that right now! The member of the group cannot be an equal contributor with other top level authors, only within their group. I hope that makes sense?! A bit complicated!

Other cases that spring to mind:

- The group author at the top level has an affiliation, but none of the members of the group do
- If members of the group have affiliations that are not the same as primary level authors, it would be unusual to publish their affiliations on the same level as the other affiliations - they should not receive the same weight.
- need to allow for a group author with no other information (ie no members of the group defined)
- some members of a group sub divide further into smaller groups

**Comment by michael** [comment]
Hi Melissa!

You are right about the `equal-contrib`. Let's only have them on the top level contrib elements for now.

Would it be sufficient to assume only group authors have affiliations but not their members? Think that would ease the implementation and avoid the edge case of multi-level affiliations.

How would sub-divided members of a group look like? (that could get a bit complicated UI-wise)

**Comment by Melissa37** [comment]
Cool

_Would it be sufficient to assume only group authors have affiliations but not their members? Think that would ease the implementation and avoid the edge case of multi-level affiliations._

You could for simplicity at this point, but we've had members of a group with affiliations and we've had to account for it in our production processes.

_How would sub-divided members of a group look like? (that could get a bit complicated UI-wise)_

We used the role tag:
```
xml
<collab>eLife Editorial Production Group
                        <contrib-group>
<!-- UPDATE: use of role in group authors. If a group author is subdivided into sections or sub-groups, this is indicated using the role tag-->                           
                            <role>Writing group</role>
                            <contrib>
                                <name>
                                    <surname>Shearer</surname>
                                    <given-names>Alistair</given-names>
                                </name>
                                <aff>
                                    <institution>eLife</institution>
                                    <addr-line>
                                        <named-content content-type="city">Cambridge</named-content>
                                    </addr-line>
                                    <country>United Kingdom</country>
                                </aff>
                            </contrib>
                            <contrib>
                                <name>
                                    <surname>Caton</surname>
                                    <given-names>Hannah</given-names>
                                </name>
                                <aff>
                                    <institution>eLife</institution>
                                    <addr-line>
                                        <named-content content-type="city">Cambridge</named-content>
                                    </addr-line>
                                    <country>United Kingdom</country>
                                </aff>
                                <aff>
                                    <institution>eLife Institute</institution>
                                    <addr-line>
                                        <named-content content-type="city">Cambridge</named-content>
                                    </addr-line>
                                    <country>United Kingdom</country>
                                </aff>
                            </contrib>
                        </contrib-group>
```

**Comment by michael** [comment]
I'm not sure I understand the sub-divided members: Would that mean that inside `<collab>` there are multiple `<contrib-group>` elements, each having a role?

**Comment by JGilbert-eLife** [comment]
Hi Michael - just jumping in as Melissa's at a conference today. That's exactly right: multiple contrib-groups within a collab. We had to implement this after encountering groups who wanted to distinguish the members who had contributed to the writing of an article separate from the analysis of their data and the editing.

**Comment by michael** [comment]
Thank you @JGilbert-eLife I will work on and share a UI mockup to reflect all the requirements. Hope this doesn't get to complicated. ;)

**Comment by michael** [comment]
Here's a potential user interface:

![image](https://user-images.githubusercontent.com/2931/31225983-bb3fc17c-a9d4-11e7-9068-8adac29bace7.png)

The support for sub-groups adds quite some UI complexity, and now if we even allow individual affiliations for each member things could get quite unreadable.

What do you think generally of this mockup?

**Comment by javani** [comment]
@michael The example you mentioned is:

```xml
<aff id="aff1">
  <institution content-type="orgname">Settles-Young Research Corporation</institution>
  <institution content-type="orgdiv1">Laboratory of Neural Systems</institution>
  <addr-line content-type="address-street">283 Hawthorne Drive</addr-line>
  <addr-line content-type="complements">Suite 310</addr-line>
  <city>Lexington</city>
  <state>KY</state>
  <postal-code>40503</postal-code>
  <country>USA</country>
  <phone>(859) 273-8543</phone>
  <fax>(859) 299-4683</fax>
  <email>lsy@settles-young.com</email>
  <uri>http://www.settles-young.com</uri>
</aff>
```

The elements `<city>`, `<state>` and `<postal-code>` were included on JATS 1.1 and they are child of `<address-line>`.
So, the correct way to represent the data is:

```xml
<aff id="aff1">
  ...
  <addr-line>
  <city>Lexington</city>
  <state>KY</state>
  <postal-code>40503</postal-code>
  </addr-line>
  <country>USA</country>
  <phone>(859) 273-8543</phone>
  <fax>(859) 299-4683</fax>
  <email>lsy@settles-young.com</email>
  <uri>http://www.settles-young.com</uri>
</aff>
```

On the other hand, the same data could be marked with `<named-content>`. In this case, the structure is valid against JATS v1.0 and 1.1:

```xml
<aff id="aff1">
  ...
  <addr-line>
  <named-content content-type="city">Lexington</named-content>
  <named-content content-type="state">KY</named-content>
  <named-content content-type="postal-code">40503</named-content>
  </addr-line>
  <country>USA</country>
  <phone>(859) 273-8543</phone>
  <fax>(859) 299-4683</fax>
  <email>lsy@settles-young.com</email>
  <uri>http://www.settles-young.com</uri>
</aff>
```
In SciELO we use to related the `<aff>` element with the author using `<xref>`.  The `<aff>` element is part of `<contrib-group>`. We don't use it as a child of  `<contrib>` as described by Melissa.

**Comment by fabiobatalha** [comment]
@michael 

Here at SciELO we deal with contribs all inside one contrib-group element.

The contrib-type attribute in the contrib element is enough to describe the "persona" which could be one of (author, compiler, editor, translator).

I believe the described approach in the previous messages still allow us to keep using this more simplified data model. 

Regarding the aff elements, all them are handled outside the contrib-group and contrib to avoid duplication of data.

**Comment by michael** [comment]
Hey @javani -in Green JATS 1.1 city,postal-code,state are allowed as childs of aff:

https://jats.nlm.nih.gov/archiving/tag-library/1.1/element/aff.html

I'd like to avoid nesting when possible.. so add-line should have no sub-elements ideally. But using named-content instead of city,postal-code,state would be fine, tagging is just a bit more verbose. Just wonder why is it important to also conform to JATS 1.0?

@fabiobatalha yes that could be another strategy. Just thought having them in separate sections make it easier for the user rather than choosing the type for each contrib? Up for discussion.

**Comment by javani** [comment]
@michael you are right, sorry! 
About the JATS 1.0, in SciELO the both versions are valide.
About the affiliation,  we can received it marked inside contrib-group or in article-meta, so have it in separated section sounds fine to me.

**Comment by fabiobatalha** [comment]
@michael @javani 

For texture I believe we don't need to support both 1.0 and 1.1. In the near future SciELO PS will also accept only JATS 1.1.

Yes Michael it is easier for the user to select the contrib-group-type only in the group context, but in the other side, it brings to us the complexity of deal with more than one contrib-group.

It is just a matter to decide with complexity we wants to deal with at this moment.

I will discuss it internally to give a more consistent decision.

**Comment by Melissa37** [comment]
Re the mock up - I think this looks good and would work. Thanks! I worry about not user testing though...but I think as long as the options make themselves available as an author adds the group (ie subgroup only appears after group has been added) it should make sense....
Thanks!

**Comment by fabiobatalha** [comment]
@michael @Melissa37 

Our decision regarding this and other issues is: Every specifications are ok as long as we are able to derivate the SciELO PS Style, from the Texture XML Style.

Regarding this specific issue, I believe we can easily produce the SciELO Style, so these requirements are ok for us. I just think we need to find a good measure for complexity/requirements,  timeline and resources for this new round of development.

**Comment by Melissa37** [comment]
@michael @fabiobatalha I agree that soon would be a good time to talk about "...find a good measure for complexity/requirements, timeline and resources for this new round of development."

cheers
M

**Comment by michael** [comment]
Support for affiliations editing is scheduled for the next alpha release (end of year). What is important is to have confidence that the requirements hold, so we don't have to implement twice. 

I'd suggest that unless there are objections we start defining the model as described above (including group authors and equal contrib) but only implement the UI for regular contrib elements first. Gives us some more time to discuss UI/UX for group authors etc.

@Melissa37 We could plan for user testing of new features at the beginning of next year at eLife?

**Comment by pigeonm** [comment]
Hi, 
Group authors and equal-contrib :

On Erudit, our group authors are not as elaborate as the cases described here.

Publishing almost exclusively journals in the humanities and social sciences, the articles you can find on Érudit are written by few authors. Also, group authors are rare (but existing) cases and the use cases where we have to tag members of a group is even rarer. In any case, these groups of authors do not represent complex cases (we only have flat groups).

In terms of contributions, we have only few journals that indicate the authors' contribution percentage and as I just describe, these cases are not complexes. 

So, on that subject, your needs are more complexes than ours, so they cover them.

**Comment by Melissa37** [comment]
@michael re user testing at eLife - can we talk about that with Giuliano?

I sign off on this too, with the caveat that it's not JATS4R yet and the JATS4R working group may change this.

**Comment by michael** [comment]
Thank you everyone for the fruitful discussions here. I've consolidated all the specification work into a single document: https://github.com/substance/texture/blob/master/docs/JATS4M.md

I will close this issue now, as I think we created a good base. Please open new issues anytime if you have questions, suggestions how to improve the current spec.
