### ISSUE TITLE
table of content not coming up

### ISSUE THREAD

**Issue by vishnukpkp** [substance/texture#278]
all headings are removed. Is it considered in next release or a new bug

**Comment by oliver----** [comment]
This is a regression. We will fix it ASAP

**Comment by vishnukpkp** [comment]
thank you

**Comment by oliver----** [comment]
Thx for reporting!

**Comment by michael** [comment]
Fixed via https://github.com/substance/texture/commit/83cfb23f6d0428d20cd6d0df4e06a65d61ea7841.
