### ISSUE TITLE
Some articles cannot be reopened after saving in recent build

### ISSUE THREAD

**Issue by axfelix** [substance/texture#279]
Hi guys,

I built the version of Texture that caused this right after you fixed importing footnotes with disp-quote, it may have been fixed since, but that build is exporting documents that it then fails to import. I opened this document:

[document (34).xml.txt](https://github.com/substance/texture/files/1360876/document.34.xml.txt)

then made a trivial change to body text, saved it, and tried to open this, which throws errors about missing pub-id values.

[2-99Z_Article Text-6-1-2-20171005.xml.txt](https://github.com/substance/texture/files/1360878/2-99Z_Article.Text-6-1-2-20171005.xml.txt)

**Comment by axfelix** [comment]
ping

**Comment by quii** [comment]
Think i am suffering from the same problem. Using latest release i have a web page which takes the sample doc, lets a user save and when the updated document is returned to the UI it complains it cannot load the document.

**Comment by michael** [comment]
We will check this asap. It's likely that there are some errors in the export transformers, which we haven't tested throughly as there are still unclear specifications for many elements.

So saving will stabilise as we are completing the features for reference editing, affiliation editing, and article metadata editing etc.

Can't provide a quick fix but the reported error will be resolved with the next release.

**Comment by axfelix** [comment]
Hi guys,

Can we get a timeline on the next release? We were OK with waiting for the fig import fix, but this is a long time for such a major bug to be open...

**Comment by michael** [comment]
I'm pretty sure there will be other export errors as well. :/ This is mainly because some features were just prototyped and did not have a proper spec. And also we haven't setup tests for export. We will be in a much better place after the next round of features is in. Think it doesn't give us much to try stabilise Alpha 3, since so many thing needed for production are missing anyways.

We are still in `not-yet-ready-for-use` state. Doing our best to change that!

**Comment by axfelix** [comment]
OK, understood -- I agree it's not a great use of time to backport fixes to Alpha 3. Is Alpha 4 still expected by December?

**Comment by michael** [comment]
End of December yeah. Lots to do: Ref + affiliations editing, fig (including file upload), table-wrap, and lists.

**Comment by michael** [comment]
Alpha 4 shouldn't break on save anymore in these cases. For content not conforming to JATS4M you should see a clear error. Closing this issue.
