### ISSUE TITLE
Invalid Journal - Errors

### ISSUE THREAD

**Issue by praveennair** [substance/texture#280]
Dear Team,

First of all thanks much for the beautiful tool. I recently download it using npm. When I am trying to process a valid Journal XML the editor unable to parse it.

**Instance 1:**
```
<fig id="F1" position="float" orientation="portrait">
<label>Figure 1</label>
<caption>
<title>Patients’ pre-operative concerns</title>
</caption>
<graphic xlink:href="cnp_v11_n3_9036_0001.jpg" position="float" orientation="portrait"/>
</fig>
```

The above structure is JATS valid, however, the structure defined in the skeleton XML (texture source code) says label is not valid and also a `<p>` tag necessary inside the title element.

**Instance 2:**
In the contributors section (affiliation) and reference section string-name is not supporting and when I replace it with `name` then it works. Again string-name is valid in both places as per NLM JATS standards.
```
<string-name name-style="western">
  <surname>...</surname>
  <given-names>...</given-names>
</string-name>
```

**Instance 3:**
`mixed-citation` is not working and the code is supporting only element-citation for references.

Also, how easily this code can make it supportive to BITS (DTD for books)?

Thanks in advance,
Praveen

**Comment by michael** [comment]
Hey @praveennair!

Thanks for reporting and sorry for the late reply. With Texture we want to follow a stricter model for more consistent tagging (see JATS4R group and Texture issues tagged "requirements"). Another reason is that we can't provide visual user interfaces for any possible JATS tagging style.

Instance 1:
We always want to have a p element so there's a placeholder for editing. However think it makes sense to add a transformer to expand it on import an drop empty p's on export.

Instance2:
We are working on that. However we will not support string-name and allow only surename, given-names tags. See: https://github.com/substance/texture/issues/239

Instance3:
Also here we will go for structured references and only support `<element-citation>` in Texture. See: #238

**Comment by praveennair** [comment]
Dear @michael,

Thanks for your reply.

We are currently using a CKEditor based implementation for editing and managing XML content. We mostly process books using BITS.dtd. I am very much impressed by the work you guys did here and planning to create solution for Books as well by doing some tweaks in the texture code base. 

Hope this is fine.

Thanks,
Praveen

**Comment by michael** [comment]
@praveennair sure! Please keep me updated of your work, maybe there's potential to make Texture support BITS out of the box in the future.

**Comment by michael** [comment]
I think we can close this. @praveennair please verify the latest spec and create an issue if a requirement isn't met.

JATS4M Spec: https://github.com/substance/dar/blob/master/specs/JATS4M.md
