### ISSUE TITLE
JATS4M-led initiative for a high-quality metadata database

### ISSUE THREAD

**Issue by michael** [substance/texture#284]
This is a proposal in response to current problems with metadata curation. Focus for now is on references but we could do the same for affiliations, persons (ORCID) etc.

According to our discussions (#276, #238) there's significant problems with the reuse of metadata.

- Bad quality of metadata in online databases (Crossref, PubMedCentral,...)
- Manually edited references can't be reused in the future (no way to directly feed them back into those databases)

What if we setup a shared database for Texture users to help get this right in the future?

- allow storing annotations for text fields (e.g. title with subscript, superscript)
- save data right from the Texture interface back into the DB (if authorised to do so)
- next time the same DOI is used, no more manual editing is needed
- ability to import incomplete data (e.g. from Crossref/PubMed), clean it up, save in the db and eventually propose that improved data to be fed back to Crossref/PubMed

I thought that our smaller number of Texture organisations (Erudit, SciELO, PKP, eLife) could run such a database together and ensure quality standards, so we can really rely on the data when we publish articles. Ideally, we could do this in collaboration with existing services instead of running and maintaining our own infrastructure. @mfenner would DataCite be interested in providing such a service?

This proposal should still be considered a temporary hack, until the same workflows could be achieved through a global service (Crossref).

@Melissa37, @fabiobatalha, @axfelix, @giotta what do you think? Good idea / bad idea?

**Comment by axfelix** [comment]
It's a good idea -- meTypeset had this same plan at one point -- but it's proven very difficult to guarantee uptake and I'm a little concerned about scope creep.

**Comment by michael** [comment]
May increase the scope a bit. Just it really hurts to know that a carefully crafted element-citation can't be saved for the next time it's going to be used. I think we could solve a real problem with today's workflows by being able to "save" a record for reuse right from the Texture interface.

I'd imagine a very simple key/value db that stores JATS element-citation records per DOI. No search/etc. capabilities. We are already doing the hard work of coming up with a strict spec for element citations. Based on that, we could really benefit from a database that provides that high quality of metadata.

**Comment by axfelix** [comment]
Yeah, I think the main problem is that the number of organizations that have successfully taken on the role of known-good citation provider is very small and it's very difficult to take on that role without being folded in to the existing infrastructure; I'd actually feel better about it if we were posting back to e.g. CrossRef somehow.

**Comment by mfenner** [comment]
@michael I wouldn't do this if I were you. It is a tremendous effort, and the main reason that Crossref metadata can be of bad quality is the scale (90 million Crossref DOis, 10 million DataCite DOIs, many other works without DOI).

I would be very interested in "crowdsourcing of DataCite metadata". We are in the middle of relaunching our DOI registration service, and it will very soon be much easier to update metadata, e.g. fix a typo in a title via a form or JSON API call rather than uploading the whole XML record.

The tricky part is the authority to update metadata. When I thought about this two weeks ago, I wanted to allow authors to update the metadata of works that include their ORCID ID (e.g. add funding info). A more generic crowdsourcing effort would be more difficult to implement.

I would certainly be interested to do a pilot of this approach with one or a few interested DataCite repositories.

**Comment by michael** [comment]
I hear you, Martin! Wouldn't want to create another island solution...

I agree when we want to unlock this for authors, things become tricky with regards to permissions. But this can wait I think. If we only allow this in publisher setups, where certain people are authorized to directly write to DataCite this would be a great start and enable reuse of carefully edited bibliographic records.

If we wanted to integrate with the DataCite database we'd need the following things:

- ability to write annotated text (e.g. in article title, what JATS elements are really used here, @Melissa37)
- ability to post an element-citation XML string to a service for updating (as that is what we have in Texture editor land)

**Comment by mfenner** [comment]
@michael I suggest to think about more whether this can be implemented in a reasonable way. I am visiting Crossref on Friday and can bring this up, specifically whether this aligns with https://www.crossref.org/services/event-data/, a joint project we do with them.

As the very first step I can implement the conversion in the other direction, i.e. from JATS element-citation to DataCite XML, bibtex, and the other formats we support in our metadata conversion.

**Comment by michael** [comment]
Would be awesome if you could discuss that with the Crossref folks. The argument "there's bad metadata on Crossref" could be elegantly countered by "here's how you can fix it". :)

We don't need to rush on this, so many other things to do on our end. Just wish we could help with Texture fixing some of the real trouble causes long-term instead of investing into treating symptoms short-term. What we are discussing for references could also be applied for contributors and affiliations (reading and writing to ORCID?).

Many thanks for your help and time Martin!

**Comment by mfenner** [comment]
Cool. Will give an update next week.

**Comment by Melissa37** [comment]
This is an interesting idea and love your enthusiasm :-) but I would not be keen to volunteer eLife to help manage this!
The reason's I can see it not working (other than those already suggested by Martin) are that those who are crafting their references in Texture are unlikely to be the authors of those papers, so you are 2 steps removed from having the authority to post this change back into the databases - you are not the publisher or the author, but a watcher in the eco system, so I cannot see how Crossref/PubMed could accept that.

Also, Crossref and PubMed purposefully remove mark up and don't want it. That is a lot of what people are crafting in their reference lists - adding back in the gene name italics and the super and subscripts. This is important information, but we need to approach PubMed and Crossref and ask why they don't want it or will strip it....then go back to the publishers to ask to provide it...

Ultimately, if there is a DOI in a reference list, the reader (human or machine) can find that content. eLife would be much more interested in supporting tools to show what references are open access content :-)

**Comment by michael** [comment]
@Melissa37 there's a lot we can do I think. Oliver and I had a broader discussion today on how we could set the course for the future to allow true reusability of carefully curated data.

We think we need to slowly move away from having records trapped somewhere inside the XML.

Instead we should think of global disambiguated concepts. E.g. each person / affiliation / reference should be given an unique identifier (even if no DOI/ORCID is assigned yet) so we can build a high-quality database of entities. Then we will be able to pick an existing affiliation from the database rather than copying all that data over into each article, even when the exact same affiliation is used. The same is true for authors and references.

We'd like to just prepare Texture to be ready for that, by using an EntityDB abstraction in the implementation. First we will just use what is in the XML (same as it is now), but later we can plug in external entity databases. We think of this as a multi-layer system. E.g. having:

1) Local Entity DB (the article - may have diverging data, so you can make article specific fixes)
2) eLife Entity DB (curated and shared by eLife, eLife editors, Stencila authors with moderation?)
3) CrossRef Entity DB (bigger repository, that collects multiple sources, newly proposed versions need to be explicitly accepted by a moderator -> much like wikipedia handles change requests to a page

@mfenner We will model and implement a local (article-level) entity db first. You can then use this spec to implement it for DataCite (and discuss with Crossref). We also decided to move away from JATS as a the serialisation for references in Texture, we rather have it represented as JSON just it follows the same schema that we define for Texture references.

@Melissa37 agree that we must allow basic annotations for certain fields (such as article title). Can be HTML (strong, em) but must be easily mappable to JATS (bold, italic).

**Comment by Melissa37** [comment]
@michael sounds good. Agree with you! Especially for repeat authors not wanting to re-input their details into Texture :-)

**Comment by michael** [comment]
We won't do that, at least not in the near future. Instead, we'll connect CrossRef/etc. to prefill reference forms.
