### ISSUE TITLE
Entity Editor User Interface

### ISSUE THREAD

**Issue by michael** [substance/texture#288]
We are moving towards manipulating entities (as part of a knowledge graph) in Texture. This allows us to generate user interfaces based on a schema. This is highly inspired by the innovate  Freebase.com interface (which was bought by Google and shut down).

For instance editing a Journal Citation looks like so:

![image](https://user-images.githubusercontent.com/2931/32776323-76604176-c932-11e7-8158-123ac563fa78.png)

Relationships (e.g. authors) are edited by opening an Entity Selector dialog:

![image](https://user-images.githubusercontent.com/2931/32776353-8dcab008-c932-11e7-8283-b40dcad3e616.png)

You can edit any entity in place:

![image](https://user-images.githubusercontent.com/2931/32776394-b307669a-c932-11e7-8861-a25b88a3165d.png)

You can create new entities when necessary:

![image](https://user-images.githubusercontent.com/2931/32776374-a02ef36c-c932-11e7-9486-185e298dceb0.png)

**Comment by oliver----** [comment]
Looking great 👍

**Comment by Melissa37** [comment]
Looks cool! Only feedback from eLife - needs to work in mobile

**Comment by michael** [comment]
Is mobile editing really a high priority? We definitely have mobile in mind in designing the interfaces, but we thought in the case of Texture most users of a production team would sit on a desktop with full keyboard etc?

**Comment by gmaciocci** [comment]
@michael We're looking for an editor that will fit within an otherwise mobile-first user journey where authors, editors and reviewers will be able to interact with a manuscript and each other in a device-agnostic fashion. While I don't believe anyone will be spending much time editing large swathes of a manuscript on a phone any time soon, but amending metadata, correcting typos, responding to vendor and reviewer feedback carrying out consultations and tracking a paper's progress are perfectly viable mobile use cases.

**Comment by michael** [comment]
@gmaciocci thanks for your input. Great suggestions!

We have two layers here:

- Entity editing interfaces (persons, person-groups, organisations, bib entries): Those are completely separate from Texture and don't even operate on the XML directly. We want other orgs/apps to be able to embed those interfaces independently. There's no problem with mobile here.
- XML-specific metadata editing interfaces (e.g. publication history, copyright statement etc): those are more tightly tied to the article and to the XML. Also there's a shared editing undo/redo between the main document and those parts. As you said, we need to make sure these components also work in a mobile-layout (single column).

What needs to be done is making the Substance library ready for mobile editing. There are mobile-related quirks with contenteditable, which we haven't had time to address yet. We would need to do a dedicated iteration here to get rid of the bugs and optimize contextual toolbars for mobile etc.

I think it's a matter of prioritisation. I understand we need to make design considerations regarding mobile from the beginning. Still I would work towards a functional Texture desktop editor first, and ship a mobile update a few months later?

**Comment by michael** [comment]
... unless we reprioritise, which we could do, just needs to be aligned with the other consortium members.

**Comment by michael** [comment]
For documentation, the underlying data looks like this:

```js
entityDb.create({
  id: 'book-citation-1',
  type: 'book-citation',
  authors: ['person-1'],
  editors: ['person-1'],
  chapterTitle: '<strong>Tobacco</strong> use',
  source: 'Clinical methods: the history, physical, and laboratory examinations',
  publisherLoc: 'Stoneham (MA)',
  publisherName: 'Butterworth Publishers',
  year: '1990',
  month: '10',
  day: '5',
  fpage: '214',
  lpage: '216',
  pageRange: '214-216'
})
// Person
entityDb.create({
  id: 'person-1',
  type: 'person',
  givenNames: 'John',
  surname: 'Smith'
})
```

**Comment by michael** [comment]
First iteration done.

**Comment by michael** [comment]
First working iteration in place, we'll iterate on the interface using mockups and implement in the coming versions.
