### ISSUE TITLE
EntitySelector Widget

### ISSUE THREAD

**Issue by michael** [substance/texture#298]
We need a flexible way for selecting and ad-hoc creating entities to allow a smooth user experience. I'd suggest a slightly higher-level specialised component, that depends on entityDB, and use registry of entity renderers internally. May not work for other cases, but think it's central to have a tailored widget for the entity editing usecase first.

```js
$$(EntitySelector, {
  placeholder: 'Select a person or group',
  targetTypes: ['person', 'person-group'],
  entityDb,
  showCreateDialog: true,
  limit: 50
})
.on('selected', this._onSelected)
.on('create', this._onCreate)
```

So at first you'd see this:

![image](https://user-images.githubusercontent.com/2931/32980473-39cc4a56-cc67-11e7-8252-6ba6281c2c24.png)

By putting the cursor inside, entries are shown and can be selected with the arrow keys, or mouse.

![image](https://user-images.githubusercontent.com/2931/32980677-47656068-cc6b-11e7-9c61-13aca3c7482f.png)

If no entries are found an optional create dialog is shown that can be used for creation and pre populating form fields. It would look like so:

![image](https://user-images.githubusercontent.com/2931/32980506-c40378f2-cc67-11e7-888e-5a3196f63972.png)

This only triggers an event `this.emit('create', targetType)` and the user must handle it, e.g. to split up the string into surname, given names and pre-populate the form-fields of the create dialog.

Requirements:

- [ ] partial matches should be displayed
- [ ] use type="search" for input field, so it can be cleared with a click
- [ ] show option list on focus (immediately when you click into the filter input field)
- [ ] only show `limit` entries at once (we will need this once we have a large db, and async query for target types)

**Comment by Melissa37** [comment]
I'm not sure whether I am reading the screenshots correctly, but I'd be concerned about someone typing in "Max" and getting full names to select from (based on the size of the database these names are coming from this could go seriously wrong) and it looks not to be that clear what to do if they are not one of the names suggested. I think I would prefer that they type in a name and then the database says is this you? and auto-populates the rest of their metadata based on their name (such as affiliations)....or better yet, ORCID login pulls in all their data and they are authenticating themself from the get-go.

Two researchers can have the same name (the whole point of ORCID) so you could have two authors using and editing the metadata associated with the same name in your database?

Also, is the group coming up in that list? and why?


I wonder whether some input from others is required before building out this idea too far? Some user testing is vital?

Thanks!

**Comment by michael** [comment]
@Melissa37 we are aware that there could be different persons or orgs with the same name. We can use the ORCID to disambiguate them (if available). Like this:

![image](https://user-images.githubusercontent.com/2931/33028043-04dd6a32-ce15-11e7-9201-3d17ccf3a273.png)

However, we will also have situations where persons have no ORCID yet, thus everything in our database gets a uuid to uniquely identifying. Since each person can have affiliations we can use those to disambiguate person that share the same name.

Group as displayed in the mockup corresponds to the group author concept of JATS. I thought of generalising this and call it "Organisation". Then an author could be either a person or an org. Would this be an option instead of introducing "group author" as a separate entity type?

I need a week or two of more time, then I could provide you a prototype for testing and we could figure out what needs work.

**Comment by Melissa37** [comment]
Hi there

Sorry for getting confused - I just discussed with Giuliano and he explained you are just demonstrating the patterns and the database structure for entities, not necessarily the UX and database you will use for the context of author names and adding authors.

**Comment by michael** [comment]
No worries, let's aim for a quick-and dirty prototype that you can try out and comment on.

Also we want to schedule user testing of particular topics based on the upcoming Alpha 4 release:

- citation editing (all required pub types)
- authors and affiliation editing
- figure insertion (upload, replace image etc)

I suppose some time in January this could happen. Would eLife be able to join that? Does not need to be a complex test script. We just want to gather initial feedback on the newly added features.

**Comment by Melissa37** [comment]
Great, thanks! Nick (UX) from eLife is very happy to be involved.

**Comment by michael** [comment]
We have a working implementation for an EntitySelector now. We'll improve it as we move forward with the UI.
