### ISSUE TITLE
Improve Entity editing UI

### ISSUE THREAD

**Issue by michael** [substance/texture#300]
The following tasks should be performed next:

- [x] style according to mockups #287 
- [x] Save and cancel button should be in a fixed place (always visible at bottom of the modal, only content is scrollable)
- [x] Implement EntitySelector widget #298 (will provide a sketch implementation first)

@Integral would love to get your help on this, starting around middle of the week. These tasks shouldn't be too time consuming, but let me know how much time (hours) you have available this week.

**Comment by Integral** [comment]
@michael i would love to join you
I could start in Thursday evening (offline)
and work in Friday-Saturday-Sunday also

**Comment by michael** [comment]
Sounds good! I will refine the issue and work on a good foundation for you to take over.
