### ISSUE TITLE
Allow TAB-ing through form fields in Entity Editor

### ISSUE THREAD

**Issue by michael** [substance/texture#313]
Currently not possible. We need a way to make RichTextInput react to TAB in a proper way.

**Comment by michael** [comment]
We generally have limited editing capabilites in the modal dialog, since it's spawned from within a surface.

@oliver---- should we somehow disable parent surfaces while we are in a modal?

**Comment by oliver----** [comment]
I think that is a different question to this issue.

It should be possible to receive key events on the Modal level and stop propagation. As long a cursor is inside a input field this should be working already. Otherwise it might be necessary to have a hidden input so that key events get received.

**Comment by michael** [comment]
When cursor is in an input field currently we don't receive events like cmd+a for select all, or tab, as these are handled by the surface.

Another way to solve this would be injecting the modal outside of the surface. This would require some kind of app state switch to bring up the dialog and pass in props on app level. Not sure what's the best way to go.

**Comment by oliver----** [comment]
> When cursor is in an input field currently we don't receive events like cmd+a for select all, or tab, as these are handled by the surface. 

Isn't that just because you do not have a keydown listener on the modal itselft.
If this bubbles through to the surface, the surface will handle them.
I suppose it wouldn't if you stopped propagation at modal level.

**Comment by michael** [comment]
Will try.

**Comment by michael** [comment]
Fixed it with the approach you described.
