### ISSUE TITLE
Deal with removal of references from the bibliography

### ISSUE THREAD

**Issue by michael** [substance/texture#324]
Currently if you remove a reference from the bibliography:

- xref elements still point to the invalid references and can't be edited
- labels are not regenerated

**Comment by michael** [comment]
Desired solution: Bring up prompt to ask "If you delete this reference, it will also be removed from 5 citations. Are you sure?"

And then remove the xref targets.

Still we should also be able to handle cases where an xref points to a not existing reference. maybe such xrefs should be underlined red, and when click on it, you can untoggle the target that can't be found.

**Comment by michael** [comment]
Something like that:

![image](https://user-images.githubusercontent.com/2931/35106639-02a511b0-fc6f-11e7-873b-10895e66e83d.png)

But this should be a second step I think. First implement the prompt on deleting a reference from the reference list.

**Comment by Melissa37** [comment]
Small comment on the message, could it read something like this instead?
"If you delete this reference, 5 citations in the text will be removed. Are you sure?"

**Comment by michael** [comment]
@Melissa37 the citation elements (xrefs) will actually not be removed, only the targets. E.g. if you have [2,3] and you delete 3, then you'll get [2] in this place. If you then also remove 2 you'll get [???]. 

I'd not remove the xrefs as we may end up with weird uncontrolled whitespace etc. Better fix those things explicitly.

**Comment by michael** [comment]
@Integral the following tasks need to be done:

1) Deleting a reference brings up the prompt and updates the affected xref elements
2) Assign a non-existing target in kitchen_sink for one of the xrefs and update EditXrefTool so that these warnings are displayed. You'll then be able to untoggle the missing target.

Let me know if there are questions.

**Comment by michael** [comment]
Mostly solved, will create a separate issue for dealing with invalid xrefs.
