### ISSUE TITLE
Issues when saving the XML - heading title missing, nested sections

### ISSUE THREAD

**Issue by soarecostin** [substance/texture#331]
Dear Team,

First of all let me congratulate you for such a great project! I am already finding it extremely useful and am looking forward to the Alpha 4 release.

I have found an issue that is present on both the demo url http://cdn.substance.io/texture-alpha-3/ and on the latest build I tried locally. I haven't found it as already reported - sorry if I missed it.

Once I hit save, the generated XML that is is outputted into the console is missing the section heading titles and the closing `</sec>` tags in the right place, resulting in multiple nested sections.

For example, the output XML is:

```
<sec id="heading-1" level="1">
	<p id="p-2"><italic id="italic-1">Microsoft Word</italic>'s dominance as an authoring tool creates....</p>
	....
	<sec id="heading-2" level="1">
		<p id="p-5">Texture is a WYSIWYG editor app...</p>
		...
		<sec id="heading-3" level="2">
			<p id="p-8">Texture is open source software built on top of</p>
			...
			<sec id="heading-4" level="2">
				<p id="p-16">At this initial stage, Texture is being developed to
				...
				[...]
			</sec>
		</sec>
	</sec>
</sec>
```

Where it should be something like

```
<sec id="heading-1" level="1">
	<title>Introduction</title>
	<p id="p-2"><italic id="italic-1">Microsoft Word</italic>'s dominance as an authoring tool creates....</p>
	....
</sec>
<sec id="heading-2" level="1">
	<title>Introducing Texture</title>
	<p id="p-5">Texture is a WYSIWYG editor app...</p>
	...
</sec>
...
```

Sorry if I've missed anything, but I've tried in various ways and I get the same issue the same time - basically opening a JATS XML for editing and then saving it, the titles are missing and sections are messed up because of this issue.

Thanks you for your time,
Costin

**Comment by michael** [comment]
Thank you for reporting! We will make sure to take care of this error for the Alpha 4 release.

**Comment by michael** [comment]
I can confirm this error, we are working on a fix right now.

**Comment by michael** [comment]
Solved in Alpha 4 (to be ready in next couple of hours).
