### ISSUE TITLE
InsertTableTool

### ISSUE THREAD

**Issue by michael** [substance/texture#342]
We need a way to create a table from the UI. Let's do a quick and dirty solution for now and provide an improved visual dialog later.

It can be implemented as a regular toggle tool. However when the command is executed we can just request a native prompt window like so:

```js
let columns = window.prompt("How many columns should your table have?")
```

Let's start with a default row count of 3.

@Integral you want to take that one?

**Comment by Integral** [comment]
Yes, after entity selector

**Comment by Integral** [comment]
@michael pls checkout #345
