### ISSUE TITLE
Deal with invalid xrefs

### ISSUE THREAD

**Issue by michael** [substance/texture#352]
If an xref target points to an id that does not exist, we need to somehow handle this and allow the user to fix the error. A dialog such as this one could be displayed

![image](https://user-images.githubusercontent.com/2931/35592527-85c23436-060d-11e8-9eb0-d1190b517732.png)

**Comment by Integral** [comment]
Maybe we should add `[3, ???]`, so user can expect already that 3 is ok and second reference is broken somehow

**Comment by Melissa37** [comment]
Sorry if being thick, but is this in the reference list but there is no citation in the text?

**Comment by michael** [comment]
No this is the edit xref dialog and there is a `ref id` referenced that does not exist.

Much like:
`<xref rid="r1, r9891223">` 

This shouldn't actually happen with correct XML, but we just want to provide a way to fix such broken links.

**Comment by Integral** [comment]
@Melissa37 It is in xref tool, not in the reference list (e.g. not in the back matter), there should be `[???]`or `[!!!]` for invalid xrefs.
