### ISSUE TITLE
List support

### ISSUE THREAD

**Issue by michael** [substance/texture#361]
We need to do a round of specification first. Here's a proposal:

### `list`

```
list-item
```

Example for bullet list:

```xml
<list list-type="bullet">
  <list-item>
    <p>item 1</p>
  </list-item>
  <list-item>
    <list list-type="bullet">
      <list-item>
        <p>item 1.1</p>
      </list-item>
    </list>
  </list-item>
</list>
```

### `list-item`

```
(list | p)?
```

*NOTE: We allow only one list or paragraph as a child.*

### Questions:

- Is it ok to only support text and inline content in lists?
   - it is problematic and not recommended to put block elements (such as tables or figures etc. into lists), are there any legitimate use-cases for this?
- Should it be possible to mix bullet lists with numbered lists (like level 1 numbered, level 2 bullet"? etc)
  - Would be faster to implement pure (numbered or bullet) lists.
  - If we went that route, we'd normalise all lists on import to be either bullet or numbered
- do we need to support other list types as described here: https://jats.nlm.nih.gov/archiving/tag-library/1.1/attribute/list-type.html

**Comment by Melissa37** [comment]
Is it ok to only support text and inline content in lists? **I think so**
it is problematic and not recommended to put block elements (such as tables or figures etc. into lists), are there any legitimate use-cases for this? **I cannot think of a use case right now, and for launch I suggest keep it simple**
Should it be possible to mix bullet lists with numbered lists (like level 1 numbered, level 2 bullet"? etc) **YES**
Would be faster to implement pure (numbered or bullet) lists.
If we went that route, we'd normalise all lists on import to be either bullet or numbered
do we need to support other list types as described here: https://jats.nlm.nih.gov/archiving/tag-library/1.1/attribute/list-type.html **Authors love the flexibility to chose their own option, and publishers more often than not will have a house style as per what list "format" is used (numbers, Roman numerals, bullets, upper case, lower case a/A, a/B etc).**

I think eLife allows 3 levels of sub list.

**Comment by fabiobatalha** [comment]
We expect the use of the above kinds of lists.

- ordered lists
- unordered lists
- lists of relations

**Ordered list**

- decimal digit
- capital letters
- tiny letters
- roman numbers (capital letters)
- roman numbers (tiny letters)

**Unordered list**

- square [example](https://www.erudit.org/fr/revues/cqd/2013-v42-n2-cqd01010/1020609ar/#pa46)
- circle
- bullett [example](https://www.erudit.org/fr/revues/recma/2014-n332-recma01376/1024827ar/#pa9)
- hyphen [exanple](https://www.erudit.org/fr/revues/memoires/2011-v3-n1-memoires1830163/1007572ar/#pa9)
- no sign [example](https://www.erudit.org/fr/revues/meta/2010-v55-n4-meta4003/045680ar/)

**List of relations**

- [example](https://www.erudit.org/fr/revues/ae/2011-v87-n2-ae1830643/1007618ar/#pa57)

Any kind list of list can have another imbricated list of any kind as well.

**Comment by michael** [comment]
How does the tagging look like for "list of relations"?

**Comment by fabiobatalha** [comment]
I'm not sure how we can tag it in JATS.

Maybe allowing the use of (label ?, title ?) inside list-item.

```xml
<list>
    <list-item>
        <label>Modèle [1]</label>
        <p>content</p>
    </list-item>
    <list-item>
        <label>Modèle [2]</label>
        <p>content</p>
    </list-item>
</list>
```
We normally handle this structure as a table so it is not mandatory to represent it as lists.

**Comment by michael** [comment]
I'd go for tables then, adding labels to a list item will make the UX worse and also complicates the implementation.

Will we need to set the list's bullet or number type per list, or is this more an article-specific setting? In other words, do articles sometimes use roman numbers in one list and capital letters in another?

**Comment by fabiobatalha** [comment]
I think there is no pattern on that.

I would not say one author uses exclusively roman or letters in one unique article.

One thing that surely should happen is an article with unordered and ordered lists.

**Comment by michael** [comment]
Decision Substance Consortium:

- one bullet type for each level of the list
- consider ability to [link numbering to a previous list](https://jats.nlm.nih.gov/archiving/tag-library/1.1/attribute/continued-from.html)
- only support text inside a list-item (+ inline content such as math, xrefs etc.)

**Comment by oliver----** [comment]
A first version without the ability to continue numbering has been implemented.
