### ISSUE TITLE
Improve RichTextInput

### ISSUE THREAD

**Issue by michael** [substance/texture#365]
There are some issues we should address for the RichTextInput:

- tabbing does not work
- when multiple richtext inputs are used multiple overlays are displayed (we need need an EditorManager on top level)

**Comment by Melissa37** [comment]
There is a JATS4R recommendation for permissions, which includes permissions for assets:

https://jats4r.org/permissions

Copyright is not required, but <license> or <ali:license_ref> are.
We use <copyright-statement>, <copyright-year>, <copyright-holder> and think they should be optional too.
Thanks!

**Comment by oliver----** [comment]
Closing this because this component does not exist. 
The comment about permissions does not belong here, but this has been captured in another issue: #479
