### ISSUE TITLE
Add Abstract, References and Footnotes to Table Of Contents

### ISSUE THREAD

**Issue by michael** [substance/texture#381]
Often you want to quickly jump to the reference list, so we should add that to the TOC. Let's use the following structure:

- Abstract (display if abstract element can be found)
- Section 1
  - Section 1.1
- Section N
- ...
- References (display if more than one ref-list > ref can be found)
- Footnotes (display if more than one fn-group > fn can be found)

**Comment by michael** [comment]
Implementation Note: `TOCProvider` must be adjusted to consider the other elements.

**Comment by Integral** [comment]
@michael pls take a look at #391
However I've discovered few problems: 
1) we can't currently translate anything inside TOCProvider
2) we don't have an access to reference manager so we don't know which ref is going first
to fix that problems we need to pass context somehow inside TOCProvider

**Comment by michael** [comment]
Done! Thank you @Integral, great job.
