### ISSUE TITLE
Not able to integrate Texture using the samples

### ISSUE THREAD

**Issue by fabiobatalha** [substance/texture#382]
I'm trying to integrate Texture to our test environment, but without success.

I'm not sure if I'm doing something wrong while attempting to change the following predefined parameters.

```
    let archiveId = getQueryStringParam('archive') || 'kitchen-sink'
    let storageType = getQueryStringParam('storage') || 'vfs'
    let storageUrl = getQueryStringParam('storageUrl') || '/archives'
```

**storage**
Basically I'm ignoring the use of the VFS as storage passing a parameter in the query string (storage=other)

**storageUrl**

full path to the storage folder, eg: storageUrl=/files/packages/63/27&archive=63278a8a-2a5d-4171-b969-26bc56ab8d03

**archive**
Name of the directory inside the storageUrl whiting the manifest.xml and manuscript.xml, eg: archive=63278a8a-2a5d-4171-b969-26bc56ab8d03

The url is something like this.

http://localhost:6543/editor?storageUrl=/files/packages/63/27&archive=63278a8a-2a5d-4171-b969-26bc56ab8d03&storage=other

As you can see in images below, the files are available at the given urls.

**manuscript.xml**

![screenshot from 2018-02-13 16-21-42](https://user-images.githubusercontent.com/504142/36174358-15cbdcb8-10da-11e8-8b32-e8804f1b8391.png)

**manifest.xml**

![screenshot from 2018-02-13 16-22-04](https://user-images.githubusercontent.com/504142/36174347-1066ff64-10da-11e8-8857-92e5550236ae.png)

The error is not explicit enough to helping debug the problem.

![screenshot from 2018-02-13 16-24-48](https://user-images.githubusercontent.com/504142/36174475-700b2cba-10da-11e8-8be4-2be30aec2db6.png)

Using the VFS storage mode, everything works fine.

Is it possible to have a working sample using a file system storage, or at least some notes in the source code to help understand how it should work without the need to dig into substance and texture source code?

**Comment by michael** [comment]
Hey @fabiobatalha!

Is the app and the storage service served from the same host+port? 

Also it could be that you have to urlencode the query parameter.

Maybe first hardcode the params in editor.js and see it it works?

**Comment by fabiobatalha** [comment]
Hy @michael 

The first attempt was hardcoding the parameters on edit.js

Yes both are in the same host+port.

**Comment by michael** [comment]
Oh I think now I see. You can't just connect the editor to a static file server. You need to run that service we implemented in node for reading and storing. 

E.g. the output of `http://localhost/archives/{docID}` must look like this:

![image](https://user-images.githubusercontent.com/2931/36175445-c374216a-110f-11e8-8afa-b491b61d8d84.png)

**Comment by michael** [comment]
The easiest way if you want to serve something else than the contents of ./data is to point to a different root folder. You can do this like so:

```
# In the Texture project folder start the server with a custom config root dir path
$ node make -s -w -d /path/to/your/document-library
```

There must be subfolders with valid ids, like the uuid you provided (63278a8a-2a5d-4171-b969-26bc56ab8d03)

Then you can access it via: 

http://localhost:4000/editor?archive=63278a8a-2a5d-4171-b969-26bc56ab8d03&storage=fs

**Comment by michael** [comment]
And make sure the contents of each subfolder (=document archive) have exactly that layout. 

https://github.com/substance/texture/tree/master/data/kitchen-sink

You need to provide the manifest.xml for it to work atm.

**Comment by fabiobatalha** [comment]
Humm Ok.

It seems the editor endpoint does not exists.

**Comment by michael** [comment]
The editor itself is just a static page, but the storage endpoint must be node backed. In our dev setup we are just serving both the static app and the /archives/{docId} endpoint from the same port, so there's no CORS issues to overcome.

**Comment by fabiobatalha** [comment]
@michael 

I have just updated my Texture environment and the editor is not working any more.

I run

node make clean
npm install
npm start

The server is running but the standard url retrieve a 404.

![screenshot from 2018-02-14 10-02-00](https://user-images.githubusercontent.com/504142/36211152-757ede32-116e-11e8-82ae-370f4e3a5102.png)

**Comment by michael** [comment]
Oh sorry, I introduced a regression by updating to a new version of our bundler. Please pull the latest change, it should work now.

Should we setup a call regarding integrating Alpha 4? Depending on the scenario it can involve some work to do a proper integration. We are aware of that, and should discuss. E.g. the `manifest.xml` file must be present when opening an article.

**Comment by fabiobatalha** [comment]
Would be nice to explain our attempt of integration, and how we can best integrate Texture with our Production Test Suite tool.

It is not a problem for us to produce the manifest.xml file, neither reproduce the FS structure under complaiance with texture needs.

I did a basic integration and it is working fine.
