### ISSUE TITLE
Problems loading contrib-group and contrib for editing

### ISSUE THREAD

**Issue by fabiobatalha** [substance/texture#385]
When opening a Valid JATS XML, and JATS4R file in texture, the following error happens.

![screenshot from 2018-02-14 17-04-53](https://user-images.githubusercontent.com/504142/36230695-37724f80-11a9-11e8-9089-bc97c17ec998.png)

It seems Texture is not being able to handle the conversion from JATS4R To TextureJATS when the XML do not have id's specified in the crontrib-group and contrib elements.

**XML failing to be loaded.**

````
<contrib-group>
    <contrib contrib-type="author">
        <name>
            <surname>Lage</surname>
            <given-names>João Gabriel Batista</given-names>
        </name>
        <xref ref-type="aff" rid="aff1"/>
    </contrib>
    <contrib contrib-type="author">
        <name>
            <surname>Gutierrez</surname>
            <given-names>Paulo Sampaio</given-names>
        </name>
        <xref ref-type="aff" rid="aff1"/>
    </contrib>
</contrib-group>
````

**XML loading after changes**

````
<contrib-group id="contrib-group-1" content-type="author">
    <contrib id="contrib-1" contrib-type="person">
        <name>
            <surname>Lage</surname>
            <given-names>João Gabriel Batista</given-names>
        </name>
        <xref ref-type="aff" rid="aff1"/>
    </contrib>
    <contrib id="contrib-2" contrib-type="person">
        <name>
            <surname>Gutierrez</surname>
            <given-names>Paulo Sampaio</given-names>
        </name>
        <xref ref-type="aff" rid="aff1"/>
    </contrib>
</contrib-group>
````

**Comment by michael** [comment]
It is not the id but content-type=author of contrib-group that must be specified.

Will check if we could add a transformation step or earlier failing. 

if you could adjust the converter output that would be the best solution.

**Comment by fabiobatalha** [comment]
Ok no problem. We can convert it in our side.

**Comment by michael** [comment]
Will add a rule so this fails earlier.

**Comment by michael** [comment]
Fixed via #392.

@fabiobatalha we do a normalisation step now that adds the missing attribute for the first and second `contrib-group` found.

Can you check if this working for you with your original input?

**Comment by michael** [comment]
FYI: This is what happens behind the scenes: https://github.com/substance/texture/pull/392/commits/e02d894bfa1c0cf2d17984fc85dfb42a7f4d9158

/cc @axfelix (please check too)

**Comment by axfelix** [comment]
Working here (though we already added a converter step to add that attribute).

**Comment by michael** [comment]
That's great, having it explicit is much better.
