### ISSUE TITLE
Rename JATS4R to JATS4M

### ISSUE THREAD

**Issue by michael** [substance/texture#394]
This should finally be done, as it is causing confusion. @Integral can do that? Just be really careful when doing the renames to not introduce regressions. It will be hard to spot later. You must also touch make.js for the schema build steps.

**Comment by Integral** [comment]
Yes!

**Comment by Integral** [comment]
@michael Let's decide what name we want to use instead of JATS4M!

**Comment by michael** [comment]
Discussed with eLife and Oliver. We are calling it `DarArticle`. Along with that rename we should also turn `TextureJATS` into `TextureArticle`.

**Comment by Integral** [comment]
I will take over this task, ok?

**Comment by michael** [comment]
Yes just let me finish with some merges before.

**Comment by michael** [comment]
You can start with this now. Just be really careful so we don't destabilize things.
