### ISSUE TITLE
Copyright statement for figure and tables 

### ISSUE THREAD

**Issue by fabiobatalha** [substance/texture#395]
As described in #265, the copyright statement for figures and tables should be implemented.

Is this still planned for the Alpha4 release?

**Comment by michael** [comment]
Can you provide examples? I will add to the spec and schedule implementation for the next release (Beta1)

**Comment by fabiobatalha** [comment]
@michael https://www.erudit.org/fr/revues/cuizine/2016-v7-n2-cuizine02881/1038479ar/#fi1

```xml
<fig id="fig1">
 <label>Figure 1</label>
 <caption>The classic regular poutine: fries, cheese curds and brown gravy.</caption>
 <permissions>
 <copyright-statement>Photographic credit: La Poutine Week</copyright-statement>
 <copyright-year>2013</copyright-year>
 </permissions>
 <graphic xlink:href="/fr/revues/cuizine/2016-v7-n2-cuizine02881/1038479ar/media/1999987n.jpg"/>
</fig>
```

**Comment by fabiobatalha** [comment]
@michael 

Other example with Title, caption and source.
https://www.erudit.org/fr/revues/teoros/2017-v36-n2-teoros03309/1042464ar/#fi1
```xml
<fig id="fig2">
 <label>Fig. 2</label>
 <caption>
  <title>Illustration 2 : Évolution des arrivées des touristes aux postes frontières</title>
  <p>MRE : Marocains résidant à l’étranger</p>
 </caption>
 <permissions>
 <copyright-statement>Source : Élaboré par les auteurs, d’après : Ministère du Tourisme du Maroc, « Chiffres clés »</copyright-statement>
 <copyright-year>2013</copyright-year>
 </permissions>
 <graphic xlink:href="/fr/revues/teoros/2017-v36-n2-teoros03309/1042464ar/media/2034346n.jpg"/>
</fig>
```

**Comment by michael** [comment]
Just copied this from another thread, where Melissa posted.

---

There is a JATS4R recommendation for permissions, which includes permissions for assets:

https://jats4r.org/permissions

Copyright is not required, but `<license>` or `<ali:license_ref>` are.
We use `<copyright-statement>`, `<copyright-year>`, `<copyright-holder>` and think they should be optional too.
Thanks!

**Comment by michael** [comment]
This is done.
