### ISSUE TITLE
Affiliations data loss after saving

### ISSUE THREAD

**Issue by fabiobatalha** [substance/texture#403]
Some data were removed from the Texture XML after saving.

![screenshot from 2018-02-28 11-46-02](https://user-images.githubusercontent.com/504142/36800261-1e58be56-1c7d-11e8-9084-c860ebde02dc.png)

**Comment by michael** [comment]
These fields are currently not in the spec and thus ignored. https://github.com/substance/dar/blob/master/DarArticle.md#aff

Is the original really needed, i mean it will be turned into structured records anyways?

Regarding the normalized field: We can auto-generate that and include it in the JATS, but ignore it when we read the document. Much like we do with the labels.

What is important is that orgname,orgdiv1,orgdiv2 use the full names and then in the rendering we can produce a normalised generated string. Currently the renderer looks like this:

```js
function organisationRenderer($$, entityId, entityDb, options = {}) {
  let { name, country } = entityDb.get(entityId)
  let result = [ name ]
  if (!options.short) {
    if (country) {
      result.push(', ', country)
    }
  }
  return result
}
```

**Comment by fabiobatalha** [comment]
Hi @michael,

I only posted this thinking on the requirement of do not have data loss in Texture.

I agree with you.

The issue with the normalized and original data is related to the SciELO Publishing Schema Style, maybe they have something to say about it.

@gustavofonseca

**Comment by gustavofonseca** [comment]
Hi @fabiobatalha and @michael,

The element `//institution[@content-type = 'normalized']` will no longer be mandatory on SciELO PS >= 1.8, so I think the current behaviour will not be a problem for us.
