### ISSUE TITLE
Saving produce invalid XML's.

### ISSUE THREAD

**Issue by fabiobatalha** [substance/texture#404]
After saving, some elements included in the XML turns it an invalid XML, these files could not be edited again after saving due to the parsing validations made while opening Texture.

![screenshot from 2018-02-28 12-04-24](https://user-images.githubusercontent.com/504142/36801349-e0b0625e-1c7f-11e8-909a-906ac5ec1892.png)

**Comment by michael** [comment]
This a regression that happened when we added the email field. Working on a fix.

**Comment by michael** [comment]
Fixed via #407.
