### ISSUE TITLE
Empty history element after saving lead to an invalid JATS file

### ISSUE THREAD

**Issue by fabiobatalha** [substance/texture#406]
![screenshot from 2018-02-28 15-26-19](https://user-images.githubusercontent.com/504142/36811483-fb8ea7ea-1c9b-11e8-97c6-95eb1bb310ad.png)

**Comment by michael** [comment]
Is it true that an empty history element does not pass JATS validation? What would be the desired output?

We should certainly optimise here and strip out empty history elements.

**Comment by fabiobatalha** [comment]
yes it is true. Besides the Texture validations we are also validating the saved documents against the hole original JATS Schema to catch up these situations.

In jats, once you have a history element you must have a date element inside it, and at least year inside date, and so on....

The desired output should be, avoid put the history element in the XML if you do not have a date to put on it.

**Comment by michael** [comment]
Will take care of it. Thank you!

**Comment by Integral** [comment]
It was already addressed.
