### ISSUE TITLE
ERROR:Could not find <dar> element.

### ISSUE THREAD

**Issue by fabiobatalha** [substance/texture#408]
Not sure what it means but we started to receive this error for all documents that were previously working.

I recently did the update of our texture instance with the last commits.

**Comment by michael** [comment]
We slightly changed the format of the manifest.xml file. Instead of `<archive>` we now have `<dar>` as the root tag. Can you fix that on your side so it conforms to the latest spec? We need to do better in announcing such breaking changes. Sorry for that.

**Comment by fabiobatalha** [comment]
No problem @michael 

I will fix it here.

**Comment by fabiobatalha** [comment]
Hi @michael 

Fixed the **dar** issue.

Now I'm having this error: ERROR:Unsupported document type

This happens with all documents.

Is there any other change I need to address.

thanks Fabio

**Comment by michael** [comment]
Ah one more change: 

before we had type='application/jats4m' and now you just put type='article'.

```xml
<!DOCTYPE sheet PUBLIC "DarManifest 0.1.0" "http://darformat.org/DarManifest-0.1.0.dtd">
<dar>
  <documents>
    <document id="manuscript" name="Reproducible Document Stack" type="article" path="manuscript.xml" />
</dar>
```

**Comment by fabiobatalha** [comment]
Its working, thanks!

**Comment by fabiobatalha** [comment]
Hello @michael

What means this error while loading a document?

"ERROR:state.errors[channel] is undefined"

**Comment by michael** [comment]
This shouldn't happen. Can you provide some context? Maybe post the file you used that caused the error.

**Comment by fabiobatalha** [comment]
@michael 

This is an exemple.

[fe189c64-b4a6-4f51-a916-abb31d2f86d7.zip](https://github.com/substance/texture/files/1782261/fe189c64-b4a6-4f51-a916-abb31d2f86d7.zip)

**Comment by fabiobatalha** [comment]
@michael 

I figured out the problem.

This is a XML file produced by the OJS, there are some elements in the XML that are not in Texture specifications. I removed them from the XML, and it is working.

This kind of unconformity should not be highlighted by the parsing while validating the XML file?

The invalid elements are, bio inside contrib, aff inside contrib, issue-id, issue-title.

**Comment by michael** [comment]
@fabiobatalha can you check if this was also fixed by https://github.com/substance/texture/commit/dd56e4629bc6d7d8b224fb5f7c4eacbb4361cfdf ?

**Comment by fabiobatalha** [comment]
It is working!
