### ISSUE TITLE
Blockquote would be easy like bold, italic, etc.

### ISSUE THREAD

**Issue by fabiobatalha** [substance/texture#410]
The blockquote tag would have the same behaviour of bold, italic, etc.

It means the user can:

* Select (highlight) an available paragraph and blockquote it pressing the bq button.
* Remove the blockquote from a paragraph positioning the cursor on the paragraph and pressing the bq button

**Comment by michael** [comment]
Could be an option, to treat it like headings and paragraphs. However for that to work smoothly we'd need to remove the structural nature of it that JATS allows (a blockquote can have multiple paragraphs and an attribution). If this is a requirement then it will be hard to treat it like you described.

**Comment by fabiobatalha** [comment]
Hi @michael 

It is only a suggestion to improve the usability, lets see what the others think about it.

For us it is not a mandatory task.

**Comment by michael** [comment]
Let's see if this comes up again. No action required atm.
