### ISSUE TITLE
include authors biography in contrib and/or in back.

### ISSUE THREAD

**Issue by fabiobatalha** [substance/texture#411]
Some Erudit articles have authors biography.

We should define a way to implement this requirement in future JATS4M specifications.

https://jats.nlm.nih.gov/publishing/tag-library/1.2d1/element/bio.html

**Comment by Melissa37** [comment]
We also use that tag at eLife for our non-research article content. It is a way for us to display a "wordy" affiliation and the editors have freedom about what they write.

**Comment by michael** [comment]
Ok if this were a single paragraph with basic formatting (strong, emphasis,...) options?

**Comment by fabiobatalha** [comment]
@michael 

There are some bio that includes a photo. :-/

But I think we can start with a single paragraph with basic formatting.

**Comment by michael** [comment]
We should be careful here. With our entity database abstraction, we are prepared to some day keep author information (affiliations, bio etc.) in a separate database for reuse (outside of the article).

Now there's a blurry line.. when we talk about author bios or photos, are these specific for the document or is it so that if the author publishes more articles, the same bio should be used?

Maybe we need to take a hybrid approach, being able to store basic author info (name, ORCID, etc.) in a shared db and document-specific parts (bio, photo?) in the JATS.

We should discuss this in Cambridge.

**Comment by Melissa37** [comment]
Yes, let's add this to the agenda. 
We at eLife need it for human readability and the information need not be retained in the database for re-use for the author the next time; it's likely to change. These authors will also have fully structured affiliation details

**Comment by fabiobatalha** [comment]
Hi @michael and @Melissa37 

May this bio change from one document to another, but I think it is ok to be structured and stored to be used further.

**Comment by Melissa37** [comment]
Happy with this suggestion :-)

**Comment by michael** [comment]
Group says:

- One free form biography - that can be annotated with simple HTML (em,link)

Lower priority:

- Image for the author

**Comment by fabiobatalha** [comment]
@michael 

Will Texture support the **bio** element in all the elements JATS is supporting it?

JATS elements that supports the element **bio**: `<back>`, `<collab>`, `<contrib>`, `<contrib-group>`

**Comment by fabiobatalha** [comment]
@michael 

I would like to confirm if this requirement defined in the last meeting is in the current developments?

**Comment by michael** [comment]
@fabiobatalha yes we will take care of this one! Can you confirm that this schema is sufficient:

```
<bio>: p*
```

The bio element can take multiple paragraphs (we would not allow complex content such as headings or disp-quotes etc.)

Do we need an author image as part of the biography or can we skip that?

**Comment by michael** [comment]
Another question: Would it be sufficient to use just one paragraph per author bio?

**Comment by fabiobatalha** [comment]
@michael 

for us the given example is enough, including basic styles like bold, italic, sub, sup and xlink:href

**Comment by fabiobatalha** [comment]
Yes, it is working.

Can we close it?

**Comment by michael** [comment]
Sure. :)
