### ISSUE TITLE
"ERROR:state.errors[channel] is undefined"

### ISSUE THREAD

**Issue by fabiobatalha** [substance/texture#413]
Hello @michael 
I opened this ticket because I'm facing this issue with some files from OTS.

In one of them I realised the XML had unexpected elements in the front metadata (bio, issue-id, issue-title).

Now there are some files that seems to be almost ok validating them against JATS, but the same error is being highlighted in Texture.

The issue is that this error do not give us any clue about what we should look in XML files.

An example of XML file where the trigger of the error in somewhere in the body, making a hard task to figure out what could be happening, and what we need to fix.

[example-1.zip](https://github.com/substance/texture/files/1786058/example-1.zip)

**Comment by michael** [comment]
Thank you! It was a regression on our side. I pushed a fix to master, now you should see a proper validation error message.

**Comment by fabiobatalha** [comment]
Working
