### ISSUE TITLE
Element 'p', attribute 'level': The attribute 'level' is not allowed.

### ISSUE THREAD

**Issue by fabiobatalha** [substance/texture#418]
Invalid JATS structure after saving a document.

Element 'p', attribute 'level': The attribute 'level' is not allowed. line 195

![screenshot from 2018-03-08 16-56-00](https://user-images.githubusercontent.com/504142/37178875-c9547e92-22f1-11e8-9de8-5bb2df4a50bd.png)

[poutine.zip](https://github.com/substance/texture/files/1794973/poutine.zip)

**Comment by michael** [comment]
Thanks for reporting. Can you reproduce when this is happening? Is it when you switch the type from a heading to a paragraph, that the level attribute stays?

**Comment by michael** [comment]
This is a really nice article btw! :)

**Comment by oliver----** [comment]
I think this is happening on every heading to paragraph switch.
ATM, the live-validator does not check attributes, that's why we fail to do this correctly.

**Comment by fabiobatalha** [comment]
@michael @oliver---- 

I can't reproduce this. I tried to switch between h1 -> par, h2 -> par, h3 -> par, saving the document in each change, the level attribute was never created.

**Comment by fabiobatalha** [comment]
I tried the previous steps in a new paragraph.

Doing any change in the broken paragraph and saving the document fixed the problem.

The given paragraph came from a copy n paste from a PDF file.

**Comment by michael** [comment]
We'll tackle this as soon as we can reproduce. Maybe you can find the same steps that led you to the problem.

**Comment by michael** [comment]
Closing this for now. Please reopen if you have steps to reproduce.
