### ISSUE TITLE
Add/Remove columns/rows for tables

### ISSUE THREAD

**Issue by michael** [substance/texture#428]
I'd suggest we follow the approach of Google Docs, where you can use a context menu (and no other UI elements are needed)

![image](https://user-images.githubusercontent.com/2931/37294702-be1214cc-2616-11e8-82ae-60065925d977.png)

@oliver---- I'm just thinking ahead when later we want to implement merge cell behavior. Then we would need a table selection, when you mouse down in one cell and drag into another. Then you don't have a text selection but instead a table selection. Can we achieve this?

![image](https://user-images.githubusercontent.com/2931/37294808-f15b7332-2616-11e8-9610-5775b4fda730.png)

**Comment by michael** [comment]
@oliver---- awaiting your green light, before Daniel can start implementing it.

**Comment by michael** [comment]
(only the add column/row thing, not the merge-split)

**Comment by oliver----** [comment]
> I'm just thinking ahead when later we want to implement merge cell behavior. Then we would need a table selection, when you mouse down in one cell and drag into another. Then you don't have a text selection but instead a table selection. Can we achieve this?

We should try to reuse the Selection from the Sheet implementation (See CustomSelection).

**Comment by oliver----** [comment]
Green light. While the Sheet's sliding viewport is too complicated, there are probably some pieces useful from the higher layer (overlays, selection, navigation, copy'n'paste, etc.)

**Comment by michael** [comment]
Cool, that's what I thought too. I also think it's ok here to have two separate implementations. The table one will be much simpler, an doesn't need handles and sliding viewport etc.

@Integral i will just start and check if we can activate our custom context menu. Once that is done, I will ping you and you can start implementing the commands.

**Comment by oliver----** [comment]
Tables have been implemented in a different way.
