### ISSUE TITLE
Revise default renderers for citations

### ISSUE THREAD

**Issue by michael** [substance/texture#430]
Current implementation can be found here: https://github.com/substance/texture/blob/master/src/entities/entityRenderers.js

We'd need some quality checking to make sure we have correct display for different possible inputs.

We are following eLife's citation style (used in their PDF's)

https://elifesciences.org/download/aHR0cHM6Ly9jZG4uZWxpZmVzY2llbmNlcy5vcmcvYXJ0aWNsZXMvMzI2NzEvZWxpZmUtMzI2NzEtdjIucGRm/elife-32671-v2.pdf?_hash=nrG1HRdFl4DZPdYxrP0OOJfOcyNJrkWHhR5HiBe0O4M%3D

Compare with: http://cdn.substance.io/texture-preview-1/

**Comment by zuphilip** [comment]
The eLife style is close to the [American Medical Association style](http://editor.citationstyles.org/styleInfo/?styleId=http%3A%2F%2Fwww.zotero.org%2Fstyles%2Famerican-medical-association) which might be better documented. Moreover, there are [guidelines to display DOIs from Crossref](https://www.crossref.org/display-guidelines/) as well as [from DataCite](https://support.datacite.org/docs/datacite-doi-display-guidelines), which I suggest to follow nowadays. Would that be okay?

**Comment by zuphilip** [comment]
See also #432

**Comment by michael** [comment]
Following American Medical Association style and DOI guidelines from Crossref sounds like a good idea.

In the long run we will probably integrate Citeproc.js into Texture so the user can choose between different styles. However that's technically tricky to solve (Citeproc.js does not work well with incremental updates), and will take some time. 

@Melissa37 @fabiobatalha are you ok with proceeding with fully implementing American Medical Association style (would serve us for quite some time I think)?

**Comment by zuphilip** [comment]
FYI The [overleaf template of eLife](https://www.overleaf.com/latex/templates/elife-latex-template/csqxykvsnyxm#.WIs5NLaLRGw) is more or less identical to AMA (position of the year, issue numbers).

**Comment by fabiobatalha** [comment]
@michael 
It is ok.

My only consideration is, texture should not try to format the authors name, as an example, see the image below, the reference 10.

![screenshot from 2018-03-13 12-18-46](https://user-images.githubusercontent.com/504142/37354985-41affb08-26b9-11e8-95ef-87dd6077a42f.png)

**Comment by zuphilip** [comment]
@fabiobatalha Do you mean the `Durand C` is displayed as `D C`? Well this seems to be a confusion about first and last name. Because the citation style will only display the initials of the first name and in your example it seems that `Durand` was wrongly saved as the first name.

**Comment by michael** [comment]
@fabiobatalha can you confirm this is the case? We could then close this issue. 

Thank you @zuphilip great work!

**Comment by fabiobatalha** [comment]
@michael Yes, it is. You can close this issue.

**Comment by michael** [comment]
Thanks!
