### ISSUE TITLE
Import of bibliography in CSL JSON

### ISSUE THREAD

**Issue by michael** [substance/texture#431]
E.g. we should be able to read:

```js
[
	{
		"id": "http://zotero.org/users/local/V2QRG5IH/items/JNF5KMDK",
		"type": "article-journal",
		"title": "Object vision to hand action in macaque parietal, premotor, and motor cortices",
		"container-title": "eLife",
		"volume": "5",
		"source": "CrossRef",
		"URL": "https://elifesciences.org/articles/15278",
		"DOI": "10.7554/eLife.15278",
		"ISSN": "2050-084X",
		"language": "en",
		"author": [
			{
				"family": "Schaffelhofer",
				"given": "Stefan"
			},
			{
				"family": "Scherberger",
				"given": "Hansjörg"
			}
		],
		"issued": {
			"date-parts": [
				[
					"2016",
					7,
					26
				]
			]
		},
		"accessed": {
			"date-parts": [
				[
					"2018",
					3,
					12
				]
			]
		}
	}
]
```

and map accordingly to our internal schema:

```js
JournalArticle.schema = {
  type: 'journal-article',
  authors: { type: ['person'], default: [] },
  editors: { type: ['person'], default: [] },
  articleTitle: { type: 'text', optional: true },
  source: { type: 'string', optional: true },
  volume: { type: 'string', optional: true },
  issue: { type: 'string', optional: true },
  year: { type: 'string', optional: true },
  month: { type: 'string', optional: true },
  day: { type: 'string', optional: true },
  fpage: { type: 'string', optional: true },
  lpage: { type: 'string', optional: true },
  pageRange: { type: 'string', optional: true },
  elocationId: { type: 'string', optional: true },
  doi: { type: 'string', optional: true }
}
```

More publication types here:

https://github.com/substance/texture/blob/master/src/entities/EntityDatabase.js 

I will do a first shot and then get help from @zuphilip.

**Comment by michael** [comment]
We'll start working on support to import CSL/JSON records. 

@Integral in order to fetch recoreds from DataCite we can use the following url:


https://data.datacite.org/application/vnd.citationstyles.csl+json/DOI

E.g. 
https://data.datacite.org/application/vnd.citationstyles.csl+json/10.5063/f1m61h5x

**Comment by michael** [comment]
New Modal shown after clicking "Add Reference(s)".

![image](https://user-images.githubusercontent.com/2931/38162532-f00fe320-34e2-11e8-8fc5-edf44365a160.png)

**Comment by zuphilip** [comment]
@michael You can use content negotiation for CSL JSON on `doi.org` directly, which then should work for DataCite, Crossref as well as mEDRA, e.g.
```
curl -L -H "Accept: application/vnd.citationstyles.csl+json" https://doi.org/10.5063/f1m61h5x
```
See also https://citation.crosscite.org/docs.html#sec-4

**Comment by michael** [comment]
@zuphilip thanks for the tip! We finished a first version using DataCite but definitely makes sense to use doi.org and content negotiation. We'll work on that.

@zuphilip if you want you could now take over and improve the CSL/JSON conversion. See: https://github.com/substance/texture/blob/master/src/converter/bib/BibConversion.js

**Comment by michael** [comment]
@zuphilp if you had some time to work o. BibConversion.js it would be fantastic. We are almost there with zotero import :)

**Comment by oliver----** [comment]
@jalperin was mentioning this
http://citeas.org/cite/http:/doi.org/10.5281/zenodo.160400

![image](https://user-images.githubusercontent.com/284099/38774854-4ce8da70-4069-11e8-8cc6-90cc63d44748.png)

**Comment by michael** [comment]
@oliver---- not sure how we could make use of CiteAs. It provides some citation styles and raw metadata (not sure this is also CSL/JSON), I guess it's better to collect the fields and render the styles locally and ad-hoc using Citeproc.js.

**Comment by jalperin** [comment]
My understanding from a [very quick look](http://citeas.org/sources) is that it looked up metadata from places other than Crossref. It seems it does, but only of github repos and CRAN/PyPI project pages, so perhaps not so useful, unless they expanded to also pulling metatada using things like Zotero connectors. 

Zotero does a good job of pulling metadata from URLs, I wonder if it would make sense to look into that using their code to do this so that we can do better than just matching things with Crossref DOIs.

**Comment by jalperin** [comment]
Here's a Ruby Gem: [Terrier](https://github.com/Authorea/terrier/tree/master/lib/terrier) that has a simple implementation of this.
