### ISSUE TITLE
Can't install npm dependency from github

### ISSUE THREAD

**Issue by de-code** [substance/texture#433]
Hi,

It would be nice if it was possible to install the dependency from github since it deviated quite a bit from the last release. e.g.:

```bash
npm install github:substance/texture --save
```

That 'installs' fine but the dependency can't be imported. Which I think is because the bundle is missing.

**Comment by michael** [comment]
I've added a postinstall hook, to build the bundle. Can you try again?

**Comment by michael** [comment]
Well that does not seem to work. I think we need the npm releases because of that said build step.

**Comment by de-code** [comment]
Okay, I think some other projects either provide a bundle built by CI or the source is standard enough to be understood. I noticed that your latest preview is actually in npm. So it is probably not an issue if those are available frequently.

**Comment by michael** [comment]
Yes, we'll count them up frequently (at least the preview channel), as we have softwares depend on Texture. E.g. https://github.com/stencila/stencila

**Comment by oliver----** [comment]
@de-code I think this should be possible now, after I have re-factored the build configuration via #454.
