### ISSUE TITLE
Preset Bold Style for image title lead to bad WYSIWYG results

### ISSUE THREAD

**Issue by fabiobatalha** [substance/texture#434]
The images titles are presented as **bold** text as default, but it is not represented in the final XML file after saving. When saving, the XML stills as a normal text without the bold tag.

For the user perspective it is a bad approach once it is not WYSIWYG as expected.

All preset styles forced by texture according to any kind of **data structure** must be reflected in the XML file (using the base style tags), to allow the XML readers/interpreters to represent the authors expected output.

In the sample bellow you can see the element title without the element bold inside, besides the Texture previewer shows the same text **bolded**.

Samples:

![screenshot from 2018-03-13 14-41-23](https://user-images.githubusercontent.com/504142/37362818-a7bcdfb6-26cc-11e8-9106-4871f6b3b0d7.png)

**Comment by michael** [comment]
Hmm.. we just use bold as style to give it more weight. It's the same for headings, which also don't have a bold tag but are just rendered differently.

What we should make sure though is that when you mark text bold inside a caption title, that the font-weight is increased from bold to super-bold so you can see it. :)

**Comment by fabiobatalha** [comment]
Yes, I understand.

I thing the bold to super-bold should work.

**Comment by michael** [comment]
Fixed via https://github.com/substance/texture/commit/590a54021c461fb6a40cc6cb16ac218ab742b5b7.
