### ISSUE TITLE
Saving authors in modal do not takes effect until ctrl+s

### ISSUE THREAD

**Issue by fabiobatalha** [substance/texture#435]
After saving changes made in Authors Modal, it is necessary to save the document with ctrl+s, otherwise the changes will not take place in the XML file.

It is not so intuitive.

**Comment by michael** [comment]
That behavior was intensional, we also don't save if you change the title. However we should maybe change the "Save" label to "Update" to avoid confusion. What do you think?

**Comment by fabiobatalha** [comment]
yes, I think the update button is proper, maybe also a message to alert the user to save the document after the update.

**Comment by michael** [comment]
Fixed via https://github.com/substance/texture/commit/6aaf4342aebd6a11a524548a95a0cabf5f9f9dc0
