### ISSUE TITLE
crtl+s stops to work after including a new institution

### ISSUE THREAD

**Issue by fabiobatalha** [substance/texture#436]
After include a new institution in a document without institutions, the ctrl+s stops to work.

The resulting action after ctrl-s is the ordinary browser behaviour to save the webpage.

**Comment by michael** [comment]
Do you use the latest version? I think I fixed that...

**Comment by fabiobatalha** [comment]
I have just updated Texture and the behaviour is the same.

by the way, the new look is much better!

**Comment by michael** [comment]
Can you check again with master? This should be solved now.
