### ISSUE TITLE
Some files are not being loaded in texture anymore.

### ISSUE THREAD

**Issue by fabiobatalha** [substance/texture#440]
Some files stop to work in texture, and no hint is displayed in the interface, neither in the stdout.

This is all info that I have:
![screenshot from 2018-03-15 11-58-09](https://user-images.githubusercontent.com/504142/37475191-7a52764e-2848-11e8-8e6c-f650a8f98dea.png)

**Comment by oliver----** [comment]
Hey @fabiobatalha 
Is it possible that you provide us the XML file. There seems some problem with the file, maybe encoding or such.

**Comment by fabiobatalha** [comment]
Hi @oliver---- 

I don't think so. It was working before I update Texture with the last version, including files previously saved in Texture stopped to work.

I'm sending a XML sample:

[texture.zip](https://github.com/substance/texture/files/1816203/texture.zip)

**Comment by fabiobatalha** [comment]
Hi @oliver---- 

Do you have tried to load this file?

**Comment by michael** [comment]
Currently we can't handle files, that don't have an abstract. To fix please just place an empty abstract element in `<article-meta>`.

I will work on a fix to create an `abstract` element automatically.

**Comment by michael** [comment]
Your file should now be working @fabiobatalha. Can you try latest master and also quick check with some other files. Not that I introduced a regression.

**Comment by fabiobatalha** [comment]
@michael It is perfectly working now!
