### ISSUE TITLE
Install KO !

### ISSUE THREAD

**Issue by ericvincenterv** [substance/texture#442]
Hello,

I want to install "Texture" and I follow "readme".

When I wrote "npm install", I have some problems.

> npm ERR! Linux 4.4.0-116-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! substance-texture@1.0.0-preview.1.1 prepublish: `node make publish`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the substance-texture@1.0.0-preview.1.1 prepublish script 'node make publish'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the substance-texture package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node make publish
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs substance-texture
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls substance-texture
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request

> 

What can I do ? I try something but without resolution.

**Comment by netbek** [comment]
According to the readme, Node 8 is required: https://github.com/substance/texture/blob/8fc4a7437b7114c273ab1bb231152d81175c5704/README.md#install Your error message says you have Node 4 installed.

**Comment by michael** [comment]
Yes, requires Node 8, at least if you want to use persistence.

@ericvincenterv did you get it to work now?
