### ISSUE TITLE
References Metadata are being replaced by anything else....

### ISSUE THREAD

**Issue by fabiobatalha** [substance/texture#443]
@michael  

Intriguing!!!

References in Texture are being replace by anything else different from what is available in the XML file.

The image below show the texture reference on the upper left, the original document in the upper right and the XML saved on Texture in the bottom.

![screenshot from 2018-03-19 13-35-52](https://user-images.githubusercontent.com/504142/37612065-7a3e92e8-2b7a-11e8-9415-c7a11cd79410.png)

**Comment by fabiobatalha** [comment]
At my point of view it is not working well, the references in Texture interface are totally different from that available in the XML file.

Regarding to the OTS results we are evaluating them. At this example at least the first 2 references are ok, as you can see in the image, the third is not ok.

But the real issue in this ticket is that Texture is presenting 49 unknown references in its interface. None of the 49 references presented in Texture are in the XML file.

**Comment by fabiobatalha** [comment]
Sorry, now I figured out. It is the issue of the order of the references. In Texture, they are not in the same order of the XML file.

**Comment by michael** [comment]
Oh sorry for the misunderstanding. 

I don't know what happens on docx to JATS conversion, this is out of scope for Texture and needs to be improved separately. Have you talked to Alex Garnett? 

We currently render only one citation style (AMA). See: https://github.com/substance/texture/pull/437

**Comment by michael** [comment]
The order of references I will address soon. Just a bit short on time atm.
