### ISSUE TITLE
Journal Reference should have `PubMed ID`

### ISSUE THREAD

**Issue by lpanebr** [substance/texture#447]
Just noticed that the Book form has the `PubMed ID` and that the journal does not.

- Journal Reference should also have the `PubMed ID` field.[1]

[1] https://www.ncbi.nlm.nih.gov/books/NBK7282/#A32750

**Comment by michael** [comment]
Fixed via https://github.com/substance/texture/commit/fbbb500230d8915a38f37b678f3d6d802b0d3fbd.
