### ISSUE TITLE
UX: Edit Authors

### ISSUE THREAD

**Issue by michael** [substance/texture#451]
Working on ideas how to improve author editing. Currently you need to navigate a lot of modals to enter basic author data such as given names, surname.

Here's a UI idea, that allows quick editing and supports two author types (person and group). By clicking on edit you'll see another modal offering more detailed fields (such as ORCID, affiliations etc.)

![image](https://user-images.githubusercontent.com/2931/37767119-4598aa8c-2dc9-11e8-9c44-b68c75d7cc37.png)

Note, this view would be shown in authoring mode... we can have a more verbose QC view for author editing where we expose all fields.

**Comment by michael** [comment]
Here's an updated Edit Person dialog, that allows basic editing of affiliations in-place.

![image](https://user-images.githubusercontent.com/2931/37768724-ec13aa38-2dce-11e8-82fb-5bebaa5798b7.png)

Compared to the current UI this has some pros but also some cons e.g.:

- Good: faster creation and editing of affiliations (no longer navigating dialogs)
- Bad: Users may overlook that there's more fields (e.g. they could enter "Columbia University, United States" but it would be correct to add United States to the country field.

**Comment by michael** [comment]
NOTE: Clicking "New Affiliation" could provide a selection of available affiliations (e.g. when entered already from another author's view). Then you decide either to pick an existing one or create a new one.

**Comment by michael** [comment]
An alternative to in-place affiliation editing: 

We could show a list of affiliations (using the display version of the affiliation) which you can expand to reach the form fields underneath.

![meh](https://user-images.githubusercontent.com/2931/37769641-f1cd0e4e-2dd1-11e8-80c9-2f0747b6d44b.png)

**Comment by michael** [comment]
We could apply the same to author editing, but then we'd get multiple editing levels (`AuthorList > Edit Author > Edit Affiliation`).

**Comment by michael** [comment]
Here's another attempt, allowing in-place editing of authors, without an extra popup. Also see #452 

![bla](https://user-images.githubusercontent.com/2931/37784117-5e4f562e-2df7-11e8-8a28-9d5f9298d2f9.png)

**Comment by lpanebr** [comment]
This looks very nice and is surely much better than navigating modals. I just find it a bit awkward having the email between first and last names.

**Comment by michael** [comment]
Yeah I just copied the existing forms which are generated from the schema and sometimes have weird order. We'll fix those things once we have decided on a UI/UX pattern.

**Comment by gmaciocci** [comment]
How do you dismiss the forms once displayed?

**Comment by michael** [comment]
By clicking on the author/affiliation name again. But we could have a separate button in the form, called something like "done editing" to make this more explicit.

**Comment by NickDuffield** [comment]
@michael I think a modal panel is a better approach. Simply because it handles bigger forms more easily. In addition it scales better to smaller screens without wasting space. I think the show more options for inputs need to be very carefully considered, especially in the affiliation instance. I would avoid show more when you can and only use it for inputs that are rarely used or not key. 

Generally, I think typical popup modals are fine for small pieces of information like 'Are you sure you want to do this? Yes, No' type actions, but complex forms with lots of inputs with hide/show behaviour may not be the best use for them.

Happy to discuss this further on a call or when you come to Cambridge. Hope this helps.

**Comment by lpanebr** [comment]
My experience with modals on small screens is not good. They often do not resize appropriately making me have to fiddle with panning to achieve what I need or to simply dismiss it. I blame this on design without responsiveness in mind.

That being said I think that the inline UI can yield a better UX **if the forms are designed to be responsive** and simple.

**Comment by michael** [comment]
We must make sure this works well when there's a huge list of authors (like 100).

**Comment by lpanebr** [comment]
If composing a long list of authors like this is a real requirement then this current approach may not be the best.  

An easier way IMO would be to do it with a spreadsheet-like UI having one author per row. Maybe the same for institutions and using regular numeral indexes to make the author institution links.

One alternative way would be to keep the current approach and just add a batch import feature that reads from a spreadsheet.

**Comment by oliver----** [comment]
@michael please re-evaluate and decide what to do next (or close)

**Comment by michael** [comment]
We have the metadata view now.
