### ISSUE TITLE
UX: In-Place Reference Editing

### ISSUE THREAD

**Issue by michael** [substance/texture#452]
![image](https://user-images.githubusercontent.com/2931/37776077-d249e8e0-2de4-11e8-8c6d-77302450e031.png)

Considerations:

- no modal required
- edits are immediately previewed
- quick editing of authors (person, or group)

**Comment by fabiobatalha** [comment]
It is really great!!

**Comment by gmaciocci** [comment]
Pretty interesting approach! Is the form loaded dynamically or on first load? Wouldn't want to needlessly slow down the page.

**Comment by michael** [comment]
Nothing need to be loaded, as all data is already in memory. This is just a matter of presenting/revealing information. You could toggle on multiple references for editing, the editing dialog would be closed by clicking on the edit symbol again.

**Comment by michael** [comment]
This is not critical for 1.0. But maybe we want to consider this (inline-editing) again for an authoring-optimised build. Assigning 2.0 milestone.

**Comment by michael** [comment]
We are consistently using the Metadata View for this now.
