### ISSUE TITLE
Could not open a file previously saved by the desktop app.

### ISSUE THREAD

**Issue by gustavofonseca** [substance/texture#467]
The file opening window doesn't allow me to select files, but only directories. If I click the button "open" at the context of a directory, I get the following error: **ERROR:Cannot read property 'name' of undefined** 

I'm using the version 1.0.0-preview.1 (1.0.0-preview.1) on MacOS High Sierra.

**Comment by GrazingScientist** [comment]
Same here, also with Mac OS High Sierra. I saved a test file (Texture did not allow me to change the name, only the folder to store it). Then I wanted to open the same file ('manuscript.xml'), but I cannot open any file with Texture. Any suggestions?

**Comment by michael** [comment]
In Texture you open folders (=archives) not files. That's why on save you are prompted with a folder path, not a file path.

If you still have problems, please provide a zip file of the corrupt contents, so we can investigate.

**Comment by GrazingScientist** [comment]
Hi @michael ,

thanks for the specification. It is a little counterintuitive but understandable that you need to store images, text files etc. in a folder not in a single file. Thanks for the support. For my side this issue may be closed!

**Comment by oliver----** [comment]
During the initial phase, we were having problem occasionally after introducing a regression.
Since several months we try to avoid that by running a load-save-load cycle on an `kitchen-sink` example that contains all types of content that can be created by Texture.
