### ISSUE TITLE
custom button in the editor toolbar 

### ISSUE THREAD

**Issue by kaschioudi** [substance/texture#470]
Hi guys,

Is it possible to add a custom button to the editor's toolbar ? 
If so could you please point me to some documentation or example code ? 

thanks,

**Comment by michael** [comment]
What would you like to add? 

The tools are configured here: https://github.com/substance/texture/blob/master/src/editor/EditorPackage.js

However, note that these are currently only editing-related tools, so application-level things like a save button do not really fit here. In a next version of Texture there may be a way to inject app level commands and tools into the main toolbar. We are currently working on some concepts in Substance to make that possible.

**Comment by kaschioudi** [comment]
thank you for your reply. 

> The tools are configured here: https://github.com/substance/texture/blob/master/src/editor/EditorPackage.js

Is it the only way ? I mean is there another way than modifying directly `EditorPackage.js` ? Like when I extend `substance.Component`

> However, note that these are currently only editing-related tools, so application-level things like a save button do not really fit here. In a next version of Texture there may be a way to inject app level commands and tools into the main toolbar. We are currently working on some concepts in Substance to make that possible.

It's actually the save button I was interested in.

**Comment by michael** [comment]
We will work out something to address this properly. We just need some time.

**Comment by michael** [comment]
Save button is now there.
