### ISSUE TITLE
Multi-Language support

### ISSUE THREAD

**Issue by michael** [substance/texture#472]
Some example:

- https://www.scielosp.org/article/bwho/2015.v93n12/826-833/en/
- https://epaa.asu.edu/ojs/article/view/3367

Group says: We need translations for title+abstract+keywords

- not visible in UI by default
- activated by "Add translation" in the menu

**Comment by gustavofonseca** [comment]
I just remembered that at SciELO there are also some use cases for figure captions in multiple languages. For example http://www.scielo.br/pdf/ce/v61n357/0366-6913-ce-61-357-00001.pdf.
