### ISSUE TITLE
Support for Sub Articles

### ISSUE THREAD

**Issue by michael** [substance/texture#473]
- Currently used by eLife/SciELO for Decision Letter / Author Comments
- Translated articles are represented by SciELO as sub-articles
- Benefit is that ther's only one shared place for metadata

**Comment by michael** [comment]
- Another benefit is that the sub-article inherits things like ref-list from the main article

**Comment by michael** [comment]
OK, we need to get concrete here. What information we want to capture in sub-articles? I think the requirement is not "support for sub-articles" it's rather.. "allow editing Decision Letter", "Author Comments" etc. 

Please provide one kitchen-sink tagging example for each use-case.

**Comment by lpanebr** [comment]
There are a multitude os use-cases **(document types)** for sub-articles including but not limited to:
 - response published with letter[1]
 - Decision Letter
 - Author Comments
 - translated version of article published with original article[2]

and on top of that they may be nested!

Maybe this is another case of #1020 ?

[1] https://www.ncbi.nlm.nih.gov/pmc/pmcdoc/tagging-guidelines/article/tags.html#el-subart
[2] https://www.ncbi.nlm.nih.gov/pmc/pmcdoc/tagging-guidelines/article/dobs.html#dob-multi-lang

**Comment by michael** [comment]
We have separate issues for each use-case now.
