### ISSUE TITLE
Allow level one sections in the abstract

### ISSUE THREAD

**Issue by michael** [substance/texture#474]
They are optional, and used to structure the summary.

**Comment by michael** [comment]
For example: https://www.scielosp.org/article/bwho/2015.v93n12/826-833/en/

**Comment by jalperin** [comment]
Another example, from PLOS: http://journals.plos.org/plosone/article/file?id=10.1371/journal.pone.0190482&type=manuscript

**Comment by michael** [comment]
Dup of #945.
