### ISSUE TITLE
Normalise title properties in publication types

### ISSUE THREAD

**Issue by michael** [substance/texture#482]
From `BibConversion.js`...

```js
  // Mapping of title depends on item type
  if (source.type==='book' || source.type==='report') {
    data.source = source.title
  } else if (source.type==='webpage') {
    data.title = source.title
  } else {
    data.source = source['container-title']
    if (source.type==='chapter') {
      data.chapterTitle = source.title
    } else if (source.type==='dataset') {
      data.dataTitle = source.title
    } else {
      data.articleTitle = source.title
    }
  }
```

We should probably use a title property everywhere, as done by CSL/JSON. Also we could introduce Chapter as a separate pub type, again to conform to CSL/JSON and not have that weird distiction of source and title for the book type.

@zuphilip what would you suggest is the cleanest way to do it? We are pretty free what we do internally (and in the Dar spec) as long as it makes sense. :)

**Comment by michael** [comment]
Todo:

- [ ] update EntityDatabase.js
- [ ] update EntityConverters.js
- [ ] update BibConversion.js
- [ ] update [Dar spec](https://github.com/substance/dar/blob/master/DarArticle.md#ref) accordingly

**Comment by michael** [comment]
If we use separate types for book and chapter we would get:


Book:

```
person-group[person-group-type=author]?, person-group[person-group-type=editor]?, edition?,
year?, month?, day?, source?, publisher-loc*, publisher-name*, fpage?, lpage?, page-range?,
page-count?, elocation-id?, pub-id[pub-id-type='doi, pmid, isbn, entity']?
```

Chapter:

```
person-group[person-group-type=author]?, person-group[person-group-type=editor]?, edition?,
year?, month?, day?, chapterTitle?, publisher-loc*, publisher-name*, fpage?, lpage?, page-range?,
page-count?, elocation-id?, pub-id[pub-id-type='doi, pmid, isbn, entity']?
```

Please help refine this! What differs between a book and a book chapter?

**Comment by Melissa37** [comment]
Please don't have different types!
See comments and examples on https://github.com/substance/texture/issues/481

**Comment by zuphilip** [comment]
> We should probably use a title property everywhere, as done by CSL/JSON.

CSL-JSON has also _two_ poperties: `title` and `container-title`, where e.g.
* for a book `title` is the book title;
* for a chapter `title` is the chapter title and `container-title` is the book title;
* for a journal article `title` is the title of the journal article and `container-title` is the journal title.

> what would you suggest is the cleanest way to do it?

Well, I would suggest to have different item types for a book and a chapter. I have seen the examples, but I haven't seen anything there which would not work with two different item types. All bibliographic metadata formats and reference management systems I am aware of do treat books and chapters as two different item types.

If you have only one item type for both, then you need to check every time for the presence of `chapterTitle` to know whether it is actually a chapter or book you are dealing with, e.g. https://github.com/substance/texture/blob/a13c5a2e2fa094df94e086c57de3c60a606a7998/src/entities/entityRenderers.js#L73-L74 and https://github.com/substance/texture/blob/a13c5a2e2fa094df94e086c57de3c60a606a7998/src/entities/entityRenderers.js#L112-L113

Besides from that, I suggest to consider to extend the fields for books and chapters with the following fields (possibly rename them):
* volume (just the number, for multi-volumed books)
* number of volumes (just the number, for multi-volumed books, if you want to cite them completely)
* series/collection title
* number in the serie/collection (just the number)
* translator (besides authors and editors)

Moreover, for conference proceedings and articles in conference proceedings, you may want to consider also
* conference name (besides the proceeding name which equals the book title)
* place of the event (besides the place of publication)

but these two fields are maybe less common used in any citation style or data format.

**Comment by michael** [comment]
Thanks for your comment @zuphilip! 

Convinced we want a separate type for chapters. @Melissa37 we will use the exact same structure as now, the only thing is that we make chapters explicit by introducing `publication-type=chapter`

I'll work on a PR for this...

**Comment by michael** [comment]
@zuphilip can you point me to a spec for the CSL schema? 

But maybe i just start with normalising the title attributes and let you do a second path... you know the terminologies better than I do. :)

**Comment by michael** [comment]
Being worked on #484

**Comment by zuphilip** [comment]
The best resource for the CSL types and fields is IMO the mapping from the Zotero fields: https://aurimasv.github.io/z2csl/typeMap.xml

**Comment by fabiobatalha** [comment]
@michael This approach seems to not cover all the Books references representations.

What happens if we want to have the source and chapter-title in the same reference? It is really a common pattern in books references.

See the last example @Melissa37 gave to us in:  #481

**Comment by michael** [comment]
That was my mistake, of course we will support both fields.
