### ISSUE TITLE
Reduce number of item types

### ISSUE THREAD

**Issue by zuphilip** [substance/texture#487]
I have studied the examples given in #481 and think that we may not need all item types which we have at the moment. Here are two suggestions how we can reduce them:
* Delete the item type `periodical` which seems identical to `journal article` and because it neither exists in the SciELO Publishing Schema nor in the CSL data schema. Even if someone wants to cite a special issue of a journal rather than a journal article (which is IMO very rare), this is still possible by using e.g. book with its fields.
* Merge the item types `report`, `clinical trial`, and `preprint`, because they neither exists as separate item types in the SciELO Publishing Schema nor in the CSL data schema. The overall type could then look like:

```
Report.schema = {
  type: 'report',
  authors: { type: ['object'], default: [] },
  sponsors: { type: ['object'], default: [] },
  title: { type: 'string', optional: true },
  reportType : { type: 'string', optional: true },
  containerTitle: { type: 'string', optional: true },
  collectionTitle: { type: 'string', optional: true },
  collectionNumber: { type: 'string', optional: true },
  year: { type: 'string', optional: true },
  month: { type: 'string', optional: true },
  day: { type: 'string', optional: true },
  publisherName: { type: 'string', optional: true },
  publisherLoc: { type: 'string', optional: true },
  isbn: { type: 'string', optional: true },
  doi: { type: 'string', optional: true }
}
```

The `sponsors` are coming from the clinical tests, but I guess also other reports can be sponsored. We should certainly have the `doi` field for reports, but there might also be other reports which are printed by a publisher and therefore have an `isbn`. With `reportType` you could still indicate e.g. that this report is a preprint, clinical study or also a working paper is possible. The `collectionTitle`, `collectionNumber` (or is `seriesTitle` better) can for example hold the information like "Technical Report Series; 949" from example http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.8-branch/tagset/elemento-element-citation.html#relatorio-1 .  What do you think?

**Comment by zuphilip** [comment]
Oh, I see. Then I would suggest to keep this type, but rename it into `newspaper-article`. The term "periodical" is ambiguous, see e.g. [here](https://en.wikipedia.org/wiki/Periodical_literature).

**Comment by JGilbert-eLife** [comment]
@zuphilip I agree it's ambiguous but I'm not sure newspaper-article is the right name either. Periodical, as eLife uses it, covers magazine articles (e.g. New Scientist or Which? Magazine or something like that) as well as newspapers. It's short-hand for any non-academic piece of periodical literature - as @Melissa37 says, something that has not been peer-reviewed.

I suppose going by the wikipedia article, it's covering 'popular' periodical literature.

**Comment by zuphilip** [comment]
"Periodicals" cover all literature appearing on a regular schedule, including magazines, newspapers but also scientific journals. That is IMO a standard definition supported also by [Online Dictionary for Library and Information Science](https://www.abc-clio.com/ODLIS/odlis_p.aspx#periodical) or the well-known reference work "Ulrich's International *Periodicals* Directory". At least I am not aware of any different definitions which would exclude scientific journals from periodicals.

CSL has all three types of articles:
* **article-magazine**
* **article-journal** with special fields DOI, volume, issue, editor
* **article-newspaper** with special fields like `edition` (e.g. national, international or regional editions) and `section` (e.g. National, International, Business, Politics, Opinion, Features)

What that cover everything which we need also here?

Well I can think of book series or annual reports also as periodicals. Books appearing in book series can be treated as normal books and can make sure that there is a field for the book serie. Each annual report can be just treated as a report.

**Comment by Melissa37** [comment]
OK, we at eLife would be OK with @publication-types "magazine" and "newspaper" to replace "periodical"

Thanks

**Comment by michael** [comment]
I just updated the Dar spec according to what has been proposed here. @substance/texture-contributors Please review:

https://github.com/substance/dar/blob/master/DarArticle.md#ref

@zuphilip regarding the `section` field in newspaper.. which JATS tag would you pick to represent that? See: https://jats.nlm.nih.gov/archiving/tag-library/1.1/element/element-citation.html

@zuphilip let's try to use JATS terminology when discussing requirements (with Melissa and the others) and then internally we map it to the schema properties (which I think should be aligned with CSL/JSON if possible). Maybe in EntityDatabase.js we could add comments for each property, referencing the corresponding JATS element, so we have one place to look up the mapping. I know it's quite some work to have all the converters and mappers in place but I hope those shouldn't change a lot in the future once we have them ready.

Thanks all for your work on this!

**Comment by zuphilip** [comment]
Maybe [`part-title`](https://jats.nlm.nih.gov/archiving/tag-library/1.1/element/part-title.html) would be suitable for section in newspapers?

For reports I suggest to also include the field `series` for things like "Technical Report Series; 949". I couldn't find a suitable JATS field to separate the series number.

**Comment by michael** [comment]
Also started adding some hints to EntityDatabase.js where the properties do not match the JATS elements. See https://github.com/substance/texture/commit/9e0f4ffa81073751dd6f1e54435c4df5d0bc5228.
