### ISSUE TITLE
Introduce additional fields for books and chapters

### ISSUE THREAD

**Issue by michael** [substance/texture#490]
As described by @zuphilip:

> Besides from that, I suggest to consider to extend the fields for books and chapters with the following fields (possibly rename them):
>
>  - volume (just the number, for multi-volumed books)
>  - number of volumes (just the number, for multi-volumed books, if you want to cite them completely)
>  - series/collection title
>  - number in the serie/collection (just the number)
>  - translator (besides authors and editors)

**Comment by michael** [comment]
I've added `volume` and series (=`part-title`) to the spec. 

Couldn't find good tags for number of volumes or number in the series. Is it ok to have those fields combined? Is it a problem having the information combined in one field?

@zuphilip Not sure we want to track translators: will they ever show up in the rendered citation? 

For Texture the primary aim is not to build a database of bibliographic records, I think that should live in central places (like Crossref) etc. However we want to be compatible with those database and be able to edit all individual fields that are needed for rendering citations (maybe feed back into Crossref at some point). We could leave the other fields out, making the edit forms shorter and easier to understand.

**Comment by zuphilip** [comment]
I see [`series`](https://jats.nlm.nih.gov/archiving/tag-library/1.1/element/series.html) in JATS and this might be better suitable here than `part-title`.

> Is it a problem having the information combined in one field?

That is a possible solution to e.g. save the series number into the series field, e.g. `series="Awesome Working Paper Series; no. 11"`. It is possible that the delimiter between series and the number depends on the citation style and also the label "no." can be localized in various languages. However, these fields are maybe less important and we may go here for the combined information.

Translator(s) can be important in some disciplines especially when dealing with some languages. For example MLA style has some rules how to render translators: https://owl.english.purdue.edu/owl/resource/747/6/ .

---

I don't have a clear vision of the workflow with the citations in the future, which might be important for such decisions here as well. Therefore, I try to outline a possibility: Let us assume that one can use the CSL-styles here in the future. People might then use the doi importer or a Zotero integration for adding citations. both sources give us CSL-JSON which can be transformed into the internal format. For rendering the citations with citeproc in any CSL style, we will need again CSL-JSON as input. Will this been produced from the internal format? Or will the original CSL-JSON been saved and just reused for rendering the citations as well?

**Comment by michael** [comment]
Ok I will change to series, unless there are objections. I'm not so familiar with these terminologies, but what I think would be important is to not have different contextual meanings for the same tag. If we use the series tag it should mean the same thing, no matter in which pub type it is used. 

Good idea to suggest a convention for the input (e.g. semicolon to separate the no). That way we can go with a simple solution for now and would later be able to split it into a separate field by just parsing the user input (we could even add validation here). Let's be pragmatic now, and optimise for the common usecase. We'll discuss and cover edge cases as they'll frequently come up.

Ok, I will update the spec to include translators, since they'll be used for rendering. Thanks for pointing that out.

---

We absolutely want to do what you describe. That's why it makes a lot of sense to use the same properties in the internal model (EntityDatabase.js). We could possibly avoid any extra conversion. As mentioned in #494 we should carefully walk through the whole schema and use the same properties whenever possible. We'd like to be able to choose a citation style in Texture and have it live rendered (as you edit the document) using Citeproc.js; we were just not satisfied with the current implementation of Citeproc.js (API and performance); it would be great if we could collaborate on improving it and then integrate.

**Comment by zuphilip** [comment]
Thank you! (I cant't help you with citeproc.js much, besides that I can point you to some experts there.)
