### ISSUE TITLE
Additional fields for proceedings and articles in proceedings

### ISSUE THREAD

**Issue by michael** [substance/texture#491]
> Moreover, for conference proceedings and articles in conference proceedings, you may want to consider also:
>
> - conference name (besides the proceeding name which equals the book title)
> - place of the event (besides the place of publication)

**Comment by Melissa37** [comment]
AKA 
<conf-name>
<conf-loc>

in JATS DTD

**Comment by michael** [comment]
Thank you. I added them to the spec. Schema needs to be adjusted and converters need to be implemented.

**Comment by michael** [comment]
We now have conference-paper as a type, which has these two fields.
