### ISSUE TITLE
Improved schema and converters for bibliographic data

### ISSUE THREAD

**Issue by michael** [substance/texture#494]
I've tried to consolidate a number of proposals by @zuphilip (#487, #490, #491, #481)

Tasks:

- [ ] verify updated [Dar spec](https://github.com/substance/dar/blob/master/DarArticle.md#ref)
- [ ] Normalise properties of EntityDatabase to use same props as CSL-JSON (not reinvent the wheel), e.g. some of the `source` properties can be called `containerTitle` (we just add a note to which JATS elements those properties refer to)
- [ ] Update EntityDatabase schema to conform to latest spec
- [ ] converters (JATS <-> EntityDb, and import from CSL-JSON

@substance/texture-contributors please comment on the latest Dar spec! It's important that we now settle on the schema so our implementation will hold for a long time.

@zuphilip want to take over the implementation part? As a time-frame end of next week would be ideal... (does not need to be final, just important to have the implementation in sync with the spec again).

**Comment by zuphilip** [comment]
Okay, I can start with the implementation. I can spend some time today, but don't know how much time I can spent the other days...

**Comment by michael** [comment]
Think we can close this.
