### ISSUE TITLE
Math: Use selected text as formula

### ISSUE THREAD

**Issue by michael** [substance/texture#495]
Needs investigation. I think the data is there and saved, but no rerender (at least of the KaTeX part) is done.

**Comment by michael** [comment]
Also, we when you have some text selected (property selection) we should use that as the TeX code instead of overriding with f(x). That way you can type sqrt(42), select it and turn it into math.

**Comment by michael** [comment]
Rerender problem fixed via https://github.com/substance/texture/commit/ed30a74b9b8f6120d32fa0fdf3380ee54f7f2d7a

**Comment by Integral** [comment]
pls check #496
