### ISSUE TITLE
When math is selected content is shifted down (jumpy)

### ISSUE THREAD

**Issue by michael** [substance/texture#500]
![image](https://user-images.githubusercontent.com/2931/39447134-1cf49052-4cc1-11e8-9906-72b9cd4709b7.png)

@Integral maybe you can investigate. Also maybe there's a way to draw a nicer selection rectangle. I think we had a nice solution in the old Stencila app already. Maybe we can replicate it.

**Comment by michael** [comment]
Look here it is stable:

![math-selection-old-stencila](https://user-images.githubusercontent.com/2931/39447243-7af91416-4cc1-11e8-8e70-7f8edaddb975.gif)

**Comment by Integral** [comment]
Will take a look

**Comment by oliver----** [comment]
@Integral have you found out the reason for this?

**Comment by Integral** [comment]
Gone with new KaTeX version.
