### ISSUE TITLE
Undo/redo with math could lead to text operation errors

### ISSUE THREAD

**Issue by Integral** [substance/texture#503]
Steps to reproduce:
1) Open the kitchen sink example
2) Find a place with a square root, remove first slash: \sqrt(13) -> sqrt(13), quit formula editor
3) Apply undo
4) Edit formula another time, you'll see \sqrt(13)), remove first or last symbol
5) You'll see the error: "provided string is too short".

![](http://g.recordit.co/eRBNAS1jJd.gif)

**Comment by oliver----** [comment]
@Integral be careful with text property paths: 
https://github.com/substance/texture/blob/8387e32310085aee011baf5e93fa8edefb4b950a/src/editor/components/EditInlineFormulaTool.js#L16

Unfortunately substance won't prevent doing this.

Correctly it is done like this:
https://github.com/substance/texture/blob/3c3e411499c219146c698e691c35cf335bda5745/src/editor/components/EditInlineFormulaTool.js#L18

I.e. using `textNode.getPath()`

**Comment by Integral** [comment]
Sorry,
that must be hack from the very beginning when we did try to bring it
anywhere without proper xml api. Bad thing.

**Comment by oliver----** [comment]
No worries. I'll just show you best practices ;)
