### ISSUE TITLE
When exporting to JATS <element-citation publication-type="undefined">

### ISSUE THREAD

**Issue by nokome** [substance/texture#513]
I suspect that this is a known bugs but thought I'd submit this since it's causing corruption of archives (so that they can not be opened).

To reproduce:

1. `npm start`
2. Go to `http://localhost:4000/?storage=fs`
3. Make a change to the text and press `Ctrl+S`
4. Then refresh the browser page to reload the example

Get error:
```
ArticleLoader.js:16 Uncaught (in promise) Error
    at Object.load (ArticleLoader.js:16)
    at TextureArchive._loadDocument (TextureArchive.js:80)
    at entries.forEach.entry (TextureArchive.js:28)
    at Array.forEach (<anonymous>)
    at TextureArchive._ingest (TextureArchive.js:23)
    at Promise.resolve.then.then.then.then (PersistedDocumentArchive.js:156)
    at <anonymous>
```
`git diff data/kitchen-sink/manuscript.xml` shows:

```
-        <element-citation publication-type="book">
+        <element-citation publication-type="undefined">
+          <publisher-loc>Cambridge</publisher-loc>
```

**Comment by michael** [comment]
@Integral can you take that one?

**Comment by michael** [comment]
Fixing this now as it's urgent.

**Comment by michael** [comment]
Fixed.

**Comment by michael** [comment]
@zuphilip we are close to releasing Texture and Stencila. Could you maybe do a final pass of testing, so we have good confidence that the converters for references work as expected and no data is lost on save.

To test writing to the file system you can use the following url:

http://localhost:4000/?storage=fs

Now pressing cmd+s will write to the data/kitche_sink folder.

**Comment by oliver----** [comment]
This is fixed.

**Comment by oliver----** [comment]
I think there is no pressure. Things are basically working.
In the next weeks I will flesh out the test suite a bit more.

**Comment by michael** [comment]
@zuphilip sorry I missed your comment. As Oliver said there is no big pressure, but if you had some time just to quick test the supported publication types and if they render properly that would be great. Just so users of this release have a fairly stable experience for editing references.
