### ISSUE TITLE
It doesnt work. 

### ISSUE THREAD

**Issue by josuevalrob** [substance/texture#515]
Npm 5.6.0

Npm install: 
$ npm start

> > substance-texture@1.0.0-preview.1.8 start C:\xampp\htdocs\texture
> > node make web -s -w -d data
> 
> C:\xampp\htdocs\texture\node_modules\dar-server\src\serve.js:27
>   app.get(apiUrl+'/:dar', async (req, res) => {
>                                 ^
> SyntaxError: Unexpected token (
>     at createScript (vm.js:56:10)
>     at Object.runInThisContext (vm.js:97:10)
>     at Module._compile (module.js:542:28)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Module.load (module.js:487:32)
>     at tryModuleLoad (module.js:446:12)
>     at Function.Module._load (module.js:438:3)
>     at Module.require (module.js:497:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (C:\xampp\htdocs\texture\node_modules\dar-server\index.js:2:10)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! substance-texture@1.0.0-preview.1.8 start: `node make web -s -w -d data`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the substance-texture@1.0.0-preview.1.8 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\Administrador\AppData\Roaming\npm-cache\_logs\2018-05-07T14_08_48_967Z-debug.log
> 

Npm start: 

> 
> > substance-texture@1.0.0-preview.1.8 start C:\xampp\htdocs\texture
> > node make web -s -w -d data
> 
> C:\xampp\htdocs\texture\node_modules\dar-server\src\serve.js:27
>   app.get(apiUrl+'/:dar', async (req, res) => {
>                                 ^
> SyntaxError: Unexpected token (
>     at createScript (vm.js:56:10)
>     at Object.runInThisContext (vm.js:97:10)
>     at Module._compile (module.js:542:28)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Module.load (module.js:487:32)
>     at tryModuleLoad (module.js:446:12)
>     at Function.Module._load (module.js:438:3)
>     at Module.require (module.js:497:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (C:\xampp\htdocs\texture\node_modules\dar-server\index.js:2:10)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! substance-texture@1.0.0-preview.1.8 start: `node make web -s -w -d data`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the substance-texture@1.0.0-preview.1.8 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\Administrador\AppData\Roaming\npm-cache\_logs\2018-05-07T14_09_25_533Z-debug.log
>

**Comment by oliver----** [comment]
It is the wrong node version, I think: node >=8
It is working for me on Windows

Michael Aufreiter <notifications@github.com> schrieb am Di., 8. Mai 2018,
12:21:
