### ISSUE TITLE
Placeholder for empty references

### ISSUE THREAD

**Issue by Integral** [substance/texture#524]
I thought I did that already (with grey font), but currently empty record looks like this:
<img width="739" alt="screen shot 2018-05-15 at 15 24 36" src="https://user-images.githubusercontent.com/182010/40056701-d08c0534-5854-11e8-8f48-acccb72f97ea.png">

**Comment by oliver----** [comment]
Probably your implementation got lost in some rewriting of the bib-record rendering.
As we rely on that bib-record rendering, it should be solve there. Because it renders '.' it would be 'hard' to understand that the record is 'empty, and the solution would be a hack.

Closing this in favor of #684
