### ISSUE TITLE
Allowing display and editing of additional article assets

### ISSUE THREAD

**Issue by JGilbert-eLife** [substance/texture#534]
In addition to main figures and figure supplements, eLife supports a number of additional assets for articles.

    source code (code) - this can exist on its own or in relation to a figure, table or video
    source data (data) - this can exist on its own or in relation to a figure, table or video
    video (video)
    supplementary file (supp)
    reporting standards (repstand)
    inline graphics (inf)
    transparent reporting form (transrepform)

We would need to be able to add, edit and (excepting inline graphics) cite all of these.

**Comment by michael** [comment]
Can we get concrete examples here? I wonder if we can generalise the tagging. Basically to just allow any additional assets (= files) to be attached to the article.

**Comment by Melissa37** [comment]
https://github.com/elifesciences/XML-mapping/blob/master/elife-00666.xml
https://github.com/elifesciences/XML-mapping/blob/master/elife_file_naming_2016_08_25.md

Let's talk about that as it will have an effect on the display side and we'll need to ask developers in the eLife team as well as PubMedCentral folk as well as JATS XML people.

**Comment by JGilbert-eLife** [comment]
@michael - I haven't had a chance to do this today but I intend to create new tickets (if they don't exist) for the related issues that fall under this one.

Here, I'm using the word 'asset' simply to mean file associated with an article, which is perhaps not very edifying!

Briefly, I think these categorise as:

video (video) - video files, displayed like figures, this can exist as a main display item or as supplemental to a figure

source code (code) - accompanying file, this can be supplemental to the whole article or one of the figures, tables or videos
source data (data) - accompanying file, this can be supplemental to the whole article or one of the figures, tables or videos

supplementary file (supp) - accompanying file, supplemental to the whole article 
reporting standards (repstand) - accompanying file, supplemental to the whole article
transparent reporting form (transrepform) - accompanying file, supplemental to the whole article

inline graphics (inf) - these are images that can appear set within the text, rather than in their own 'block' like figures; we want to get away from using them to denote symbols appearing in figures but likely still have use cases for them e.g. within tables.

I'll update tomorrow with tagging examples in new tickets/existing tickets.

**Comment by JGilbert-eLife** [comment]
Hi again @michael , @Melissa37 - I've added individual tickets for these addition assets. On reflection, I thought it sensible to structure it around the way this gets expressed in the XML.

So we have:

Use of `<supplementary-material>` in `<caption>`: https://github.com/substance/texture/issues/1016
Use of `<supplementary-material>` in `<back>`: https://github.com/substance/texture/issues/1015

Use of `<media>` (e.g. videos) at the same level as main figures: https://github.com/substance/texture/issues/1014
Use of `<media>` (e.g. videos) at the same level as figure supplements: https://github.com/substance/texture/issues/1017

Use of `<inline-graphic>`: https://github.com/substance/texture/issues/1018

Let me know if any of this doesn't make sense!

I hope that makes sense!

**Comment by Melissa37** [comment]
Fab, thanks @JGilbert-eLife! M

**Comment by michael** [comment]
This is actually a lot we need to do here, so I would ask you to choose an issue to start with and we move the others to the 3.0 milestone.

Once you chose one and assigned the 2.0 milestone to one of the issues, please will close this issue.

**Comment by michael** [comment]
Ok I already chose the video support as the next step. Inline-graphic is in the 2.0 milestone too. Closing this. I will finish this iteration and then we can discuss shifting some things around.
