### ISSUE TITLE
Ability to tag authors as deceased

### ISSUE THREAD

**Issue by JGilbert-eLife** [substance/texture#540]
In the eLife XML, we apply this as an attribute on the author and as a footnote:

```
 <contrib contrib-type="author" id="author-00001" deceased="yes">
<xref ref-type="fn" rid="fn1">&#035;</xref>


<fn fn-type="fn" id="fn1">
                    <label>&#035;</label>
                    <p>Deceased</p>
</fn>
```

**Comment by michael** [comment]
I'd suggest to only use the deceased attribute in the source XML. Adding a separate footnote is redundant. It can be automatically generated and displayed in the HTML version. If this needed e.g. to conform to PubMed standards, we could always generate an "archive version" of the XML.

**Comment by JGilbert-eLife** [comment]
That's a good point - we only have it in there because it is required for deceased status to show up on PMC.

We could approach PMC about changing the way they handle this. I agree that the footnote is otherwise unnecessary and PMC seems able to generate a corresponding author status footnote from that attribute alone. What does everyone think?

**Comment by michael** [comment]
I've covered the deceased attribute #360
