### ISSUE TITLE
Towards a TextureDocument API

### ISSUE THREAD

**Issue by michael** [substance/texture#543]
I'm working on the reader and creating new components while trying to design them reusable (for editor and reader) and less dependent on the internal Texture XML model.

I've found that we work directly with the XML model a lot. Also we named our components after the XML elements. E.g. FrontComponent, BodyComponent etc., maybe we should question that.

I'd like to move towards a range of independent components that depend on a slim API for accessing content, instead of working with the XML tree directly.

So far we did it like this:

```js
    el.append(
      $$(ArticleHeaderComponent, {
        node: frontNode
      }).ref('articleHeader'),
      $$('div').addClass('main-content').append(
        $$(ArticleAbstractComponent, {
          node: abstractNode
        }).ref('articleAbstract'),
        $$(ArticleBodyComponent, {
          node: bodyNode
        }).ref('articleBody'),
        $$(ArticleReferencesComponent, {
          node: refListNode
        }).ref('articleReferences')
      )
    )
```

And in the ArticleAbstractComponent:

```js
      el.append(
        $$('h1').addClass('sc-heading').append('Abstract')
      )
      // There can be multiple abstracts. We just take the first
      const content = node.findChild('abstract-content')
      let contentEl
      if (content) {
        contentEl = $$(this.getComponent('container'), {
          placeholder: 'Enter Abstract',
          name: 'abstractEditor',
          node: content,
          disabled: this.props.disabled
        })
      } else {
        // TODO: ability to add an abstract
      }
      el.append(contentEl)
```

--- 

Here's a rough proposal of introducing API objects that hide the details of the xml implementation behind the scenes. 

```js
    const api = this.editorSession.getAPI()

    el.append(
      $$(ArticleHeaderComponent, {
        title: api.getArticleTitle(),
        authors: api.getAuthors(),
      }).ref('articleHeader'),
      $$('div').addClass('main-content').append(
        $$(ArticleAbstractComponent, {
          model: api.getAbstract()
        }).ref('articleHeader'),
        $$(ArticleBodyComponent, {
          model: api.getBody()
        }).ref('articleBody'),
        $$(ArticleReferencesComponent, {
          model: api.getReferences()
        }).ref('articleReferences')
      )
    )
```

Then we could remove things like node.find from ArticleAbstractComponent and instead use an AbstractModel API.

```js
  render($$) {
    const abstract = this.props.model
    
    let el = $$('div')
      .addClass('sc-abstract')
      .attr('data-id', abstract.id)

    el.append(
      $$('h1').addClass('sc-heading').append('Abstract')
    )

    let contentEl = $$(this.getComponent('container'), {
      placeholder: 'Enter Abstract',
      name: 'abstractEditor',
      node: abstract.getContainer(),
      disabled: this.props.disabled
    })
    el.append(contentEl)

    return el
  }
```

this.props.model would be of type AbstractModel and provide the minimal API to serve components to read and write information as needed.

```js
abstract.getContainer() // returns an XMLContainerNode (interface for ContainerEditor)
abstract.getText() // get Abstract as plain text
abstract.empty() // clear abstract
```

For references we can provide a dedicated API too, that behind the scences writes into the XML + entity db.

```js
let references = api.getReferences()

references.addReference({...})
references.deleteReference({...})
references.forEach() // iterate over sorted reference list
```

```js
let figure = api.getFigure('fig1')

figure.setTitle('Bla blup') // ability to programmatically set the title (xPub etc. may use this)
figure.getLabel() // get the automatically generated label
...
```

@oliver---- is this a good idea, or is it rather overkill that adds another layer that a developer needs to understand? If we do it, I guess we should really always go through an API call and never use low-level xml manipulation

**Comment by oliver----** [comment]
In general is such an abstraction not a bad thing.
The advantage of this is more flexibility. The disadvantage for us, we need to document it.
Advantage of using XML directly, the schema can be used to generate documentation, disadvantage the implementation is tangled with the specific XML schema.
In general I prefer this abstraction, because it might give us more freedom/stability on the long run. Even if we change something in the model/schema we might be lucky and only need to change the adapter.

Nevertheless, with your proposed solution you will find yourself with no updates anymore.
You need to do something similar as NodeComponent.

**Comment by oliver----** [comment]
Thinking of very specific UI for JATS, which we will have to do a lot in the next months, I would on the other hand say, it is an overkill.
So it would be nice to have a general solution for reusable things, but maybe we will find it annoying to create this extra layer for JATS specific meta data stuff.

**Comment by michael** [comment]
> Nevertheless, with your proposed solution you will find yourself with no updates anymore.
You need to do something similar as NodeComponent.

True, but this could then be a chance to model the updates better. E.g. sometimes we have different elements (abstract+abstract-content) we need to listen to but they form one semantic unit, so this could be a chance to group them together again, and just say, when the model updates, rerender the component.

**Comment by oliver----** [comment]
You can do that. 
Just be aware that adding listeners for document changes without any means of hierarchical layering, it will slow down the system with the number of components.

**Comment by michael** [comment]
> Thinking of very specific UI for JATS, which we will have to do a lot in the next months, I would on the other hand say, it is an overkill. So it would be nice to have a general solution for reusable things, but maybe we will find it annoying to create this extra layer for JATS specific meta data stuff.

Actually for the publisher metadata, I'd see the abstraction as rather helpful. While the JATS representation might be changing for some time the interface could stabilise much faster. E.g. we can define the setKeywords() API and keep it while changing the serialisation underneath several times until the publishers are happy.

Most of the metadata is simple key-value stuff without annotations so the XML model is much heavier than a JS API that expresses the same.

**Comment by michael** [comment]
> Just be aware that adding listeners for document changes without any means of hierarchical layering, it will slow down the system with the number of components.

the layering would still be there right (it's in the model) - so if we have the FigureModel it would only proxy updates that happen inside `fig` - or am I missing sth?

**Comment by oliver----** [comment]
There won't be no shortcuts like generated UI anymore, or the XML hack thingie. 
So if something is blocking adoption, it is blocked. Just be prepared to create a lot of things really quick ;)

**Comment by oliver----** [comment]
> the layering would still be there right (it's in the model) - so if we have the FigureModel it would only proxy updates that happen inside fig - or am I missing sth?

It is still substance data, and no magic. With every change you need to identify the list of candidates you want to call. If this identification is done by a increasing number of 'selectors' then your system is slowing down.

**Comment by oliver----** [comment]
You need to come up with something new, or use something like NodeComponent.

**Comment by michael** [comment]
what's your feeling? is it the right time to start this work?

I'm just realising that now by working on the reader components that things are very much tied to the XML nodes and even the element structure in XML. If we extracted some generic model for different places, we could step by step break free of the serialisation format.

If we needed the XML edit thingie we could provide that as an api in places where we need it. E.g. the `ContribModel` could have a setXML method for expressing a group author with roles etc. where we don't want to provide a UI for it.

**Comment by oliver----** [comment]
I think it could be the right time, as we do not want to release a new Texture Version the next 2 weeks.

**Comment by oliver----** [comment]
It could also be interesting to work on Component tests along with this work. Then the whole thing will get cleaner and tighter.

**Comment by michael** [comment]
I will start this off by introducing TextureArticleAPI and use it for the new reader implementation. I will for now not touch the existing editor code. So we can go hybrid for a lil while until we feel confident and switch over the whole thing?

**Comment by oliver----** [comment]
Also you might want to consider looking at the EditingInterface. This is basically already intended to be something like this. `tx` is fulfilling this API.

**Comment by michael** [comment]
Not sure but maybe it's ok to have that on a separate level (EditingInterface). E.g. TextureArticleAPI could start transactions internally but don't expose the concept to the user.

My feeling is that EditingInterface could be a more low-level version of the api, while TextureArticleAPI then is really intended for the folks that don't want to mess with editing and selections etc.

**Comment by oliver----** [comment]
That is ambitious. But if you want you can go for it.

**Comment by oliver----** [comment]
@Integral after some basic first steps done by us, definitely! :)
