### ISSUE TITLE
Error when using XMLDocumentImporter to process article - Could not find <dar> element

### ISSUE THREAD

**Issue by samboustani** [substance/texture#546]
I'm returning the following using the dar service and a custom storageUrl, but I get an error at the following function in XMLDocumentImporter.js.  The <dar> element is in a manifest.xml file, but I'm not using that file (at least I don't want to have to use it since I'm sending the content in without it):

```
importDocument (dom) {
    this.reset()
    const doc = this.state.doc
    if (isString(dom)) {
      dom = DefaultDOMElement.parseXML(dom)
    }
    const startTag = this.xmlSchema.getStartElement()
    let rootEl
    if (dom.is(startTag)) {
      rootEl = dom
    } else {
      rootEl = dom.find(startTag)
    }
    if (!rootEl) throw new Error(`Could not find <${startTag}> element.`)
    // TODO: an XMLDocument should be more like a DOM
    // and just have children, instead of the designated root element
    doc.root = this.convertElement(rootEl)
    return this.state.doc
  }
```

**_Uncaught (in promise) Error: Could not find <dar> element.**
    at XMLDocumentImporter.importDocument (XMLDocumentImporter.js:32)
    at loadManifest (loadManifest.js:14)
    at Object.load (ManifestLoader.js:5)
    at TextureArchive._loadManifest (PersistedDocumentArchive.js:211)
    at TextureArchive._ingest (TextureArchive.js:16)
    at Promise.resolve.then.then.then.then (PersistedDocumentArchive.js:152)_

`"<?xml version=\"1.0\" encoding=\"UTF-8\"?> <!DOCTYPE article PUBLIC \"DarArticle 0.1.0\" \"http://darformat.org/DarArticle-0.1.0.dtd\"> <article xmlns:xlink=\"http://www.w3.org/1999/xlink\">   <front>     <article-meta>       <title-group>         <article-title>Proposal test 5af51a28070f6d1740d2ca42</article-title>       </title-group>     </article-meta>   </front>   <body>     <sec id=\"section-1\">       <title>Section 1</title>       <p id=\"p-1\">Lorem ipsum dolor sit amet, ea ludus intellegat his, graece fastidii phaedrum ea mea, ne duo esse omnium. Ne mel quas quodsi. Ea pri semper nostrum necessitatibus. Mea salutatus gloriatur persecuti eu, augue oportere efficiendi at eum. Ex eam mutat falli dicit.</p>     </sec>     <sec id=\"section-2\">       <title>Section 2</title>       <p id=\"p-2\">Lorem ipsum dolor sit amet, ea ludus intellegat his, graece fastidii phaedrum ea mea, ne duo esse omnium. Ne mel quas quodsi. Ea pri semper nostrum necessitatibus. Mea salutatus gloriatur persecuti eu, augue oportere efficiendi at eum. Ex eam mutat falli dicit.</p>     </sec>     <sec id=\"section-3\">       <title>Section 3</title>       <p id=\"p-3\">Lorem ipsum dolor sit amet, ea ludus intellegat his, graece fastidii phaedrum ea mea, ne duo esse omnium. Ne mel quas quodsi. Ea pri semper nostrum necessitatibus. Mea salutatus gloriatur persecuti eu, augue oportere efficiendi at eum. Ex eam mutat falli dicit.</p>       <p id=\"p-4\">Lorem ipsum dolor sit amet, ea ludus intellegat his, graece fastidii phaedrum ea mea, ne duo esse omnium. Ne mel quas quodsi. Ea pri semper nostrum necessitatibus. Mea salutatus gloriatur persecuti eu, augue oportere efficiendi at eum. Ex eam mutat falli dicit.</p>     </sec>   </body>   <back>     <app-group>       <app>         <title>Appendix 1</title>       </app>       <app>         <title>Appendix 2</title>       </app>     </app-group>   </back> </article>"`

**Comment by michael** [comment]
The root tag must be `<dar>` not `<article>`.

**Comment by michael** [comment]
Oh wait sorry, in the manifest.xml it has to be `<dar>` the article itself can have `<article>`. You must provide a manifest file for the interface to be fulfilled.
