### ISSUE TITLE
Associating funder with authors and including grant numbers

### ISSUE THREAD

**Issue by JGilbert-eLife** [substance/texture#551]
eLife publishes funder name (+ fundref ID if available), grant number and author for each grant received by authors on an article:

```
<funding-group>
                <award-group id="fund1">
                    <funding-source>
                        <institution-wrap><institution-id institution-id-type="FundRef">https://dx.doi.org/10.13039/100000011</institution-id>
                        <institution>Howard Hughes Medical Institute</institution>
                        </institution-wrap>
                    </funding-source>
                    <award-id>F32 GM089018</award-id>
                    <principal-award-recipient>
                        <name>
                            <surname>Harrison</surname>
                            <given-names>Melissa</given-names>
                        </name>
                    </principal-award-recipient>
</award-group>
```

We need to be able to add new funding entries to an article, verify the entered funder against the fundref registry (see https://github.com/substance/texture/issues/476) and add a fundref ID if available, and associate one or more authors with each funding entry.

**Comment by michael** [comment]
I wonder if we coulda achieve a real association between an author (contrib element) and a grant (award-group). So instead of repeating the name in principal-award-recipient, could we use an xref within contrib to reference `fund1` according to this example?

```xml
<contrib id="contrib-60a1b7e4c0b0eae9ce6a2e4516917d49" contrib-type="person">
  <name>
    <surname>Melissa</surname>
    <given-names>Harrison</given-names>
  </name>
  <xref ref-type="award" rid="fund1" />
</contrib>
```

**Comment by michael** [comment]
This is done and editable via the interface. Will be ready for testing in next release.
