### ISSUE TITLE
Including appendix sections

### ISSUE THREAD

**Issue by JGilbert-eLife** [substance/texture#554]
eLife articles may contain one or more appendices. These can contain their own assets:

figures
figure supplements
tables
videos
source data and source code related to the above

References in eLife appendices got into the main reference list used for the whole article.

**Comment by fabiobatalha** [comment]
It is also important for Érudit

**Comment by michael** [comment]
@JGilbert-eLife can we break this down into separate issues with examples?

**Comment by JGilbert-eLife** [comment]
I've added individual tickets for

Figures: #1026 
Tables: #1027 
Videos: #1028 

The XML for those individual items is the same as in the main text; what is different is it is appearing within the appendix structure and the labels take the appendix number as a prefix (e.g. Appendix 1—figure 1).

We (eLife) need to nail down an issue with appendix tagging before I can post examples of that, but hopefully will be able to do so by the end of the week.
