### ISSUE TITLE
Coloured text, coloured cells in tables

### ISSUE THREAD

**Issue by JGilbert-eLife** [substance/texture#555]
eLife permits coloured text. At the moment this is implemented using named-content tags which are then interpreted by our website. For example:
```
<named-content content-type="author-callout-style-a1">Some text</named-content>
```
The website will then display 'Some text' in red.

Similarly, coloured backgrounds in cells are added using the style attribute:
```
 <td style="author-callout-style-b5">Some text</td>
```
The list of allowed colours is given in the attached PDF file. 
[eLife_Allowed_Colours.pdf](https://github.com/substance/texture/files/2072458/eLife_Allowed_Colours.pdf)

This is a very eLife specific solution. However, while a more general solution that we could then limit to use the eLife palette would give flexibility to other users, eLife specifically picked out colours that would be easily readable online, so there might be some scope of recommending others use the same palette.

**Comment by michael** [comment]
Is there a way to move towards a more semantic direction. E.g. we could say one category is "key-concept" which means the words tagged are particular important concepts in the paper. We can still use the color palette but we put the semantics first, and not the style. Any thoughts?

Maybe you could look at your corpos of documents that use author-callout styles and try to identify common semantics behind it.

**Comment by Melissa37** [comment]
Yes, we agree with being more semantic and would really appreciate input from the rest of the consortium on this!
It's not great how eLife specific it is and we'd welcome the ability to make it more useful for others too

**Comment by michael** [comment]
I think the main need behind this is semantically tagging and linking concepts in the text. So if we do this right, we may be able to not just say this is a concept, but also link it to a database entry (gene databse etc.). 

Let's not rush here, and bring this to the attention of more people. I'll label this as a proposal for now until we've found agreement.

**Comment by dalapeyre** [comment]
Colored cellos in tables are typically accomplished with the 'style' attribute on the element th or the element td.

**Comment by oliver----** [comment]
@dalapeyre you can use `` ` `` (back-tick) to write xml-tags, i.e. write something like this `` `<element/>` ``

**Comment by dalapeyre** [comment]
Appreciate the advice, but I thought I had used backticks.
I will just avoid angle brackets.

—Debbie

> On Sep 19, 2018, at 4:30 PM, Oliver Buchtala <notifications@github.com> wrote:
> 
> @dalapeyre you can use ` (back-tick) to write xml-tags, i.e. write something like this `<element/>`
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 


================================================================
Deborah A Lapeyre              mailto:dalapeyre@mulberrytech.com
Mulberry Technologies, Inc.      https://www.mulberrytech.com
17 West Jefferson Street         Phone: 301-315-9631 (USA)
Suite 207                        Fax:   301-315-8385
Rockville, MD 20850
----------------------------------------------------------------
Mulberry Technologies: Consultancy for XML, XSLT, and Schematron
================================================================

**Comment by Melissa37** [comment]
eLife will be reconsidering the use of color to convey info anyhow as we are working on increasing the accessibility of our content and using colour is such a no-no!

FYI @JGilbert-eLife

**Comment by michael** [comment]
Yeah! We'll become famous for helping remove colours from scientific manuscripts! 😅

**Comment by michael** [comment]
Closing this in favour of #1102.
