### ISSUE TITLE
NLM JATS to DAR JATS

### ISSUE THREAD

**Issue by scimole** [substance/texture#558]
Im new to texture. How can i convert an xml from NLM JATS to DAR JATS format, for further editing with Texture.

Thanks in advance

**Comment by michael** [comment]
There are a lot different flavours of JATS so it's hard to write a general converter. However we'd like to encourage orgs/journals to write little transformers to convert/normalise their content.  It's not a hard job, just there's a lot of variation, and we can't take responsibility for that. With the Dar format we hope that in future things will be interexchangable between journal etc. (even authoring tools).
