### ISSUE TITLE
Not possible to create two links next to each other

### ISSUE THREAD

**Issue by michael** [substance/texture#562]
Reported by Nick Stiffler:

> I am having an issue with texture / substance that I am hoping you or Oliver can help me resolve. On occasion we need to create links in superscripts as well as the base word of the superscript. I can link one or the other, but not both. The coordinates seem to overlap, and I am blocked from creating the second link. For example, the endOffset of the base word might be x and the startOffset of the superscript is also x. If you have any hints on how to override this behavior that would be great.

Response:

> I think what happens is that when you want to create the second link, it is interpreted as expanding the existing link. In order to create two links touching each other you'd first make them using a space in between, and then delete the space.

We may want to find a better behaviour to prevent such confusion.

**Comment by oliver----** [comment]
Fixed.
