### ISSUE TITLE
Ability to add name-alternatives for authors

### ISSUE THREAD

**Issue by fabiobatalha** [substance/texture#567]
In Érudit context there are several cultural journals where the authors make use of alternative names, or pseudonyms.

The ability to deal with this kind of data will be an improvement for Érudit in the use of Texture as a QC tool.

The DAR should change from:

```
contrib-id[contrib-id-type=orcid]?, contrib-id[contrib-id-type=entity]?, name, email?, xref*
```

To:

```
contrib-id[contrib-id-type=orcid]?, contrib-id[contrib-id-type=entity]?, name, name-alternatives?, email?, xref*
```

**Comment by michael** [comment]
How will this information be displayed? Will it be in the authors list somehow, or will it be some kind of info box per author, that shows a line "uses pseudonym RapidRabbit"? ;)

I'm only a bit worried about how we make this info editable and accessible. It will become a very crowded form just to enter an author, and most fields are not used in 99% of the cases.

One question I'd always ask is will this information be used for data querying later? E.g. would you ever do data mining and ask: get all articles written by "RapidRabbit"?

Don't get me wrong, I'm all for structured data when ever possible. Still, if there's info we just want to display along with the author, we could utilise a free form text field to describe arbitrary author details such as the pseudonyms. Would that be also acceptable? Just wondering...

What is anybody else thinking @substance/texture-contributors ?

**Comment by fabiobatalha** [comment]
A real example: https://www.erudit.org/fr/revues/socsoc/2017-v49-n1-socsoc03347/1042824ar/

``Kurt Tucholsky, alias Peter Panter`` 

We are not able to query by the alias, yet, but we should. 

Once this info exists in the Article and it is not frequent but still an existing practice, I think we should be able to deal with this, even if we say that Texture will not be able to handle, edit or show this king of information (what is bad), it should be able to receive a XML with this information and bypass it to the final (saved) XML.

**Comment by gustavofonseca** [comment]
I'm checking with the production team.

**Comment by jalperin** [comment]
This seems like a pretty obscure case, and I do not think we should be worrying about allowing it to be edited within texture. At least not for a 1.0. 

Adding edge cases like this will always be tempting, but if we start including them all, then it will get messy fast. However, I don't think adding a free form text field is the right solution either. 

Perhaps the middle ground is to make sure Texture doesn't strip this data if it is found in the XML, and allows it to pass through.

**Comment by gustavofonseca** [comment]
Just to update on my last comment [https://github.com/substance/texture/issues/567#issuecomment-396240437], we are not aware of the occurrence of authors with alternative names in our database.

**Comment by michael** [comment]
We need to make a decision sooner or later, which will be either supporting that edge case or not. If we support it (in agreement) then I would make this info editable as well. As said I'm worried about crowded forms (we even may need multiple alternative names, with add+remove functionality), and other orgs may have similar use-cases, which are very rare and I'd like to say yes only if there's broader consensus (at least two orgs really need it).

@fabiobatalha can you challenge the need for this functionality at Erudit? Usually pseudonyms are used to hide a real identity. So you could still decide to publish as "Peter Panter", without the real name. Is that an option?

**Comment by michael** [comment]
I'm adding a propsal label to unconfirmed requirements. So this just means it's open for discussion but not confirmed. Everything that is confirmed will have a 'requirements' label.

**Comment by fabiobatalha** [comment]
@michael 

The pseudonym was an example, authors may publish with artistic name and other things. We reproduce the ways the journals deals with their publications, so, at this moment, it is not in Érudit hands to decide to publish or not both names.

So, in Érudit use cases, we still need to have the ability to identify and publish the authors names and their pseudonyms (or other names).

If this feature will not be available in the first version, would be good at least that Texture do not remove these elements from the XML when they are available.

**Comment by jalperin** [comment]
My vote is to not allow editing in V1, but to also not remove from XML if
present.

Juan

**Comment by michael** [comment]
Suggestion: Can we do it as a simple property of a contrib element. Like this:

```xml
<contrib>
  <name>...</name>
  <string-name content-type="alias">Peter Panter</string-name>
</contrib>
```

We can make this easily editable. Only limitation: Just one pseudonym per author.

@fabiobatalha what do you think?

**Comment by fabiobatalha** [comment]
@michael I think it is ok.

**Comment by michael** [comment]
@Integral this is good to implement. We need a field `alias` in our internal model and we use the string-name tagging as shown above to model an alias/pseudonym.

**Comment by michael** [comment]
Needs to be added to the TextureArticle.rng `contrib` schema.

**Comment by michael** [comment]
Done via #748.
