### ISSUE TITLE
Regressions in Reader branch

### ISSUE THREAD

**Issue by michael** [substance/texture#569]
Just to track them so we don't forget fixing:

- annotations are not properly rendered in Editor (bold, ext-link etc.), in Reader it works
- References are broken in Editor (we may refactor that anyways)
- tbc...

**Comment by michael** [comment]
I fixed the problem with missing annotation components. Was just missing registrations.

Found some other things:

- IsolatedNodes are no longer rendered in Editor
- Seems Footnotes and References are mixed up in EditXrefComponent (some change must have caused this)

![image](https://user-images.githubusercontent.com/2931/41108194-35a00afc-6a74-11e8-99c0-9eea8eab7cf7.png)

@oliver---- can you confirm and comment on the issues.

**Comment by oliver----** [comment]
For annotations we need to register components explicitly. This has changed in Texture, because it overrides the fall-back component for unsupported inline nodes.

**Comment by michael** [comment]
Yeah I saw the comment and it's fixed now. Also provided an ExtLinkComponent with a proper link. I've also just fixed the confusion of referenceManager with footnoteManager, that was my mistake.

If you have time, could you look into those two things:

- IsolatedNodes are no longer rendered in Editor
- Adding a new citation breaks: try adding a new xref for a reference (think this is related to the new context setup;)

**Comment by oliver----** [comment]
Will do

**Comment by oliver----** [comment]
I have fixed the two mentioned issues.

**Comment by oliver----** [comment]
Two things I'd like to make you aware of @michael @Integral 
- please use `export default` with the class name. Since ES6 it is not necessary to have that at the bottom. Without the line at the bottom the code is less redundant.
- as mentioned above, be aware that `Commands` must pass `context` through to the rest of the api. This is particularly important for higher-level command implementations, i.e. those which are sub-classed.

**Comment by michael** [comment]
Thank you! Works perfectly. One question: When in the reader, clicking on an isolated node highlights it, do we want that, or somehow disable these selections? I mean such a selection would be fine, but you should be able to clear it by clicking somewhere else.

Thanks for the hints regarding export and context.

**Comment by michael** [comment]
Can we just not render the isolated node if `this.props.disabled === true`? Guess that would feel best, in terms of a reader. Currently you can't make a selection inside a caption.

**Comment by oliver----** [comment]
You can try, by changing TextureContainerEditor.getNodeComponent()

**Comment by michael** [comment]
We are good here. Closing.
