### ISSUE TITLE
Find a project name

### ISSUE THREAD

**Issue by michael** [substance/texture#57]
Let's collect name ideas here, for the ultimate naming of the project. Important: The name should be somewhat universal for a front-end toolset that involves authoring, reviewing, copy-editing, reading, etc.

Possible Names (some are already taken but I listed them as they may inspire other names)

- **Scientist™** - current working title - playful, makes the software a bit more like your friend.
- **Ken™** -  as an analogy to knowledge production (to ken = to know)
- **Transmission™** - of knowledge...
- **Manuscript™** - already used (Manuscript.app), would be very descriptive..  as all tasks around a 
- **Softcopy™** - what we do here is soft-copy editing, isn't it? ;)
- **Phrase™** - it's all about the phrases.
- **Type™** or **Substance Type™** - content production system by Substance
- **Script™** - short, but probably also over-used and not unique enough for a good brand
- **Letterpress™** - a digital letterpress this time  ;), maybe doesn't fit so well for the author role
- **Matter™** - would relate nice to Substance as a universal word for the essential (nitty gritty,..), also used elsewhere quite often
- **Scholar™** or **Substance Scholar™** the Substance Scholar suite. Mhh.. Not too catchy... also more suiteable for a platform than a toolkit
- **Pen™** - more author-centric, too artsy... 

Think of it also as a software module, when using it:

```js
$$(Manuscript, {
  mode: 'author',
  documentId: 'doc-1'
})
```

Please help! ;)

**Comment by Integral** [comment]
Also think about old compose, composer, compositor etc.

**Comment by michael** [comment]
Not general enough. We need a name that also includes a reader.

**Comment by gnott** [comment]
- Easel
- Speedway
- JATSzilla

**Comment by michael** [comment]
- Ed (short for Electronic Documents)

**Comment by michael** [comment]
- **Texture™**

**Comment by chmike** [comment]
Hi. Texture is nice but unfortunately also match a popular unrelated concept in graphic. One of the name selection criteria should be a direct match and find with web search engines. The programming language Go is very frustrating on this regard.

**Comment by chmike** [comment]
Here is my humble proposal **scholarTextPad**.
