### ISSUE TITLE
Allow alternative reference citation styles

### ISSUE THREAD

**Issue by JGilbert-eLife** [substance/texture#571]
At present, Texture supports number citations, e.g.

For reading out neuronal activity in vivo, the combination of calcium imaging of neuronal populations (​[1]) with two-photon microscopy ([2]​), has proved its utility because of its high selectivity, good signal-to-noise ratio, and depth penetration in scattering tissues (​[3-9]).

However, eLife and other journals use author, year citations. In our style that sentence would read:

For reading out neuronal activity in vivo, the combination of calcium imaging of neuronal populations (​Yuste and Katz, 1991) with two-photon microscopy (Denk et al., 1990​), has proved its utility because of its high selectivity, good signal-to-noise ratio, and depth penetration in scattering tissues (​Yuste and Denk, 1995; Cossart et al., 2003; Zipfel et al., 2003; Helmchen and Denk, 2005; Svoboda and Yasuda 2006; Ji et al., 2016; Yang and Yuste, 2017).

Our style is to use 'Smith, 1990' for articles of one author, 'Smith and Jones, 2000' for articles with two authors and 'Smith et al., 2010' for articles with three or more authors. Other journals employ different variations of author, year citations.

We would require support for this citation style. In addition, reference lists in eLife articles are presented in alphabetical order, with the underlying rids for references enumerated in the order the references appear, e.g.

```
 <ref-list>
            <title>References</title>
            <ref id="bib1">
                <element-citation publication-type="journal">
                    <person-group person-group-type="author">
                        <name>
                            <surname>Briggman</surname><given-names>KL</given-names>
                        </name>
                        <name>
                            <surname>Bock</surname><given-names>DD</given-names>
                        </name>
                    </person-group>
                    <year iso-8601-date="2012">2012</year>
                    <article-title>Volume electron microscopy for neuronal circuit
                        reconstruction</article-title>
                    <source>Current Opinion in Neurobiology</source>
                    <volume>22</volume><fpage>154</fpage><lpage>161</lpage>
                    <pub-id pub-id-type="doi">10.1016/j.conb.2011.10.022</pub-id>
                    <pub-id pub-id-type="pmid">22119321</pub-id>
                </element-citation>
            </ref>
            <ref id="bib2">
                <element-citation publication-type="journal">
                    <person-group person-group-type="author">
                        <name>
                            <surname>Brown</surname><given-names>E</given-names>
                        </name>
                        <name>
                            <surname>Mantell</surname><given-names>J</given-names>
                        </name>
                        <name>
                            <surname>Carter</surname><given-names>D</given-names>
                        </name>
                        <name>
                            <surname>Tilly</surname><given-names>G</given-names>
                        </name>
                        <name>
                            <surname>Verkade</surname><given-names>P</given-names>
                        </name>
                    </person-group>
                    <year iso-8601-date="2009">2009</year>
                    <article-title>Studying intracellular transport using high-pressure freezing and
                        Correlative Light Electron Microscopy</article-title>
                    <source>Seminars in Cell &amp; Developmental Biology</source>
                    <volume>20</volume><fpage>910</fpage><lpage>919</lpage>
                    <pub-id pub-id-type="doi">10.1016/j.semcdb.2009.07.006</pub-id>
                    <pub-id pub-id-type="pmid">19660566</pub-id>
                </element-citation>
            </ref>
            <ref id="bib3">
                <element-citation publication-type="journal">
                    <person-group person-group-type="author">
                        <name>
                            <surname>Bushong</surname><given-names>EA</given-names>
                        </name>
                        <name>
                            <surname>Johnson</surname><given-names>DD</given-names>
                        </name>
                        <name>
                            <surname>Kim</surname><given-names>KY</given-names>
                        </name>
                        <name>
                            <surname>Terada</surname><given-names>M</given-names>
                        </name>
                        <name>
                            <surname>Hatori</surname><given-names>M</given-names>
                        </name>
                        <name>
                            <surname>Peltier</surname><given-names>ST</given-names>
                        </name>
                        <name>
                            <surname>Panda</surname><given-names>S</given-names>
                        </name>
                        <name>
                            <surname>Merkle</surname><given-names>A</given-names>
                        </name>
                        <name>
                            <surname>Ellisman</surname><given-names>MH</given-names>
                        </name>
                    </person-group>
                    <year iso-8601-date="2015">2015</year>
                    <article-title>X-ray microscopy as an approach to increasing accuracy and
                        efficiency of serial block-face imaging for correlated light and electron
                        microscopy of biological specimens</article-title>
                    <source>Microscopy and Microanalysis</source>
                    <volume>21</volume><fpage>231</fpage><lpage>238</lpage>
                    <pub-id pub-id-type="doi">10.1017/S1431927614013579</pub-id>
                    <pub-id pub-id-type="pmid">25392009</pub-id>
                </element-citation>
            </ref>

```

**Comment by lollopus** [comment]
I second this request, which is critical to increase the beta user base

**Comment by lpanebr** [comment]
There's also another use-case for Author-Date citation that I think is relevant and quite frequent in social and humanities journals. In this use-case Authors are cited directly and a sentence could read:

Denk et al., 1990, have proved that Yuste and Katz, 1991 technique of combining calcium imaging of neuronal populations with two-photon microscopy shows [...]

**Comment by JGilbert-eLife** [comment]
A quick thought on this - the style for references is set at the journal level, so when using Texture as a production tool, one would not be expected to have to change the referencing style halfway through working on an article. However, authors may need to flip between different styles of referencing when submitting to different journals. This might mean there is some requirement for on-the-fly changing of referencing style.

I imagine the trickiest part of that is that it will affect the order in which the references are displayed in the reference list (alphabetical vs order in which the citations appear in the text).

**Comment by JGilbert-eLife** [comment]
Another item to note as part of incorporating alphabetical reference lists/name-year citations: we will need to be able to differentiate between citations with the same names and years using a, b, c etc notation.

Smith, 1990a
Smith, 1990b
Smith and Jones, 2000a
Smith and Jones, 2000b
Smith et al., 2012a
Smith et al., 2012b

**Comment by michael** [comment]
We will start working on this in the 2.0 milestone, utilising Citeproc.js. We plan to have initial support for CSL/Citeproc.js in 2.0, but add improvements for the 3.0 milestone.

@JGilbert-eLife can you check if the eLife citation style can be reached using CSL/Citeproc.js?

**Comment by Melissa37** [comment]
>can you check if the eLife citation style can be reached using CSL/Citeproc.js?

Is this what you mean?
https://www.zotero.org/styles?q=id%3Aelife

**Comment by lpanebr** [comment]
> And wait... why is there actually a style called eLife? Shouldn't you better use an existing more widely supported style?

ahhahahaha... We provide services to 40+ journals and I ask that question every day for most of our journals.. Thankfully with time we are able to convince our editors to adopt one of the several international standard citations widely available.

**Comment by Melissa37** [comment]
>I ask that question every day for most of our journals

Same here - editorial preferences regarding punctuation and journal abbreviations make it really hard to conform to all the specifics in one style. We tell our authors to give us what they want and we'll sort it out, but people still like to have a style to cling to. It's not about the actual semantics of the information, it's all about the human-reading presentation of that content.

>And wait... why is there actually a style called eLife? Shouldn't you better use an existing more widely supported style?

We did not request it, CSL created it and told us and rather than waste their work and annoy authors who want to use it, we said, thanks for doing that!

CSL do not have some things we cover, such as they don't differentiate preprints as an article type.

**Comment by michael** [comment]
> Same here - editorial preferences regarding punctuation and journal abbreviations make it really hard to conform to all the specifics in one style. We tell our authors to give us what they want and we'll sort it out, but people still like to have a style to cling to. It's not about the actual semantics of the information, it's all about the human-reading presentation of that content.

Another sign we need overridable labels. :(  I willl provide that feature, but recommend to use it as little as possible. The automatic label generation is much cheaper and less error prone. And then you can move things around and the labels get updated immediately.

> CSL do not have some things we cover, such as they don't differentiate preprints as an article type.

That's not a problem, we can have 2 types and then internally convert it to the shared CSL-type for rendering via Citeproc. What is important is that you are happy with the citation labels generated by Citeproc.

**Comment by jalperin** [comment]
Whatever a journal's preferences are, I think supporting CSL styling is the only sensible thing to do. There are some basic labeling options that the Zotero and Mendeley plugins for Word provide. These include: 
- suppress author (just include year) 
- prefixes (free text form, to include things like: "i.e., "; "e.g."; "see also")
- suffix (free text form)
- page numbering (this can almost always also be achieved with the suffix, but there are "styles" for how these are handled). 

Zotero just provides "suppress author" but does not support "Alperin (2018)" as an auto-generated label. They expect the author to type "Alperin" and the auto-label will just be (2018).

**Comment by michael** [comment]
See citation styles feature in requirements document. Closing.
