### ISSUE TITLE
[Question] What is the interplay (if any) between Texture and lens reader?

### ISSUE THREAD

**Issue by meinbrodt** [substance/texture#574]
Hello, 

I have another question. Is there any interplay between Texture and the lens reader or are they using both completely different code bases? 

Since both are visualizing NLM XML flavoured documents (Texture allows also for their editing of course) I'm wondering if there is any code reusage between these two project. 

Regards, Matthias

**Comment by michael** [comment]
Hi!

Currently Texture is a new codebase, and Lens code uses a bit outdated Substance version. We are working however on joining the two codebases. At first, to just have a classic Texture Reader (one panel) but later bring back Lens functionalities (split pane interactions).
