### ISSUE TITLE
Add MultiSelect Form Element

### ISSUE THREAD

**Issue by michael** [substance/texture#581]
For tasks like associating affiliations with authors we need a multi-select input widget.

![image](https://user-images.githubusercontent.com/2931/42033067-e8ac260e-7adb-11e8-9720-79eb21f1aa4a.png)

```js
$$(MultiSelect, {
  selectedOptions: ['aff1', 'aff2'],
  availableOptions: [
    {id: 'aff1', text: 'Linz University, Austria'},
    {id: 'aff2', text: 'Vienna University, Austria'},
    {id: 'aff3', text: 'Graz University, Austria'}
  ],
  selectorLabel: 'Add Affiliation'
})
```

When changes are made to the selection, an action should be sent up.

```js
this.send('updatedSelection', ['aff1', 'aff2', 'aff3'])
```

Regarding layout:

- Remove icons should be aligned and move to the right according to the longest item
- selector should just be a regular native select box (custom style but once clicked shows the regular dropdown)

**Comment by Integral** [comment]
See #582. Perhaps I need a mockup to be able to style it with more details.
