### ISSUE TITLE
Implement API's with support for group authors

### ISSUE THREAD

**Issue by michael** [substance/texture#585]
Please implement in the following order:

- [x] [Get authors](https://github.com/substance/texture/blob/master/docs/TextureAPI.md#authors)
- [x] [Get affiliations](https://github.com/substance/texture/blob/master/docs/TextureAPI.md#affiliations)
- [x] Add author
- [x] Update author/group author
- [x] Delete author/group author
- [x] Add/Update/Delete affiliation record
- [x] Add award/Update/Delete award (model not yet ready)

Bonus tasks: 

- [ ] Ensure the TextureAPI.md doc is consistent. So improve examples if necessary. I guess we also need one formal API description (describing all available props) and then an example.

NOTE: we should provide plain old javascript objects for the API, so for the getters toJSON() should be enough for most cases. And for saving we will take objects anyways.

**Comment by michael** [comment]
The internal JATS model for group authors looks like this for reference. However you only have to deal with the pubMetaDb records, the converters I'm implementing will do the rest.

```xml
  <contrib contrib-type="group" equal-contrib="yes" corresp="no" deceased="no">
    <collab>
      <named-content content-type="name">The Mouse Genome Sequencing Consortium</named-content>
      <xref ref-type="aff" rid="aff2"/>
      <xref ref-type="award" rid="fund1" />
      <contrib-group contrib-type="group-member">
        <contrib contrib-type="person">
          <name>
            <surname>Kelly</surname><given-names>Laura A.</given-names>
          </name>
          <role>Writing Group</role>
          <xref ref-type="aff" rid="aff2"/>
        </contrib>
        <contrib contrib-type="person">
          <name>
            <surname>Randall</surname><given-names>Daniel Lee</given-names>
            <suffix>Jr.</suffix>
          </name>
          <role>Lab Group</role>
          <xref ref-type="aff" rid="aff3"/>
        </contrib>
      </contrib-group>
    </collab>
  </contrib>
```

**Comment by michael** [comment]
We also need:

[ ] Model (EntityDatabase.js) and Converters for keywords
[ ] Model (EntityDatabase.js) and Converters for award

I've added the XML to the kitchen sink.

**Comment by Integral** [comment]
Hey @michael,
I was thinking whatever we need a validator for creation API? Like when you add entities via pubMetaDbSession you can pass any properties and they will stay in DB. We can cut off anything not related to schema. What do you think?

**Comment by michael** [comment]
We have a model already for the entities, so any properties that are not in the schema should be deleted anyways. But we can think about better errors and warnings etc. according to schema. However other things have priority I think.

**Comment by Integral** [comment]
Only docs are left.
