### ISSUE TITLE
Introduce Toolbar for MetadataEditor

### ISSUE THREAD

**Issue by michael** [substance/texture#609]
We want to provide a dedicated toolbar for the metadata editor, to allow quick access to related tasks (e.g. adding entities such as authors, affiliations etc.)

The toolbar will include a mode switcher (right side) to be able to switch between editor, metadata editor and reader (=preview) modes.

![image](https://user-images.githubusercontent.com/2931/42836385-300c9f1e-89fb-11e8-9cb9-8d1f6a2bcd68.png)

**Comment by michael** [comment]
Also see #610 for more UI/UX ideas including batch actions.

**Comment by michael** [comment]
@Integral for the coming days.. could you do a first iteration on this:

- [ ] Create a tool for the mode switcher (dropdown). At first let's just use the app toolbar as it is, but use fixed positioning to place it over the editor toolbar in the right upper corner (that's fine for a start i think)
- [ ] Add tools in Metadata editor for adding a new Author, Editor, Keyword, Award, Reference, Group etc.

**Comment by oliver----** [comment]
We have this now.
