### ISSUE TITLE
Styling needed

### ISSUE THREAD

**Issue by michael** [substance/texture#612]
We implemented these cards, and the UX feels quite nice. It allows quick in-place editing of references too. However I'm failing to give this a minimal consistent style. 

Desired:

- minimal buttons for adding and removing of authors/editors
- consistent button style
- position of the warning sign for required fields
- way to reveal the warning message (I guess we don't want to display all the time as quite noisy)
- ideally avoid the blue color for buttons, looks nicer on the eye and less color clash (warning color vs blue)

![image](https://user-images.githubusercontent.com/2931/42845624-d5f4558c-8a16-11e8-9be3-6bdf77f5e607.png)

@NickDuffield could you help? ;) Maybe you have some ideas...

**Comment by michael** [comment]
The overall QC pane looks like this atm:

![image](https://user-images.githubusercontent.com/2931/43149348-84a4ac1c-8f67-11e8-8815-a5d140f9c738.png)

**Comment by oliver----** [comment]
IMO this issue is not specific enough to be kept open.
For sure we need some general style iterations.
