### ISSUE TITLE
Import and display article record (including pub history) in MetadataEditor

### ISSUE THREAD

**Issue by michael** [substance/texture#614]
This input is already in the kitchen sink, but we need to make it editable.

```xml
      <pub-date id="date-5" publication-format="print" date-type="pub" iso-8601-date="1999-01-29">
        <day id="day-5">29</day>
        <month id="month-5">01</month>
        <year id="year-5">1999</year>
      </pub-date>
      ...
      <history id="history-1">
        <date id="date-1" date-type="received" iso-8601-date="1998-01-05">
          <day id="day-1">05</day>
          <month id="month-1">01</month>
          <year id="year-1">1998</year>
        </date>
        <date id="date-2" date-type="rev-request" iso-8601-date="1998-03-14">
          <day id="day-2">14</day>
          <month id="month-2">03</month>
          <year id="year-2">1998</year>
        </date>
        <date id="date-3" date-type="rev-received" iso-8601-date="1998-05-24">
          <day id="day-3">24</day>
          <month id="month-3">05</month>
          <year id="year-3">1998</year>
        </date>
        <date id="date-4" date-type="accepted" iso-8601-date="1998-06-06">
          <day id="day-4">06</day>
          <month id="month-4">06</month>
          <year id="year-4">1998</year>
        </date>
      </history>
```

Plan is the following: Introduce an ArticleRecord model (EntityDatabase.js), it's a singleton with a fixed id: "article-record".

```js
export class ArticleRecord extends DocumentNode {}

ArticleRecord.schema = {
  type: 'article-record',
  volume: { type: 'string', optional: false, default: '' },
  issue: { type: 'string', optional: false, default: '' },
  fpage: { type: 'string', optional: false, default: '' },
  lpage: { type: 'string', optional: false, default: '' },
  pageRange: { type: 'string', optional: false, default: '' },
  elocationId: { type: 'string', optional: false, default: '' },
  acceptedDate: { type: 'string', optional: false, default: '' },
  publishedDate: { type: 'string', optional: false, default: '' },
  receivedDate: { type: 'string', optional: false, default: '' },
  revReceivedDate: { type: 'string', optional: false },
  revRequestedDate: { type: 'string', optional: false }
}
```

So this needs to be converted on import and export. Please make sure the following criteria is fulfilled:

- [ ] we use fixed date-types (pub, received,accepted, rev-received, rev-requested)
- [x] pub-date element is used for storing publishedDate (directly inside article-meta element)
- [x] other date properties are stored inside `history`
- [x] we always use `iso-8601-date` attribute (like on import)
- [x] we create individual date fields on export if we can derive it. Valid inputs are "2018-04-03" or "2018-02" or "2018". So please just derive year, and optional month+day elements from that. Make sure that if string can not be parsed that no year,day,month elements are created, but that `iso-8601-date` attribute is set to whatever the user entered.
- [x] when `elocationId` is filled out the properties (issue,volume,fpage,lpage,pageRange) are ignored and not saved to JATS. If eLocation is set then we only store that elocation-id element. See JATS spec (`(((fpage, lpage?)?, page-range?) | elocation-id)?`)
- [x] remove old code and schema regarding content-loc (we don't need this anymore as we will keep everything in pubMetaDb), so remove ConvertContentLoc and replace it with a ConvertArticleRecord converter.

This is a special section in MetaDateEditor which is not a collection. So this will just have a model (DefaultModel I guess) and no counter on the Table of Content. So you need to adjust this code here and not render CollectionEditor but instead some other editor registered for that model type, displaying section title + EntityEditor.

```js
    SECTIONS.forEach(section => {
      let model = this.api.getModel(section.modelType)
      collectionsEl.append(
        $$(CollectionEditor, { model: model })
          .attr({id: model.id})
          .ref(model.id)
      )
    })
```

Add something like:

```js
if (model.isCollection()) { .. } else { ... }
```

**Comment by Integral** [comment]
@michael according to JATS there could be elocation-id and volume/issue. Let me know if I'm wrong.

**Comment by michael** [comment]
Yeah volume/issue is there independently. We are done here, closing.

**Comment by gro1729** [comment]
Wie wird man diese Spam-Mails wieder los?
Es reicht wohl nicht, sich aus der Liste auszutragen.

**Comment by oliver----** [comment]
@gro1729 This is github.com, not a mailing list. Probably you have registered to this repo, by clicking the "Watch" button.
If you are not able to unregister please contact github.com support
