### ISSUE TITLE
QC Mode requirements

### ISSUE THREAD

**Issue by michael** [substance/texture#618]
Requirements according to @fabiobatalha :

Journal

- journal publisher id
- journal aggregator id
- journal other id
- Title
- Subtitle
- Abbreviated title
- Translated Title
- Translated Subtitle
- other titles
- ISSN (electronic, print, other)
- publisher name

Issue

- volume
- number
- publication date
- received date
- reviewed date
- acceptance date
- Issue Title

Article

- Article Type
- Article Language
- Article ID (DOI, publisher ID, aggregator ID)
- pages (first, last)
- elocation
- translated titles
- abstract and translated abstracts
- keywords and translated keywords
- Document Type (Original Article, Review Article, etc)
  - free pub-id-type?
- Author Notes
- Editorial Notes
- Bio Notes [example](https://www.erudit.org/fr/revues/mi/2011-v16-n1-mi1826189/1006917ar/#nb1)  look for "notes biographiques"
- acknowledgements [example](https://www.erudit.org/fr/revues/rse/2011-v37-n1-rse01/1007666ar/)
 look for "remerciements"

**Comment by michael** [comment]
We'll support a great portion of it in Texture 1.0, but let's review this in Sao Paulo together and refine until everyone is happy.

**Comment by oliver----** [comment]
@fabiobatalha I will remove the sao-paolo label. Should we keep this issue? or can we turn it into more specific ones? If so, could you help me with that, i.e. create specific issues?

**Comment by michael** [comment]
Yeah please create separate ones, for everything that is missing from 1.0. Ideally with an example of XML + how the info should be displayed/edited.
