### ISSUE TITLE
References ordered alphabetically instead of numerically

### ISSUE THREAD

**Issue by soarecostin** [substance/texture#619]
Dear Team,

When citing multiple references, the order in which they appear cited is sorted alphabetically rather than numerically and sometime that results is a problem. Let me give you a few examples:

- Citing references 2, 3, 14 and 15 results in Texture displaying [14, 15, 2, 3] instead of [2, 3, 14, 15]
- Citing references 1, 2, 3, 4, 16, 17 results in Texture displaying [1, 16, 17, 2-4] instead of [1-4, 16, 17]
- Citing references 3 - 18 results in texture displaying [10-18, 3-9] instead of [3-18]

Please find attached a picture describing the third case from above, exemplified on paragraph from the Texture demo article, on the latest build.

![texture editor](https://user-images.githubusercontent.com/6401790/42945867-cd73ac06-8b69-11e8-81d5-ec0f0a3953b6.png)

Thank you for your time,

Best regards,
Costin

**Comment by oliver----** [comment]
The observed behavior was not intended, so it must be a bug in the label generator.

In case of references, we will replace the current solution with something based on citeproc.
For other citations, such as Figures and Tables we will still use the current logic.

**Comment by oliver----** [comment]
Fixed via https://github.com/substance/texture/commit/957cc6114a069727f41fb4145e1b0cc17f674cdd

**Comment by oliver----** [comment]
@soarecostin Thank you. Your report was very helpful.
