### ISSUE TITLE
Inconsistent behavior with merged cells in tables

### ISSUE THREAD

**Issue by soarecostin** [substance/texture#620]
Dear Team,

I have found that depending on how I setup some merged cells in the table, sometimes it works without any issues, other times I get an error when I try to save (Ctrl+S) and in rare cases the browser crashes.

Please see below a few examples of merged cells:

![texture editor 1](https://user-images.githubusercontent.com/6401790/42946659-b2397b4e-8b6b-11e8-8c9e-318bc189ec0f.png)
_This is the case that I can save without any issues_

![texture editor](https://user-images.githubusercontent.com/6401790/42946674-c1735f1c-8b6b-11e8-9991-96e2bf444e62.png)
_This is the case that results in a Javascript error in the console (merging happens on the last row of the table). Please see a screenshot with the error below_

![capture](https://user-images.githubusercontent.com/6401790/42946700-d3fa4e2a-8b6b-11e8-8cf8-105d874f070e.PNG)

![texture editor 2](https://user-images.githubusercontent.com/6401790/42946711-e05dc778-8b6b-11e8-9916-c0a886896685.png)
_This is the case where the browser completely freezes when I try to save (an entire row is merged, but not the last row in the table)_

Thank you very much for looking into this

**Comment by michael** [comment]
Thanks for reporting, we'll try to address this for the 1.0 release.

**Comment by oliver----** [comment]
Yep. Thanks for the very nice report!
I am starting to work on this.

**Comment by oliver----** [comment]
FIxed via #745

**Comment by oliver----** [comment]
@soarecostin Thanks. This was very helpful.

**Comment by soarecostin** [comment]
Great! Thank you for the fix!
