### ISSUE TITLE
Is it possible to import and use node.js modules?

### ISSUE THREAD

**Issue by meinbrodt** [substance/texture#624]
Hi, 

I wanted to import an external node.js module while tinkering a little bit with texture using 

```
const <moduleName> = require('<pathToModule>')
```

Running `node start` builds the web based texture version without any errors,  however, when I open the page on localhost I always get a `Uncaught ReferenceError: require is not defined` at the exact position in the code where I inserted the require statement. 

Any help on how to solve this problem would be highly appreciated. 

Thanks and regards, Matthias

**Comment by michael** [comment]
We use ES-NEXT style imports in all client-code. So this would translate to:

```js
import moduleName from './moduleName'
```
