### ISSUE TITLE
More metadata editor improvements before building a demo

### ISSUE THREAD

**Issue by michael** [substance/texture#631]
Just coming up with a list of (more or less prioritised tasks):

- [x] Get toolbar in place (Add buttons with dialog e.g. for references, Mode switcher) see #609 
- [x] Subjects are broken (nothing displayed in EntityEditors)
- [x] Glitch: Currently when you finish changing a property of an entity, the selection gets restored in a different place and scrolled to, e.g. try putting cursor into fig caption and then update author
- [x] Add language selector for keywords and subjects (currently we have a field for the language code, but select box based on available languages + label is better)
- [x] Use custom SelectInput implementation (and use overlay app state logic)
- [x] Focus and scrollTo after inserting a new author/reference/etc. in metadata panel
- [x] Show all options in SelectInput (currently selected option is not shown in the dropdown)

Not before we have joined pubMetaDb and document:

- [x] Remove subj-group from the DOM after import (like we do with keywords already), let's not store the order for now, i think it's enough to use type index as we do with keywords

**Comment by oliver----** [comment]
> - [ ] Remove contrib-group + contrib elements from InternalArticle, instead put authors and editors inside article-record
- [ ] Remove ref-list from DOM after import (again we can use type index) as references are managed in the entity db, so to have them in the DOM is redundant and needs extra book-keeping (such as creating DOM elements on insertion of references etc. this will simplify API implementation of addReference etc.)

These two issues are not valid anymore, or I decided to take a different approach. In general relying on indexes should be a last resort. Everything should have a dedicated place in the document model, this makes the model easier to understand.

**Comment by oliver----** [comment]
Closing this now.
