### ISSUE TITLE
Improve handling of references

### ISSUE THREAD

**Issue by michael** [substance/texture#634]
We need to do another iteration on references to make everything work properly. We now have a quite good model underneath (e.g. ref-contrib nodes with name + optional givenName) which are used to represent individuals and groups. We need to update the CSLJSON importer / exporter to reflect that. Currently the functionality breaks on certain imports from Zotero etc.

This needs a bit of planning, which I will do once the MetadataEditor iteration is completed.

**Comment by michael** [comment]
@zuphilip are you in for helping getting this in shape? There's no big rush have time until end of September. :)

**Comment by lollopus** [comment]
Hi, I'm writing a manuscript with Stencila and came across the need to insert this reference: "The Gene Expression Nervous System Atlas (GENSAT) Project, NINDS Contracts N01NS02331 & HHSN271200723701C to The Rockefeller University (New York, NY)." This is the recommended string by the project authors themselves (see: [http://www.gensat.org/daily_showcase.jsp](url)) and I have trouble finding an appropriate reference type. For cases such as this one with little structure and no DOI I would suggest adding a generic reference type containing only a string field.

**Comment by zuphilip** [comment]
@michael Maybe a little later I have time to help, but I still have to see how other things are working out. Can you ping me again in 1-2 weeks?

**Comment by michael** [comment]
Critical issues are addressed. We need to further polish the internal model and CSL/JSON import/export.
