### ISSUE TITLE
Default name for newly created references

### ISSUE THREAD

**Issue by Integral** [substance/texture#642]
![screen shot 2018-08-03 at 14 08 08](https://user-images.githubusercontent.com/182010/43639990-c4e75178-9726-11e8-9ae9-80e59f74f90c.png)
This looks a bit ugly. I remember that we had a grey placeholders in manuscript at some point, just with name of properties which should be filled out.
@michael what do you think?

**Comment by michael** [comment]
I think we need the labels here, otherwise it's hard to scan when filled out. However I think we can remove the yellow border from the card if there are issues. It's enough to have the warning sign.

**Comment by oliver----** [comment]
IMO this is a deficiency of the bibr rendering. The validation and warnings make sense, even the yellow border is ok.
Closing this in favor of https://github.com/substance/texture/issues/684
