### ISSUE TITLE
References not saved/incompletely saved on MacOsX in both stencila and texture

### ISSUE THREAD

**Issue by lollopus** [substance/texture#643]
This issue also posted on stencila desktop repository at https://github.com/stencila/desktop/issues/68 (however these problems appear to be originating from Texture)

References are saved erratically. Sometimes they are not saved at all (I have a manuscript being edited that I can send you for testing that replicates this).

With newly created empty files, references with only their title field filled out are saved but said title is missing when reopening the file. In one instance when reopening the file I got the following error:

Importing JATS
Parse XML
Validate JATS
<element-citation> is incomplete. Schema: (inline-supplementary-material|related-article|related-object|hr|string-date|bold|fixed-case|italic|monospace|overline|overline-start|overline-end|roman|sans-serif|sc|strike|underline|underline-start|underline-end|ruby|alternatives|inline-graphic|private-char|chem-struct|inline-formula|label|tex-math|mml:math|abbrev|milestone-end|milestone-start|named-content|styled-content|annotation|article-title|chapter-title|collab|collab-alternatives|comment|conf-acronym|conf-date|conf-loc|conf-name|conf-sponsor|data-title|date|date-in-citation|day|edition|email|elocation-id|etal|ext-link|fpage|gov|institution|institution-wrap|isbn|issn|issn-l|issue|issue-id|issue-part|issue-title|lpage|month|name|name-alternatives|object-id|page-range|part-title|patent|person-group|pub-id|publisher-loc|publisher-name|role|season|series|size|source|std|string-name|supplement|trans-source|trans-title|uri|version|volume|volume-id|volume-series|year|fn|target|xref|sub|sup|x)+
<element-citation publication-type="data">
</element-citation>
Transform JATS -> TextureArticle
Validate Dar Article
Transform TextureArticle -> InternalArticle
Validate Texture Article
Essentially saving behavior is erratic. I deem this issue as **blocking/high priority** since it makes using stencila or texture on real manuscript drafting impossibile, even as a willing beta tester.

**Comment by michael** [comment]
@lollopus we are aware of these issues, and as you say they are originating from Texture. We are working on getting all this stable until September, when we plan to release Texture 1.0, and also update Stencila.

**Comment by lollopus** [comment]
Good to know. I'd like to help with beta testing but at this stage I'll wait for your September release. cheers, L
