### ISSUE TITLE
copy/paste of text containing quotation marks from texture/stencila to other editors needs improvment

### ISSUE THREAD

**Issue by lollopus** [substance/texture#644]
if you copy this text from texture/stencila:

> test "test"

to word/textedit/pages in MacOsX you get:

> test & quot;test& quot;
(i added the spaces after the &s manually)

**Comment by oliver----** [comment]
Thanks for reporting.

**Comment by oliver----** [comment]
Interesting: other applications apparently are not decoding HTML-encoded content.
I'll try to disable the encoding for the Clipboard and see where we get with that. Hopefully we are not breaking general HTML parsing with that.

**Comment by oliver----** [comment]
@lollopus Without the encoding we are good with content as you suggest.
