### ISSUE TITLE
Video demonstrating new Metadata Editor

### ISSUE THREAD

**Issue by michael** [substance/texture#648]
Video Script (Priorities)

- [ ] Add new author and assign affiliations and awards
- [ ] Modify article record (proper labels are missing here)
- [ ] Add new author group and assign author
- [ ] Add/edit keywords 
- [ ] Add subject (with translation)
- [ ] Add/edit/delete references
- [ ] Demonstrate how warnings are displayed for required fields
- [ ] Demonstrate how you can quick edit (and on demand reveal all available fields)

Nice to have:

- [ ] Translations for Title / Abstract
- [ ] Edit figures in metadata panel (caption, title)
- [ ] Edit footnotes

**Comment by oliver----** [comment]
@michael I have reworked the schema and converter, which is great. However this needs to wait a little longer, until things are ironed out.

**Comment by michael** [comment]
@oliver---- i just had a look. Things are looking great generally. I think we just nail a few more easy to fix things and then I record the video. It's just important to demo the concepts and get green light for the UI/UX.

**Comment by michael** [comment]
Done.
