### ISSUE TITLE
Add keyboard shortcuts for metadata editor

### ISSUE THREAD

**Issue by michael** [substance/texture#672]
Add author: CommandOrControl+alt+a
Add editor: CommandOrControl+alt+a
Add group: CommandOrControl+alt+g
Add affiliation: CommandOrControl+alt+f
Add award: CommandOrControl+alt+w
Add keyword: CommandOrControl+alt+k
Add subject: CommandOrControl+alt+s
Add footnote: CommandOrControl+alt+o
Add reference: CommandOrControl+alt+r

**Comment by Integral** [comment]
@michael do you know that currently it works only when you put a focus on some input?

**Comment by Integral** [comment]
@michael unfortunately there are more problems
some of combos are not working in chrome, for instance if you do CommandOrControl+alt+w it will do Cmd+W, e.g. it will close tab. The same thing happens with some other combos. Any ideas?

**Comment by Integral** [comment]
I found didn't find enough free combos in CommandOrControl+Alt space... So in #710 we have this:
Add author: CommandOrControl+Shift+A
Add editor: CommandOrControl+Shift+E
Add group: CommandOrControl+Shift+P
Add organisation: CommandOrControl+Shift+O
Add award: CommandOrControl+Shift+Y
Add keyword: CommandOrControl+Shift+K
Add subject: CommandOrControl+Shift+S
Add footnote: CommandOrControl+Shift+F
Add reference: CommandOrControl+Shift+L

But I think that we should need to register global key handler as you said and reject any native behaviour and go back to CommandOrControl+Alt space...

**Comment by oliver----** [comment]
>Let's just use other combos that don't close the window

I guess this is not a good decision.
We are not in an urgent need to get this 'nailed' in a hurry. Instead we should invest our time into work that brings us forward.

I'd say this is blocked until we have the global event handling.

**Comment by Integral** [comment]
Agree. Please keep in mind that besides of browser there are browser extensions which could also use ANY key combos ;)

**Comment by oliver----** [comment]
Ok, gotcha. I guess if we stop up-bubbling keydown events, the browser and plugins should not receive anything.

**Comment by oliver----** [comment]
Let's try.

**Comment by oliver----** [comment]
@Integral do we have an issue for this global event handling already?

**Comment by oliver----** [comment]
I don't think that all originally suggested shortcuts are good: Cmd+Alt+F is for search, Cmd+Alt+S is probably better related to saving...

**Comment by oliver----** [comment]
Beyond that the obstacles are fixed via #783
