### ISSUE TITLE
Keyboard shortcuts no longer shown

### ISSUE THREAD

**Issue by michael** [substance/texture#674]
Somehow keyboard shortcuts are not displayed anymore in the tools. 

@Integral maybe you want to take a look, if you have problems I take this over.

**Comment by oliver----** [comment]
Probably a regression since pulling Tools and stuff out of substance core

**Comment by Integral** [comment]
While I'm a bit confused by [this comment](https://github.com/substance/texture/blob/master/src/kit/ui/ToggleTool.js#L57) I did try to revert this functionality here: #717

**Comment by oliver----** [comment]
Hmmm. I agree. That comment does not bring much ;)

**Comment by oliver----** [comment]
@Integral you can merge. Thx.

**Comment by Integral** [comment]
Done, thanks.
