### ISSUE TITLE
Provide a select box for Licenses

### ISSUE THREAD

**Issue by michael** [substance/texture#696]
Use a constant (ArticleConstants.js) for now to register licenses:

```js
LICENSES = [
{
  id: 'http://creativecommons.org/licenses/by/4.0/'
  name: 'CC BY 4.0',
},
{
  id: 'https://creativecommons.org/licenses/by-sa/2.0/',
  name: 'CC BY-SA 2.0'
}
]
```

Here we should display a select box instead. The URL (=license id) is used as value.

![image](https://user-images.githubusercontent.com/2931/44792360-0617a800-aba4-11e8-8d53-3c9d28331245.png)

**Comment by Integral** [comment]
Pls see #701

**Comment by michael** [comment]
Sweet thank you.
