### ISSUE TITLE
Annotations in reference title are not displayed in rendered version

### ISSUE THREAD

**Issue by michael** [substance/texture#703]
![image](https://user-images.githubusercontent.com/2931/44856085-d54f7580-ac6c-11e8-9282-ff9cd05e4153.png)

Think we need to address a few things:

- consider annotations bold, italic etc. on import
- convert them to HTML equivalents on render

@oliver---- also we should be able to control where annotations are available. E.g. we don't want to have them for properties such as volume, year, month etc.

**Comment by oliver----** [comment]
@michael yeah, that is one of the next bigger things I want to bring back: disabling 'insert/annotate' commands according to `schema.targetTypes`.

**Comment by oliver----** [comment]
@michael for the rendering we should try to share implementation with the HTML converter used for the clipboard.

**Comment by oliver----** [comment]
#738 has now brought back schema-driven command states, which is now based on Substance NodeSchema's `targetTypes` specification.

**Comment by michael** [comment]
Done via #776.
