### ISSUE TITLE
Suppress native keyboard shortcuts

### ISSUE THREAD

**Issue by Integral** [substance/texture#718]
We want to suppress or override browser/app native keyboard shortcuts sometimes. 
As a first step we want to collect different cases to decide later what approach we will take.

- CMD+Q - quit the browser/app. We want to ask user first whatever he really wants to do that or maybe save what is unsaved.
- CMD+W - for the browser it means close the current tab. Here we also need to ask user if he wants to quit.
- CMD+F - for manuscript editor we want to open our own FR dialog, while in metadata editor we want to use native FR?

**Comment by oliver----** [comment]
Superseded by #723
