### ISSUE TITLE
Saving in dev mode breaks

### ISSUE THREAD

**Issue by michael** [substance/texture#720]
Looks like vfsSaveHook needs to be adapted. archive.write expects callback but is called as promise.

@oliver---- just curious, why did we switch back to callbacks instead of the promises there? Guess for easier testing?

**Comment by oliver----** [comment]
@michael the problem with the Promises is that Chrome has removed halt-on-exception support for those, making debugging very hard. Thus, I want to wait with that until this is properly supported at least by Chrome.

**Comment by oliver----** [comment]
I have changed the DAR API to use cb as last argument. So it should be easy to fix this.

**Comment by oliver----** [comment]
Fixed via #724
