### ISSUE TITLE
Blank article is not editable

### ISSUE THREAD

**Issue by oliver----** [substance/texture#731]
Open `http://localhost:4000/?archive=blank` 

During import we need to make sure that there is at least an empty paragraph in the body.

**Comment by michael** [comment]
I think it's better to ensure one empty paragraph. We can always strip that on export.

**Comment by oliver----** [comment]
The problem with fixing on import and pruning on export is that it is hard to distinguish if a paragraph was created automatically or not. Thinking about collab, this means competing changes without user interaction. I think we would be better off without pruning, then the document 'stabilizes' after the first import.

**Comment by oliver----** [comment]
In addition to that, I guess adding a placeholder to the FlowContent model would provide a good fallback solution. I.e. if we miss something when implementing the converter we would still have a working editor.

So I'd suggest, doing both. 1. Normalize on import, and 2. let FlowContentComponent implement a strategy for empty containers.

**Comment by oliver----** [comment]
The advantage of (2) is that you implement it once. For (1) you need to catch every type.

**Comment by oliver----** [comment]
Fixed via #779
