### ISSUE TITLE
A guide-line for implementing new features

### ISSUE THREAD

**Issue by michael** [substance/texture#735]
As proposed by Oliver:

- Level 0: basic definition in Texture JATS, which must be JATS compliant and make sense on a global scope. E.g. restricting to a minimal feature set
- Level 1: Display-only component for node complying with Level 0, i.e. not editable. Then somebody could change the XML manually or with other tools, and still use Texture
- Level 2: Internal model and probably converter
- Level 3: Editor for model
- Level N - Level N+3: iterate by refining the spec (i.e. relax restrictions), display new info, model them, and make them editable.

This way we can start gradually supporting content, without 100% agreement on edge-cases etc.

Let's refine this and follow the pattern.

**Comment by oliver----** [comment]
I guess we don't need an issue for that.
