### ISSUE TITLE
Render label for model.type on each card

### ISSUE THREAD

**Issue by michael** [substance/texture#736]
I think it would be good to render a human readable type of a card, so you can see what type of info you are editing. This is particularly important for references, as it makes clear why book has different properties than a journal article.

As a first UI suggestion, I would say to put this into the top right corner. Just we need to make sure the text in card header is not overlapping. So maybe flexbox inside the header is the way to do it.

@Integral want to take this?

**Comment by michael** [comment]
Like this we could do it:

![image](https://user-images.githubusercontent.com/2931/45226967-348e3500-b2c0-11e8-88f0-f62c123731a2.png)

**Comment by Integral** [comment]
Yes, thanks.
