### ISSUE TITLE
Allow changing order of user-controlled collections

### ISSUE THREAD

**Issue by michael** [substance/texture#757]
A few collections are user controlled with regard to the order:

- authors
- editors
- keywords
- subjects

For those collection we want to enable move up / move down actions, which we will hide in an ellipsis menu.

![image](https://user-images.githubusercontent.com/2931/45266102-06425e00-b456-11e8-9737-dc246f802114.png)

**Comment by michael** [comment]
We will introduce a card-selection (=node selection inside metadata editor).

**Comment by Integral** [comment]
Fixed via #842.
