### ISSUE TITLE
api.insertNode taking a JATS content snippet, for creation of nodes

### ISSUE THREAD

**Issue by michael** [substance/texture#765]
E.g. for creating a figure or table-wrap.

**Comment by Integral** [comment]
We are working on this here: #774

**Comment by Integral** [comment]
Closing this now, PR is merged, there are problems with complex JATS structures like `collab` which holds a groups as well, so we don't want to use this approach for author/editor insertion for now.
Later we want to discuss how we can use and how we should improve this API for CLI kind of thing.
