### ISSUE TITLE
Improved UI for the manuscript view

### ISSUE THREAD

**Issue by michael** [substance/texture#815]
![image](https://user-images.githubusercontent.com/2931/45484797-a5689d80-b755-11e8-9a7e-43d018e5ded6.png)

The empty article should look like this:

![image](https://user-images.githubusercontent.com/2931/45484938-2162e580-b756-11e8-9c78-63fa465c9c8a.png)

**Comment by michael** [comment]
[Texture-Better-Layout.sketch.zip](https://github.com/substance/texture/files/2379001/Texture-Better-Layout.sketch.zip)

**Comment by Integral** [comment]
This is ended up with a big CSS refactor. I will close this issue now.
