### ISSUE TITLE
Repair eLife example document

### ISSUE THREAD

**Issue by michael** [substance/texture#819]

**Comment by oliver----** [comment]
@michael can you elaborate what this issue is about?

**Comment by michael** [comment]
I'm not sure if we want to pursue it. We just used the eLife example for demoing on the webpage: http://cdn.substance.io/texture-preview-2/

But we can also delete it and just maintain our kitchen sink, knowing that soon lot's of real-world Dars will exist that don't need to be maintained manually.

**Comment by oliver----** [comment]
Yeah. Let's drop this, because we are working with eLife very closely, and we will figure out general problems, that will go into the kitchen-sink eventually.
