### ISSUE TITLE
Fix spacing in Footnotes

### ISSUE THREAD

**Issue by oliver----** [substance/texture#832]
![image](https://user-images.githubusercontent.com/284099/45541582-c8578800-b80f-11e8-82c7-32de80fc7d17.png)

**Comment by oliver----** [comment]
Not jumpy anymore after #834 but now 'overlapping'

**Comment by Integral** [comment]
It's not there already and I hope (very much, yeah) that it will not be
there after our big css refactor

**Comment by Integral** [comment]
@oliver---- that's ok, we know about this and trying hard to improve :)

**Comment by michael** [comment]
Fixed via #847
