### ISSUE TITLE
Footnotes surface already registered

### ISSUE THREAD

**Issue by Integral** [substance/texture#837]
This happens when you trying to insert a new footnote: 
![](http://g.recordit.co/q5CKQduzCZ.gif)
And you can't edit footnotes content afterwards.

**Comment by oliver----** [comment]
Need to think about it.
But in first place we should not use Surfaces in the dropdown.
At the moment, when you open the dropdown there are two places in the manuscript where you could edit the footnote.

**Comment by Integral** [comment]
I didn't know that you can edit footnote in a dropdown, is it a bit inconsistent?

**Comment by oliver----** [comment]
Fixed via #843

Now the Footnote previews are 'readonly'
