### ISSUE TITLE
CSS: spacing between abstract and body

### ISSUE THREAD

**Issue by oliver----** [substance/texture#848]
Maybe a little bit more spacing here...
![image](https://user-images.githubusercontent.com/284099/45576207-86adf800-b876-11e8-82d8-59476e1c5bea.png)

Particularly it appears to be different to other spacings

**Comment by Integral** [comment]
Not finished yet! Just a 🐄 boy mode

**Comment by oliver----** [comment]
Ok :)

**Comment by Integral** [comment]
This is fixed now.
