### ISSUE TITLE
Cursor always stays after placeholder

### ISSUE THREAD

**Issue by Integral** [substance/texture#855]
<img width="172" alt="screen shot 2018-09-15 at 07 31 46" src="https://user-images.githubusercontent.com/182010/45582951-723f1f00-b8b9-11e8-95cc-75cb3592a57a.png">

**Comment by oliver----** [comment]
Not a bug. This is now CSS (_placeholder.css). Probably a `position: absolute;` could do the trick.

**Comment by oliver----** [comment]
@michael @Integral as you are the CSS experts I leave this to you.

**Comment by Integral** [comment]
Ah, ok, didn't know that

**Comment by Integral** [comment]
Fixed via e7f2d51.
