### ISSUE TITLE
Empty article information card shouldn't be empty

### ISSUE THREAD

**Issue by Integral** [substance/texture#857]
<img width="762" alt="screen shot 2018-09-16 at 12 41 14" src="https://user-images.githubusercontent.com/182010/45595032-e78c1c00-b9ad-11e8-80d9-55e95ade2ea2.png">

**Comment by Integral** [comment]
@michael I know that you suggestion was to use required properties again, but I have a feeling that it's a wrong approach since none of these properties could be required really.

**Comment by oliver----** [comment]
@Integral I agree, let's not abuse the 'Required Properties' feature for that, this would also trigger the validator.
Isn't this just a UI / Representation problem? Just one idea, maybe we should render a message explaining that there have been no article info entered yet?

**Comment by oliver----** [comment]
BTW, I find that it is very inconsistent ATM what cards are considered empty, and what not:

**Comment by michael** [comment]
Fixed via #874
