### ISSUE TITLE
Does not insert a figure if image has been used before

### ISSUE THREAD

**Issue by Integral** [substance/texture#858]
To reproduce:
- open `http://localhost:4000/?archive=blank`
- insert a figure
- insert a new paragraph after inserted figure
- insert a new figure using the same file again

![](http://g.recordit.co/ocu5pTCav1.gif)

**Comment by oliver----** [comment]
@Integral I'll take a look at #804 and then see if we can sort out where the issues are coming from.

**Comment by oliver----** [comment]
Can't reproduce.

The observed logs are actually not critical. 

`FIXME: bring back schema compliant tx.createTextNode()` is raised because I don't like that still a global 'defaultTextType'  is used, but which should be fine in this case (using `<p>`)

And `SchemaDrivenCommandManager` does not know about the selection where a full node is selected. This one I file fix right-away.

**Comment by oliver----** [comment]
@Integral I have just noticed, that you used the same file twice. Maybe the insert was alright, but you were thinking it failed because of the console error?

**Comment by oliver----** [comment]
Removing the bug label and closing this, as I think everything is fine now.

**Comment by oliver----** [comment]
Ah, now.
It only happens if you try to insert the same file twice.

**Comment by Integral** [comment]
Yes, do you understand why?

**Comment by oliver----** [comment]
Not yet. But I think it is not selection related, more something fishy about blob handling.

**Comment by oliver----** [comment]
Ah, I remember something. I think the file input is not triggering if the value has not changed. So we need to make sure to reset the value before opening.

**Comment by oliver----** [comment]
Fixed via e1f611ced4d7e945e5706618ee264ba79929cc83

**Comment by oliver----** [comment]
Close this when PR is merged.

**Comment by Integral** [comment]
Thank you, closing this issue now, PR is merged.
