### ISSUE TITLE
Hidden TOC sections shown in Metadata editor

### ISSUE THREAD

**Issue by michael** [substance/texture#876]
Looked like this was fixed but when I open empty article, then add a new author, they show up again and make an ugly look of the TOC.

![image](https://user-images.githubusercontent.com/2931/45705781-bf054d00-bb7a-11e8-874c-606a69fcaa7a.png)

**Comment by Integral** [comment]
Fixed via ba0a827.
Note: we are doing display none thing now, it's not very elegant, but since MetaSectionTOCEntry is Model Component that's the easiest way, otherwise we would need to make a toc renderer more robust and toc entries more dumpy.
