### ISSUE TITLE
When adding or changing RefContrib elements preview is not updated

### ISSUE THREAD

**Issue by michael** [substance/texture#877]
Think we need to employ some more listeners correctly.

**Comment by oliver----** [comment]
This is not 100% accurate:

![texture-refpreview-not-updating](https://user-images.githubusercontent.com/284099/45745614-86f51d00-bc01-11e8-8955-4506bd3ab961.gif)

- It is updating when changing an existing contrib.
- it is updating when adding and removing a contrib
- but it is not updating when changing an added contrib

**Comment by oliver----** [comment]
A workaround is to use the `More fields...` / `Less fields` toggle.

**Comment by oliver----** [comment]
I'd say this is not critical.

**Comment by oliver----** [comment]
Rather than quick-fixing this, I'd like to approach this in a different way: #881

**Comment by oliver----** [comment]
Following #881 it is most likely that in future, I will address such cases with a classical way, registering for all document changes, and the sort out dynamically if one of the contribs has changed.
So it would make sense to go for that right away, and using a Component derived from PreviewComponent, that does that checking, and triggering a re-render if needed.
