### ISSUE TITLE
Saving via Control+S BUG? (Ubuntu)

### ISSUE THREAD

**Issue by lpanebr** [substance/texture#878]
The sad part is I can't reproduce it.. :disappointed: 

I've just pulled my working copy and `npm start`ed it.

Then I edited a reference adding e-location and when I pressed CRTL+S the shell showed the errors and exited.

It happened two times but now CTRL+S just doesn't work anymore..

The log is below:
```
0 info it worked if it ends with ok
1 verbose cli [ '/home/lpanebr/.nvm/versions/node/v8.7.0/bin/node',
1 verbose cli   '/home/lpanebr/.nvm/versions/node/v8.7.0/bin/npm',
1 verbose cli   'start' ]
2 info using npm@6.4.1
3 info using node@v8.7.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle substance-texture@1.0.0-preview.3-preview.2~prestart: substance-texture@1.0.0-preview.3-preview.2
6 info lifecycle substance-texture@1.0.0-preview.3-preview.2~start: substance-texture@1.0.0-preview.3-preview.2
7 verbose lifecycle substance-texture@1.0.0-preview.3-preview.2~start: unsafe-perm in lifecycle true
8 verbose lifecycle substance-texture@1.0.0-preview.3-preview.2~start: PATH: /home/lpanebr/.nvm/versions/node/v8.7.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/lpanebr/Dropbox/work/texture/node_modules/.bin:/home/lpanebr/bin:/home/lpanebr/.pyenv/shims:/home/lpanebr/.pyenv/bin:/home/lpanebr/.rbenv/shims:/home/lpanebr/.rbenv/bin:/home/lpanebr/.pyenv/shims:/home/lpanebr/.pyenv/bin:/home/lpanebr/.rbenv/shims:/home/lpanebr/.rbenv/bin:/home/lpanebr/.nvm/versions/node/v8.7.0/bin:/home/lpanebr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle substance-texture@1.0.0-preview.3-preview.2~start: CWD: /home/lpanebr/Dropbox/work/texture
10 silly lifecycle substance-texture@1.0.0-preview.3-preview.2~start: Args: [ '-c', 'node make web -s -w -d data' ]
11 silly lifecycle substance-texture@1.0.0-preview.3-preview.2~start: Returned: code: 1  signal: null
12 info lifecycle substance-texture@1.0.0-preview.3-preview.2~start: Failed to exec start script
13 verbose stack Error: substance-texture@1.0.0-preview.3-preview.2 start: `node make web -s -w -d data`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/lpanebr/.nvm/versions/node/v8.7.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (/home/lpanebr/.nvm/versions/node/v8.7.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:927:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid substance-texture@1.0.0-preview.3-preview.2
15 verbose cwd /home/lpanebr/Dropbox/work/texture
16 verbose Linux 4.4.0-135-generic
17 verbose argv "/home/lpanebr/.nvm/versions/node/v8.7.0/bin/node" "/home/lpanebr/.nvm/versions/node/v8.7.0/bin/npm" "start"
18 verbose node v8.7.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error substance-texture@1.0.0-preview.3-preview.2 start: `node make web -s -w -d data`
22 error Exit status 1
23 error Failed at the substance-texture@1.0.0-preview.3-preview.2 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by michael** [comment]
You used the web version or the Desktop build?

**Comment by lpanebr** [comment]
Web version started from the command line with `npm start`

**Comment by michael** [comment]
We'll check and make sure this is addressed for 1.0! Just give us some time as we don't have a Linux at hand atm.

**Comment by michael** [comment]
Can you also provide screenshot of the app, which exact URL etc. We had a case with Fabio, which was related to saving. Like that the dev server crashes in some circumstances on Ubuntu. Just to verify if it is the same problem.

**Comment by lpanebr** [comment]
I did some test again and found looking at the DevTools that:

1. there are some warnings when I open the app
![image](https://user-images.githubusercontent.com/129185/45724540-13192d00-bb8d-11e8-93c5-2adf96eb1e2a.png)


2.  the CTRL+S binding is getting triggered and the JATS document is generated in the DOM
![image](https://user-images.githubusercontent.com/129185/45724454-b158c300-bb8c-11e8-89d2-f7c4237d6cb9.png)

3. The crash did not happen again. However the file `data/kitchen-sink/manuscript.xml` does not get saved in the file system.
![image](https://user-images.githubusercontent.com/129185/45724498-e82ed900-bb8c-11e8-9fc0-35d79f808359.png)

Let me know if there's any specific test I can make.. 

Ah, speaking of tests when I run `npm tests` it runs fine and all tests pass.

**Comment by oliver----** [comment]
Just saw that there is a `package-lock.json`. This might also be a source of problems.
As this npm feature is very new, and not ironed out, we are not using it. Unfortunately, you do it properly or disable it completely, otherwise strange things may happen.
Will add an `.npmrc` into the repo disabling this as suggested in https://codeburst.io/disabling-package-lock-json-6be662f5b97d , so we are sure that we do not see issues caused by an outdated package lock.

**Comment by oliver----** [comment]
Shifting this, because we don't know how to tackle it at the moment.
But leaving it open, so that we do not forget.

**Comment by lpanebr** [comment]
Thank you. 
I've:
 - pulled to get the save button on the toolbar
 - removed the `package-lock.json` file

The crash has not happened again but the problem persists:
 - the JATS document gets generated in the DOM (I see it via DevConcole) but the `data/kitchen-sink/manuscript.xml` does not get saved in the file system (and permissions area fine).

I guess It's something ubuntu related but I've no clue as how to help debug it and provide more feedback. Sorry. :-(

Maybe @michael can take a look during the SciELO 20 years meeting next week ;-)

**Comment by oliver----** [comment]
We will definitely have a look! :)

**Comment by oliver----** [comment]
See u there!

**Comment by lpanebr** [comment]
ow yeah.. you'll be there too. Nice. :-)

**Comment by Integral** [comment]
@lpanebr we just tried out latest version of texture on latest lts version of Ubuntu and it's working fine.
We will release 2.0 in the end of the month, but currently you can build a latest version yourself and try it out. Please open a new issue if you'll find some errors.
