### ISSUE TITLE
Rethink implementation for trigger updates on nodes with relationships

### ISSUE THREAD

**Issue by oliver----** [substance/texture#881]
At the moment we have established a mechanism that 'marks' nodes as dirty if a node has changed that is referenced via a relationship (child, children, one, many): https://github.com/substance/texture/blob/ddab0afaf2ea5998e27f2622ff9714b8366ef119/src/kit/app/DocumentObserver.js#L31-L44
This did the trick for us to quickly solve some updating problems in the beginning.

After some time we found out, that this logic is not working yet: #877 
Also I saw a lot of undesired 'collateral' updates triggered this way.

Altogether, I think we are on a wrong track here, and we should apply a less 'smart' approach. 

For example, the preview for references should be updated when an author has been added or removed, or their name has changed. This could be done less magically by using a dedicated Component for this preview, which registers for updates appropriately.

**Comment by michael** [comment]
Oh one more thing to update: After an affiliation is added, all SelectInputs should be updated with the new record. Currently you can't select a newly created affiliation right away in the Author cards.

**Comment by oliver----** [comment]
Better track this separately.

**Comment by Integral** [comment]
@michael this is other issue and I can't confirm it, it's working for me (in browser)

**Comment by michael** [comment]
@Integral true, it is working now. Forget it.

**Comment by oliver----** [comment]
Closing this. As the decision is final for me. No fancy updates. This is not needed often, so better to implement this canonically.
