### ISSUE TITLE
Try to prevent selections on rendered content or app-chrome

### ISSUE THREAD

**Issue by oliver----** [substance/texture#882]
![texture-prevent-selections-on-rendered-content](https://user-images.githubusercontent.com/284099/45747545-6bd8dc00-bc06-11e8-81d0-a4d0792a1b79.gif)

**Comment by michael** [comment]
Yeah I also observed this. In order not to overload click areas, one option we also have is to put a dedicated 'handle' area, where a card can be selected. E.g. in top left / or top right corner corner. This could also serve as a drag+drop handle if we wanted that.

Could be stlyed like this.

![image](https://user-images.githubusercontent.com/2931/45754105-fdeadf80-bc1a-11e8-827e-abe89775d4ee.png)

**Comment by oliver----** [comment]
Just tried out stopPropgation + preventDefault on the CardComponent.el, which solves the problem.
This works in Chrome, but might cause problems in other browsers: once they then had not triggered click() anymore.

**Comment by michael** [comment]
Cool, let's keep as is for now. I'd like to see if people like this approach or if there's confusion and we need to act.
