### ISSUE TITLE
Minor: Focus border is shown when clicking a FootnotePreview

### ISSUE THREAD

**Issue by michael** [substance/texture#885]
![image](https://user-images.githubusercontent.com/2931/45754911-40152080-bc1d-11e8-9af0-2a01a588a51b.png)

**Comment by michael** [comment]
The style is displayed for focused contenteditables. Here we have `contenteditable="false"` but when you click there still seems to be a :focus, which adds the border.

**Comment by michael** [comment]
Taking care of this now.

**Comment by oliver----** [comment]
Maybe before starting something new, could you pls review #862?

**Comment by michael** [comment]
Oh overlooked. Will do.

**Comment by michael** [comment]
Fixed via #911.
