### ISSUE TITLE
The insert figure file picker does not filter for image types

### ISSUE THREAD

**Issue by michael** [substance/texture#892]
Reported by Giuliano. @Integral is that easy to do? For what image types do we want to filter?

**Comment by Integral** [comment]
It's not so easy actually since in browser you can do that. So we will need somehow to override default electron file dialog with something custom. I mean you can configure that easily in electron, but we will need to intercept that call somehow. I would suggest to shift this task or at least make it low priority.

**Comment by oliver----** [comment]
Ok. If it takes a bit of technical evaluation, let's shift.
Can we make the other side more robust? I.e. that it filters non-image files?

**Comment by Integral** [comment]
@oliver---- not sure what you mean

**Comment by oliver----** [comment]
I mean, if we are ATM not able to control the native file dialog, then we should at least not allow to add assets as figures. I.e. filter the result of the dialog to have only images.

**Comment by Integral** [comment]
I think it is fixed via ddab0af.

**Comment by Integral** [comment]
Sorry, I think this issue was about type restrictions and not filtering, is it correct?

**Comment by oliver----** [comment]
@Integral The commit you referenced is about ListCommand.

**Comment by oliver----** [comment]
If we can not make sure that the FileDialog is only producing files of image type, then we must make sure to not create a figure if there is a non-image file selected.

**Comment by Integral** [comment]
sorry, it is a0028bc
we are sure, it will let you select only images

**Comment by oliver----** [comment]
Ah, ok. This is what I actually thought it would need. Thanks.
