### ISSUE TITLE
Table cells should wrap text always

### ISSUE THREAD

**Issue by michael** [substance/texture#895]
Reported by Giuliano.

We should prevent from such scenarios:

![image](https://user-images.githubusercontent.com/2931/45756812-21fdef00-bc22-11e8-9c14-c3ae7518ed6b.png)

Reproduce:

- insert a new table in Manuscript view
- add a long URL into one of the cells
- open Metadata view
- go to tables
There the table cells are not wrapped.

**Comment by oliver----** [comment]
@Integral this seems to be a CSS thingie. Could you help here?

**Comment by Integral** [comment]
I can't reproduce it.

**Comment by oliver----** [comment]
Looks like they have some long urls in the text.

**Comment by oliver----** [comment]
Can't reproduce neither.

**Comment by Integral** [comment]
@oliver---- i've tried long urls in chrome and electron... Everything is ok for me
![screen shot 2018-09-20 at 00 11 25](https://user-images.githubusercontent.com/182010/45781799-bfc8dc80-bc69-11e8-96ba-0aa6692d1c66.png)

**Comment by oliver----** [comment]
@michael do you have more details about this?

**Comment by oliver----** [comment]
@Integral let's wait then

**Comment by oliver----** [comment]
@michael also here you are needed

**Comment by michael** [comment]
Also can't reproduce.

@gmaciocci can you provide the steps you did to end up with the broken table layout?

**Comment by oliver----** [comment]
@gmaciocci Thx! now I can see it 😄

**Comment by oliver----** [comment]
@michael @Integral this seems to be a CSS thing.

**Comment by oliver----** [comment]
Added a 'Reproduce' to the issue description

**Comment by oliver----** [comment]
@Integral do you think you can fix this?

**Comment by Integral** [comment]
Will look into this

**Comment by Integral** [comment]
Fixed via c5be87c.

**Comment by oliver----** [comment]
THX!
