### ISSUE TITLE
Texture Desktop: Store as .dar files instead of a folder

### ISSUE THREAD

**Issue by michael** [substance/texture#896]
As reported by Giuliano:

> Saving does not create a folder / DAR with the article name, it dumps the manifest and main xml in whatever folder you clicked. 
> Texture does not associate itself with XML files in MacOS (another reason why DARs should be archives with their own extension and not just folders)

There's some beauty in using folders. Like that you can always look inside the documents and e.g. use Git to track changes made to some files, not the whole file. However there are of course limitations and confusion related to that approach.

I'd suggest to continue for a while with the folder approach until the Dar spec has fully stabilised. As soon as we introduce a file format (.dar) users will expect to be able to open them in all future versions of Texture.

**Comment by gmaciocci** [comment]
That makes file association impossible on desktop. If you're trying to encourage authors to move away from Word, I'm afraid dumping a bunch of xml files in the target folder (especially without a unique subfolder) won't be doing them any favours. Additionally, saving two documents in the same target folder will overwrite the first one, as you seen not to be giving saved files unique names (I always get manuscript and manifest)

**Comment by oliver----** [comment]
I agree that a folder as target is dangerous and a rather advanced feature. It makes sense only if the user wants to save into a git managed repo, for instance.

**Comment by Integral** [comment]
Couldn't we have both options? E.g. save as DAR by default and optionally
export files into folder?

**Comment by oliver----** [comment]
Probably it is better to move to a zip-file with `.dar` as extension. Format-/version-wise I don't see any difference here, because a folder is not much different to a zip file from our angle.

**Comment by gmaciocci** [comment]
@Integral @oliver---- If I may make a suggestion, I'd explore making saving of new files default to .dar zips, and have an "export XML" as a separate option. a single self contained DAR (and desktop file association) makes it easy to open a file multiple times while working on it, and to share it, whereas XML is more of a final product of the work. 

Please ask for a unique name either way (and create a unique subfolder with that name for the manuscript and the manifest for xml exports).

That said, if you open XML to begin with, your default save is XML, unless you do "save as" which will create a new DAR file with a new name.

**Comment by gmaciocci** [comment]
> you can choose that by creating a folder from the save dialog. 

Not to be difficult, but can you name me another application that saves every file with the same name, two files in fact (one which doesn't even make sense to the author), and dumps them in whatever target folder you pick without prompting you for a name?

I just did a test and pressed CMD-S (save) while working on a new document. I selected the folder where I store all my documents ("Documents") and Texture overwrote my previous manuscript without even asking. Unique names are essential. Overwrite confirmations also.

> I understand that's not what users are used to.

And there's your problem right there. You're already asking authors to get used to this whole semantic editing thing, and to drop the one authoring app they've been using their entire careers. maybe let's not also challenge every single one of their assumptions regarding the basic opening, saving and naming of documents. That's a solved problem, you don't get to stand out or innovate here. :)

**Comment by oliver----** [comment]
As @gmaciocci demonstrated, the folder approach need to be done way more carefully. As we don't do this at the moment, let's move to `.dar` quickly.
And let's do the advanced folder export later... it definitely needs more thinking.
@michael if you don't want to loose the ability to save to folders for maintaining our dev-examples, then I'd rather suggest to enable this as an export mode feature, e.g. when starting the dar-server.

**Comment by michael** [comment]
Yeah I'm fine with moving to .dar as the default. Just want to maintain the ability to ad-hoc edit folders. We could also have this as a hidden/pro feature. Like when you are in a dar folder start Texture from the command line.

```
$ texture .
```

Also fine with export dialog, that creates the static webpage.

**Comment by oliver----** [comment]
I start working on a ZIP based storage implementation that is used in Texture Desktop.

**Comment by oliver----** [comment]
> Note: this will not affect the browser version that talks to a dar-server, so for development we will still be able to maintain examples via Texture UI

**Comment by michael** [comment]
Think we should use tar.gz as the archive format underneath. When we did this the last time we figured that there's no standard that different implementations follow.

**Comment by oliver----** [comment]
You mean it is not possible to open zip files from different apps/os'es?

**Comment by michael** [comment]
I just remember there were issues with javascript/Node.js libraries to open and write zip archives. tar.gz certainly only works for Node.js but that's fine for our case (Desktop)... we don't need to read/write zip archives in the browser. 

We tried this in the times of Substance Composer, drag and drop a zip file onto a webpage and open it. ;)

**Comment by oliver----** [comment]
I'd rather prefer a random-access archive, which tar is not. The cool kids are using yazl and yauzl. I have seen an adapter for that for hyperdrive (-> dat) written by Max, when we were in Berlin.

**Comment by oliver----** [comment]
And this is probably going even more into the direction I am interested in: https://github.com/karissa/zip-to-hyperdrive

**Comment by oliver----** [comment]
Then we are essentially already on a `dar->dat` track.

**Comment by oliver----** [comment]
@michael @Integral @gmaciocci if you are interested here is a technical description of the architecture I have in mind.

https://docs.google.com/document/d/1xVchWFIR_bpfieQTsQDlszigkJvaAq3ZNzQvXbZbMBU/edit?usp=sharing

HTTP served DARs and local `.dar' files are pretty much the same for Texture after unpacking a `.dar` into an internal temporary folder.

**Comment by oliver----** [comment]
As a first iteration I will only do the mapping from `.dar` to the internal folder, not using hyperdrive as means for versioning.

**Comment by oliver----** [comment]
I have a first version ready in #915.

**Comment by oliver----** [comment]
![texture-opening-dars-via-file-browser](https://user-images.githubusercontent.com/284099/46083500-f7f38200-c177-11e8-975e-a1130e554396.gif)
