### ISSUE TITLE
Add overwrite confirmation dialog

### ISSUE THREAD

**Issue by michael** [substance/texture#899]
Currently it's too easy to overwrite existing files when using Texture Desktop > Save/ Save as.

**Comment by Integral** [comment]
@michael @oliver---- I think it's already there in electron@4, look:
![](http://g.recordit.co/5RA9wHk6Km.gif)

Or did you mean something else?

**Comment by oliver----** [comment]
Cool. Then this was easy ;)

**Comment by Integral** [comment]
@oliver---- yes ;) But need something else.
