### ISSUE TITLE
Table: scroll jumping when table is bigger than viewport

### ISSUE THREAD

**Issue by Integral** [substance/texture#906]
If you create a long table and start clicking oh a top cells you'll be scrolled down to the bottom of table:
![](http://g.recordit.co/zbryIJ6kin.gif)

**Comment by oliver----** [comment]
This has been caused by  keytrap.focus(). Just found out that there is an 'preventScroll' option for `el.focus()`. I remember we had some strange scroll problems in the past, similar to this, with Surface grabbing focus.

**Comment by oliver----** [comment]
Fixed via #910
