### ISSUE TITLE
Find and Replace: Select All in one of the inputs should not select all in the document.

### ISSUE THREAD

**Issue by oliver----** [substance/texture#912]
At the moment, keyboard events bubble up to the editor which handles certain combos, such as `CtrlOrCommand-a`, having the effect that `Select All` is applied to the area where the internal selection is.

![texture-find-and-replace-select-all](https://user-images.githubusercontent.com/284099/45834185-d40ee700-bd06-11e8-8e0e-7b77c9977516.gif)

We should either prevent all events from bubbling up, or consume certain combos.

**Comment by michael** [comment]
Yeah I saw that too. I wonder if it would make sense to use Substance TextInput instead of the native input fields. Maybe then we have things better under control? (also enabling commands cmd+g etc.)

**Comment by oliver----** [comment]
`Command-G` is more relevant as a short-cut for next, when the cursor is inside the doc.
Have you noticed, that you can travers with `ENTER`? `Shift-Enter` is not handled yet, though.

**Comment by oliver----** [comment]
Don't think that Substance TextInput is solving this problem for us.

**Comment by oliver----** [comment]
In this case it is really important to bind a keydown handler for `CtrlOrCommand+a` on the input. The SelectAllCommand is working only for Surfaces.

**Comment by oliver----** [comment]
Maybe I didn't understand your suggestion... It would make sense to have a native input component, which is having all the common handlers. That's true.
If Substance TextInput is doing this already, I'd suggest to move it into the kit.

**Comment by oliver----** [comment]
But don't use it for a model! :)

**Comment by oliver----** [comment]
Surfaces are bound to models. So the inputs in the FaRD(ialog) ;) are not candidates for Surfaces.

**Comment by michael** [comment]
The would need a detached (temporary model) of course. Anyways.. as said it was just a thought, since now this is the only place where we have `<input>` elements. :)

**Comment by oliver----** [comment]
That is an overkill. We are perfectly able to create a native input with enough handlers attached to be compliant with the rest of the Substance actors.

**Comment by oliver----** [comment]
Still it makes sense to have such a thing, so we do not need to reinvent it each time.

**Comment by oliver----** [comment]
> now this is the only place where we have <input> elements.

The key difference is that FaRD is app chrome, not content.

**Comment by michael** [comment]
Fair enough. Let's stick with what we have then.

**Comment by oliver----** [comment]
Yeah. Still I am in favor of creating a Component around Input which behaves nicely. :)

**Comment by oliver----** [comment]
Fixed via https://github.com/substance/texture/commit/64860304b46f5df232771efb81ddc059f934d298
