### ISSUE TITLE
Should Texture allow to open an 'XML' file directly?

### ISSUE THREAD

**Issue by oliver----** [substance/texture#913]
While this does not make sense for full DARs, it could ease 'debugging' in an early phase.
Texture could take the XML, and treat it as a DAR without assets... more in the sense of 'Create DAR from JATS XML'.

**Comment by michael** [comment]
That's more an import scenario.  Not sure if we should take over responsibility for that. Opening an XML will create all different kind of edge case scenarios. I think first there should be a CLI tool to convert those inputs to Dars (e.g. with fake images if they can't be resolved).

**Comment by oliver----** [comment]
This idea is documented, but we think it is not worth be pursued.
If somebody thinks differently, please comment on this issue.
