### ISSUE TITLE
Alignment of table cells

### ISSUE THREAD

**Issue by michael** [substance/texture#918]
We need align left,center,right. Or somerthing equivalent. There should be a way to align decimal points.

**Comment by michael** [comment]
@Melissa37 @JGilbert-eLife how is aligning to a decimal point done currently? Do you have examples?

**Comment by Melissa37** [comment]
>how is aligning to a decimal point done currently? Do you have examples?

https://jats.nlm.nih.gov/archiving/tag-library/1.2d1/attribute/char.html

We'll need to dig out some examples. To follow.
And add to the kitchen sink.

@FAtherden-eLife too.

**Comment by Melissa37** [comment]
>how is aligning to a decimal point done currently? Do you have examples?

There's been confusion at our end (in my head really!) and I have found out we don't support this on the website or the current tool. We do have authors asking to change the alignment sometimes, which creates manual processes.
It would be good to have input from the others in the consortium to find out if this is important to them?

**Comment by michael** [comment]
Tracked in requirements document. Closing.
