### ISSUE TITLE
Linux Build: Keyboard shortcuts not working

### ISSUE THREAD

**Issue by oliver----** [substance/texture#931]
For instance, `Ctrl+S` is not working. But it is working via Menu.

**Comment by lpanebr** [comment]
Let me know if and how should I test and/or provide logs to help debugging this. ;-)

**Comment by Integral** [comment]
@lpanebr we just tried out latest version of texture on latest lts version of Ubuntu and it's working fine.
We will release 2.0 in the end of the month, but currently you can build a latest version yourself and try it out. Please open a new issue if you'll find some errors.
