### ISSUE TITLE
We should be able to insert Reference Citations inside table cells, caption and title

### ISSUE THREAD

**Issue by lpanebr** [substance/texture#935]
Texture currently does not allow this, and yet it's something we see every day.

**Comment by lpanebr** [comment]
ow, and inside table footnotes also (when we have them #556).

**Comment by Melissa37** [comment]
Agree with this completely - and figure legends.

**Comment by JGilbert-eLife** [comment]
Ah, sorry! Accidentally part-duplicated this with the wider case of https://github.com/substance/texture/issues/970 (formatting, hyperlinks and so on also don't work in table cells).

The issue in this ticket also applies to figure titles.

**Comment by oliver----** [comment]
Almost done. Only for the title it is still missing.

**Comment by oliver----** [comment]
Solved via #1077
