### ISSUE TITLE
Importing CSL/JSON the app is not getting the file.type

### ISSUE THREAD

**Issue by sbirAECA** [substance/texture#942]
I'm trying to import references via CSL/JSON. I ensure the file is well formatted (I see it in the properties as well).

If I run the app (npm run app) then ReferenceUploadComponent is not getting the file.type, so is not uploading anything 

![npm run app](https://user-images.githubusercontent.com/37865559/46682442-d5d51780-cbed-11e8-99f0-3ebe0f8b7976.jpg)

... but if I start the dar server (npm start), and I check with the same JSON file, now I can see the file.type

![npm start](https://user-images.githubusercontent.com/37865559/46682581-33696400-cbee-11e8-8657-0b575276bacf.jpg)

Well, I would use the dar server option but every time I'm trying to save I obtain the same error 

![err](https://user-images.githubusercontent.com/37865559/46682806-e1750e00-cbee-11e8-9445-3f1d85a70dea.jpg)

**Comment by michael** [comment]
Thank you for reporting. @integral can u confirm that problem, and if yes work on a fix?

**Comment by sbirAECA** [comment]
Yes I confirm it, and I can help you, and not an expert but I think I can.
I have checked it with all sort of computers: Ubuntu 64 and Win 32 and 64, and in all cases I can't save when using dar-server

**Comment by Integral** [comment]
@sbirAECA can you please post here your CSL/JSON?

**Comment by sbirAECA** [comment]
I have to includle dummy DOIs because it is mandatory

[{
		"author": [{
				"family": "Acosta",
				"given": "Y.A."
			}, {
				"family": "Nabi",
				"given": "M.N."
			}, {
				"family": "Dornberger",
				"given": "U."
			}
		],
		"title": "Technological capability improvement as result of the entrepreneur's search for innovation in the SMEs in Colombia",
		"container-title": "Journal of Marketing Development \u0026 Competitiveness",
		"volume": "6",
		"page": "1–15",
		"URL": "https://search.proquest.com/docview/1315304098",
		"issue": "4",
		"language": "en",
		"urldate": "from",
		"issued": {
			"date-parts": [[2012]]
		},
		"id": "acosta2012a",
		"DOI": "doi_FICTICIO_010",
		"type": "article-journal"
	}, {
		"author": [{
				"family": "Cuero",
				"given": "Y."
			}, {
				"family": "Un Nabi",
				"given": "M."
			}, {
				"family": "Dornberger",
				"given": "U."
			}
		],
		"title": "Technological Capability Improvement as Result of the Entrepreneur's Search for innovation in the SMEs in Colombia",
		"container-title": "Journal of Marketing Development \u0026 Competitiveness",
		"volume": "6",
		"page": "1–16",
		"URL": "https://search.proquest.com/openview/4f5dfb4b55223e54bcaa85ec1ac19d30/1",
		"issue": "4",
		"language": "en",
		"urldate": "from",
		"issued": {
			"date-parts": [[2012]]
		},
		"id": "cuero2012a",
		"DOI": "doi_FICTICIO_010",
		"type": "article-journal"
	}, {
		"author": [{
				"family": "Kwon",
				"given": "M."
			}, {
				"family": "Cho",
				"given": "Y.C."
			}
		],
		"title": "Investigating effects of entrepreneurial orientation and management on performance: public vs. private sector",
		"container-title": "Journal of Marketing Thought",
		"volume": "4",
		"page": "12–24",
		"URL": "http://www.ejmt.org/download/201708/JMT2017_8_2.pdf",
		"issue": "2",
		"language": "fr",
		"urldate": "from",
		"issued": {
			"date-parts": [[2017]]
		},
		"id": "kwon2017a",
		"DOI": "doi_FICTICIO_010",
		"type": "article-journal"
	}, {
		"author": [{
				"family": "López",
				"given": "S.A."
			}, {
				"family": "López",
				"given": "M.C."
			}, {
				"family": "Ríos",
				"given": "M.M."
			}
		],
		"title": "Las capacidades tecnológicas y la experiencia empresarial",
		"container-title": "Revista TECSISTECATL",
		"volume": "19",
		"URL": "http://www.eumed.net/rev/TECSISTECATL/n19/capacidades.html",
		"language": "es",
		"urldate": "from",
		"issued": {
			"date-parts": [[2016]]
		},
		"id": "l2016a",
		"DOI": "doi_FICTICIO_010",
		"type": "article-journal"
	}, {
		"author": [{
				"family": "Poudel",
				"given": "K.P."
			}, {
				"family": "Carter",
				"given": "R."
			}, {
				"family": "Lonial",
				"given": "S."
			}
		],
		"title": "The process aspect of Entrepreneurial Orientation-Performance Relationship: Uncovering the mediating roles of technological capabilities, innovation, and firm growth",
		"container-title": "Frontiers of Entrepreneurship Research",
		"volume": "32",
		"page": "483–497",
		"URL": "https://digitalknowledge.babson.edu/fer/vol32/iss12/3",
		"issue": "12",
		"language": "en",
		"urldate": "from",
		"issued": {
			"date-parts": [[2012]]
		},
		"id": "poudel2012a",
		"DOI": "doi_FICTICIO_010",
		"type": "article-journal"
	}, {
		"author": [{
				"family": "Welter",
				"given": "C."
			}, {
				"family": "Bosse",
				"given": "D.A."
			}, {
				"family": "Alvarez",
				"given": "A.S."
			}
		],
		"title": "The interaction between managerial and technological capabilities as a determinant of company performance: an empirical study of biotech firms",
		"container-title": "International Journal of Management",
		"volume": "30",
		"page": "272–284",
		"URL": "https://search.proquest.com/docview/1315212905",
		"issue": "1",
		"language": "en",
		"urldate": "from",
		"issued": {
			"date-parts": [[2013]]
		},
		"id": "welter2013a",
		"DOI": "doi_FICTICIO_010",
		"type": "article-journal"
	}
]

**Comment by sbirAECA** [comment]
I'm sending y
[export.citeproc01_preparadoTexture.zip](https://github.com/substance/texture/files/2463746/export.citeproc01_preparadoTexture.zip)
ou the file

**Comment by Integral** [comment]
Thank you, I need some time for the investigation as it is working for MAC OS build.

**Comment by sbirAECA** [comment]
Sorry I don't have a MAC.
This is what I have to do to work

@@ -68,15 +68,17 @@ export default class ReferenceUploadComponent extends Component {
   }
 
   _handleUploadedFiles (files) {
     Object.values(files).forEach(file => {
       const isJSON = file.type.indexOf('application/json') === 0
-      if (isJSON) {
+	  // si comentamos estos hay que asegurarse que se estÃ¡n subiendo 
+	  // archivos CSL/JSON
+      //if (isJSON) {
         const reader = new window.FileReader()
         reader.onload = this._onFileLoad.bind(this)
         reader.readAsText(file)
-      }
+      //}
     })
   }
 
   _onFileLoad (e) {
     const res = e.target.result
Always ensuring I'm uploading json files

**Comment by Integral** [comment]
@sbirAECA I just installed latest version from master branch on Ubuntu, did `npm run app` and imported file from your archive. I can't see any problems.

**Comment by Integral** [comment]
I used this dialog... and you?
<img width="938" alt="screen shot 2018-11-08 at 19 15 16" src="https://user-images.githubusercontent.com/182010/48211530-ba932e80-e38a-11e8-936e-5a141152ee4c.png">

**Comment by sbirAECA** [comment]
Yes, pressing 'select'

**Comment by Integral** [comment]
Please give a try with fresh git clone

**Comment by Integral** [comment]
There are might be some other problems with building in Linux systems, see #1024

**Comment by sbirAECA** [comment]
Give me a moment

**Comment by sbirAECA** [comment]
Again, it is empty fileType (WIN 32)
![filetype](https://user-images.githubusercontent.com/37865559/48214853-26709980-e381-11e8-82dd-c1ad5897698f.jpg)

**Comment by sbirAECA** [comment]
Here is the screen when I run the command 'npm run app'



![npmrunapp](https://user-images.githubusercontent.com/37865559/48250735-9291e280-e3ff-11e8-858f-9b3262c44c63.jpg)

**Comment by Integral** [comment]
I will check Windows version, thanks

**Comment by Integral** [comment]
@sbirAECA, just to have a better understanding, what Windows are you using, what is your browser? You could see a report here: https://www.whatsmybrowser.org

**Comment by sbirAECA** [comment]
I'm not at work at this very moment. I'm at home. But I can try to test it.
Here is the rport of my home computer. I can tell you it is different from work
![ordenador](https://user-images.githubusercontent.com/37865559/48281303-766d6000-e456-11e8-99e5-92f088374d1b.jpg)

**Comment by sbirAECA** [comment]
Now, give me a moment to install texture

**Comment by sbirAECA** [comment]
git clone https://github.com/substance/texture.git ...
npm install ...

![npminstall](https://user-images.githubusercontent.com/37865559/48282132-11ffd000-e459-11e8-83e2-23a9d8664478.jpg)

**Comment by sbirAECA** [comment]
and npm run app ... 
![npmrunapp](https://user-images.githubusercontent.com/37865559/48282338-b5e97b80-e459-11e8-9542-36c224159c9b.jpg)

**Comment by sbirAECA** [comment]
It doesn't recognize file.type

![jsonfile](https://user-images.githubusercontent.com/37865559/48282584-66577f80-e45a-11e8-862a-fc0a43eb4ac1.jpg)

**Comment by Integral** [comment]
@sbirAECA thanks again, I will continue my investigation!

**Comment by Integral** [comment]
At last, I can see these problems on windows.

**Comment by Integral** [comment]
I will close this issue now since there is fix in master.
@sbirAECA, thank you very much! And please file a new issue about saving problems if you have it.
