### ISSUE TITLE
Support `<sec>` in abstracts?

### ISSUE THREAD

**Issue by axfelix** [substance/texture#945]
I'm not sure if there was an explicit decision made not to support structured abstracts in Dar -- I think this will probably be a limitation long-term and wanted to check what the plan is here.

**Comment by Melissa37** [comment]
I agree, it should be allowed and accommodated otherwise people will get around it by using bold tagging and <p>, which is less semantic.

**Comment by fabiobatalha** [comment]
Agree

**Comment by oliver----** [comment]
Absolutely, thanks for tracking.

**Comment by Melissa37** [comment]
eLife will require this, see the clinical trial recommendation from JATS4R:
https://jats4r.org/clinical-trials

We need to support this

**Comment by fabiobatalha** [comment]
Implemented in the version 1.2
