### ISSUE TITLE
Can't enter text to newly created footnote

### ISSUE THREAD

**Issue by pfeiffer0kristina** [substance/texture#947]
Hi! We are testing texture at the moment for DAI and I have a problem with the new released version when it comes to footnotes. Neither can I fill the field with information, nor can I crossref. I can open up a footnote field in metadata but then nothing more. In the code texture complains about a blank entry in ft resulting in a reload failure of the file....Sorry for asking, maybe I just do not get it but I cant solve by myself. In the previous versionj of texture it was fine! Thank you!

**Comment by Integral** [comment]
Hello!
Current version of Texture designed more for publishers, so idea was that you are editing and adding new footnotes through a metadata mode.
However, as I can see now you can't enter text to a newly created footnote, so this is actually a bug. Thanks for reporting!

**Comment by pfeiffer0kristina** [comment]
Thank you!

**Comment by Integral** [comment]
Fixed in master via #994. Not yet released.
