### ISSUE TITLE
Support for dedication content

### ISSUE THREAD

**Issue by fabiobatalha** [substance/texture#950]
Several articles have content as **dedication** in the article body. We should support this in the next versions.

Suggested implementation: https://jats.nlm.nih.gov/publishing/tag-library/1.2d1/element/disp-quote.html

``` xml
<body>
 <disp-quote content-type="dedication">
   <p>Pour André Clas, Sprachmittler, maître-passeur et ami</p>
 </disp-quote>
  ...
</body>
```

**Comment by michael** [comment]
Not sure I understand this requirement. Can you elaborate more, should this then be displayed in a special way? Is this used only by Erudit, or is it a general type of content?

**Comment by fabiobatalha** [comment]
Dedicatories are a common content in any kind of documents, it is important to be identified because it not makes part of the main text even it is placed inside the body. It works in the same way of epigraphs.

You can see an example in: https://www.erudit.org/fr/revues/arbo/2014-n4-arbo01600/1027428ar/

It will be mainly used to highlight the content with a custom style.

The JATS xml for this content is:

``` xml
  <body>
    <disp-quote content-type="dedicatory">
      <p>En souvenir de Catherine Viollet</p>
    </disp-quote>
    <sec>
      <label>1</label>
      <disp-quote content-type="epigraph">
        <p>L’étude des rapports entre le texte et l’image montre quelque chose d’essentiel, un
          savoir qui concerne le fonctionnement du langage et de l’image, notre connaissance et
          notre appréhension du monde, de manière plus évidente et visible que lorsque littérature
          et peinture fonctionnent séparément et comme en autarcie. Leur frayage est souvent de
          l’ordre du nécessaire.</p>
        <attrib>Louvel 2010 : 277</attrib>
      </disp-quote>
      <p>Les multiples ...</p>
      ...
   </sec>
   ...
  </body>
```

**Comment by fabiobatalha** [comment]
a dedication can be also expressed as an note in the article-meta.

``` xml
<article-meta>
  ...
  <notes notes-type="dedication">
    <note>En souvenir de Catherine Viollet</note>
  </notes>
  ...
</article-meta>
```

**Comment by michael** [comment]
Would be good to pick one representation for dedications. Could we collect user stories and make the ticket conform to the Feature Request template?

**Comment by fabiobatalha** [comment]
Yes @michael, at this moment I'm only reviewing our requirements, I'm also identifying together with @Melissa37 the overlapping requirements, at the end they will be all following the Feature Request template.

**Comment by pigeonm** [comment]
@michael the ideal way of tagging dedications would be in the body

**Comment by fabiobatalha** [comment]
continue a: https://github.com/substance/texture/issues/1316
