### ISSUE TITLE
Allow to control labels of list items

### ISSUE THREAD

**Issue by oliver----** [substance/texture#954]
reported by @JGilbert-eLife 

> We need to be able to add numbered, bullet-pointed and un-numbered lists

A common approach is to choose from `1.`, `a)`, `i)`, `I.`, etc. for ordered lists, for instance.

**Comment by oliver----** [comment]
@JGilbert-eLife what do mean with `un-numbered` lists?

**Comment by JGilbert-eLife** [comment]
Lists without a prefix character, as per the JATS allowed values:

![screen shot 2018-10-19 at 09 26 34](https://user-images.githubusercontent.com/1785305/47206738-4fed6500-d381-11e8-97dc-5cce0e842558.png)

**Comment by michael** [comment]
Tracked in requirements document.
