### ISSUE TITLE
Ability to add preformat blocks

### ISSUE THREAD

**Issue by oliver----** [substance/texture#966]

**Comment by michael** [comment]
Maybe we call this preformat as in JATS.

```xml
<preformat preformat-type="code">
def skip_test_launch_environ():
    host = Host()

    assert len(host._binders) == 0

    ioloop = IOLoop.current()

    async def run():
        result = await host.launch_environ('https://github.com/org1/repo1')
        ioloop.call_later(0.5, ioloop.stop)

    ioloop.add_callback(run)
    ioloop.start()

    assert len(host._binders) == 1

    binder = next(iter(host._binders.values()))
    assert 'request' in binder
    assert binder['request']['url'] == 'https://mybinder.org/build/gh/org1/repo1/master'
    assert binder['events'] == []
</preformat>
```

I guess we should also assume CDATA here. E.g. when you want to provide HTML code.

**Comment by Integral** [comment]
@michael, I would say that we should use ```code```. We already have it, but a bit unfinished. For inline code we are using `monospace`.
Did I miss something?

**Comment by Integral** [comment]
It looks to me that it might make sense to have a references to code blocks... @michael?

**Comment by oliver----** [comment]
@Integral interesting general question.
@michael I guess there are more things that could or should be referencable, e.g. sections etc.

**Comment by Integral** [comment]
Could I close this issue? Or do we need a references now?

**Comment by oliver----** [comment]
This is good for now.
