### ISSUE TITLE
Creating a footnote corrups document

### ISSUE THREAD

**Issue by tamirhassan** [substance/texture#967]
If you try to create a footnote in the Metadata view, you cannot edit it and it does not contain any fields. More critically, if you then try to save the file, you cannot reopen it as the parser reports an error, as per the JATS specification a footnote has to have at least a `<p>` tag. This bug is still present in the 1.0 release. 

```
    <fn-group>
      <fn id="_fn-1">
	</fn>
    </fn-group>
```

**Comment by Integral** [comment]
Thanks for reporting, we already know about this bug via #947.

**Comment by michael** [comment]
Closing in favor of #947.
