### ISSUE TITLE
Tables: Handling for wide tables

### ISSUE THREAD

**Issue by JGilbert-eLife** [substance/texture#972]
The current restriction on table width is not going to work for the more complex tables eLife (and presumably other journals) handle. It very rapidly becomes very cramped when dealing with more than six or seven columns, and tables can reach twenty columns +, or have a large amount of content per column cell.

![screen shot 2018-10-19 at 15 07 49](https://user-images.githubusercontent.com/1785305/47223283-c190d780-d3b0-11e8-80fe-77ab5540bdff.png)

**Comment by michael** [comment]
Need to think about it. Maybe we can just remove the horizontal space limit for tables. Alternatively allow horizontal scrolling.

**Comment by michael** [comment]
Tracked in requirements document.
