### ISSUE TITLE
Drop-downs disppear too quickly for user to select option

### ISSUE THREAD

**Issue by JGilbert-eLife** [substance/texture#979]
This affects both the license and language options

**Comment by michael** [comment]
That's indeed a bug. And will be fixed asap.

**Comment by Integral** [comment]
Fixed in master via #1021, thanks @JGilbert-eLife!

**Comment by helenum** [comment]
This is also happening with languages for keywords.

**Comment by michael** [comment]
@helenum new release will have those problems addressed (ready end of Feb).

**Comment by helenum** [comment]
Many thanks :)

HES







___________________
Helena Espírito Santo, Professora Auxiliar
Coordenadora, Departamento de Investigação & Desenvolvimento do ISMT <http://diinews.ismt.pt/>
Editora-chefe, Revista Portuguesa de Investigação Comportamental e Social <http://rpics.ismt.pt/index.php/ISMT/index>
Consultora, Gabinete de Apoio Psicológico do ISMT <http://helenum.ismt.pt/GAPSI1/Quem_somos.html>
Professora Auxiliar, Neurociências | Neuropsicologia | Psicopatologia do Adulto

Instituto Superior Miguel Torga
Rua Augusta, 46
3000-061 Coimbra
Portugal

Tel: (+351) 239 488 030
E-mail: investig@ismt.pt

No dia 28/01/2019, às 18:46, Michael Aufreiter <notifications@github.com> escreveu:

@helenum <https://github.com/helenum> new release will have those problems addressed (ready end of Feb).
