### ISSUE TITLE
Ability to add article subtitle

### ISSUE THREAD

**Issue by fabiobatalha** [substance/texture#985]
In Érudit several articles have subtitles. This is a common use in all sort of subject areas.

Texture should support the editing of this element in the article editing, including translations of the metadata in the metadata editing interface.

Example in Érudit: https://www.erudit.org/fr/revues/meta/1981-v26-n2-meta292/002157ar/

Example 1:

``` xml
<article-meta>
  ...
  <title-group>
    <article-title xml:lang="fr">Le langage des « gendarmes  » et des « voleurs »</article-title>
    <subtitle xml:lang="fr">Étude comparative du vocabulaire de la pègre et de la police en français et en anglais</subtitle>
  </title-group>
  ...
</article-meta>
```

Example 2:

``` xml
<article-meta>
  ...
  <title-group>
    <article-title xml:lang="fr">Éditorial</article-title>
    <subtitle xml:lang="fr">Un grand colloque pour une grande revue</subtitle>
  </title-group>
  ...
</article-meta>
```

**Comment by oliver----** [comment]
A first iteration has been done via https://github.com/substance/texture/pull/1097
