### ISSUE TITLE
Ability to add issue title

### ISSUE THREAD

**Issue by fabiobatalha** [substance/texture#987]
A lot of journals associate a title to its issues.

Texture should support the editing of this element in the metadata editing.

Example in Érudit: https://www.erudit.org/fr/revues/meta/2016-v61-n1-meta02588/1036984ar/

Example:

``` xml
    <article-meta>
      ...
      <pub-date date-type="issue">
        <season>mai</season>
        <year>2016</year>
      </pub-date>
      <pub-date publication-format="epub" date-type="pub">
        <day>28</day>
        <month>06</month>
        <year>2016</year>
      </pub-date>
      <volume>61</volume>
      <issue>1</issue>
      <issue-title xml:lang="fr">Des zones d’incertitudes en traduction</issue-title>
      <fpage>204</fpage>
      <lpage>220</lpage>
      ...
   </article-meta>
```

**Comment by Melissa37** [comment]
Agree this is a requirement for most journals.
eLife does not need it, just because we don't publish issues :-)

**Comment by oliver----** [comment]
@fabiobatalha should issue-title support rich-text or any annotation? or is this plain-text only?

**Comment by fabiobatalha** [comment]
@oliver---- Yes, we support this in Érudit Publishing Schema, so it should be available in Texture.

**Comment by fabiobatalha** [comment]
@oliver---- @Integral 

Sorry I have just realized that even we want to have rich-text in issue-title, JATS will not allow us to do that.

JATS spec: https://jats.nlm.nih.gov/publishing/tag-library/1.2d2/element/issue-title.html

**Comment by oliver----** [comment]
Interesting. As usual JATS green allows more here: https://jats.nlm.nih.gov/archiving/tag-library/1.2d1/element/issue-title.html.
At the moment Texture is based on JATS green. @fabiobatalha what is your opinion about this?

**Comment by oliver----** [comment]
Done.
