### ISSUE TITLE
texture integration

### ISSUE THREAD

**Issue by kaschioudi** [substance/texture#99]
Hello guys,

I have done some work to integrate texture editor with our stack.  Basically I created a new XML Store (cf. https://github.com/kaschioudi/texture/blob/xmlps/examples/XMLPSXMLStore.js) and modified package.js (from jats-editor folder) to use my new store instead of the example store. Then I ran `npm run bundle` to generate the bundle. 

The editor is successfully loaded and rendered. However I don't understand how texture loads resources.

For instance, when I load texture on a page with the following url  http://domain.com/manager/editor/id/1510. Then for  `<graphic xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="media/image1.png" ...>` the editor tries to fetch the resource from `http://domain.com/manager/editor/id/media/image1.png` instead of `http://domain.com/manager/editor/id/*1510*/media/image1.png`.

Did I miss a step in the integration process?

My customizations are available here: https://github.com/kaschioudi/texture/tree/xmlps

Thank you for your assistance.

**Comment by kaschioudi** [comment]
@axfelix

**Comment by michael** [comment]
Hey currently resources need to have a fully qualified url in the XML to work. However we should add an URL resolver, that can be configured. JATS also specified a baseurl attribute that could be use for resolving asset urls.

**Comment by axfelix** [comment]
This is what OJS does currently for static HTML articles -- we've gotten some questions from users wanting to upload their own pre-prepared JATS for use with the Lens Viewer that shipped in OJS 3.0:

>> For HTML documents, we're rewriting filenames. JMs will have pre-uploaded a set of images/CSS/etc. to go with the HTML.

For each of these, we look at the original filename (as it was on the system from which it was uploaded). We look for href="that_filename.jpg" in the HTML, and rewrite that with the proper URL.

From the user's perspective, they just use straight-up filenames. I suggest we try keeping the same convention.

**Comment by axfelix** [comment]
Basically, we need to figure out how we're going to make external media make sense in the context of OJS3 + Texture + our conversion stack hooks.
