### ISSUE TITLE
Cannot add citations to figure legends

### ISSUE THREAD

**Issue by JGilbert-eLife** [substance/texture#995]
Trying to add a figure citation in a figure legend just adds a new space. For references, the ??? is not displayed but I was (once) able to get the pop-up list of references to appear; however I could not get the reference to actually insert (though the list did respond as if I was selecting things). I could not then get the reference list to reappear and after clicking about, I saw this error in the console:

![screen shot 2018-10-23 at 17 38 19](https://user-images.githubusercontent.com/1785305/47376404-73e6d880-d6ea-11e8-9893-223291d536f7.png)

(I think I may have reported this elsewhere so please delete if this is a duplicate issue!

**Comment by oliver----** [comment]
Seems that we have forgotten to enable `<xref>` in the captions.

**Comment by michael** [comment]
Assigning this to 2.0 milestone as a backlog item.

**Comment by oliver----** [comment]
After further investigation, I found the source, and this can even be considered as critical. 
doc.findAll() is not working for regular DocumentNodes yet. Thus, in this case, the citation manager does not consider xrefs inside figures.

**Comment by oliver----** [comment]
Fixed via #1050
